### ISSUE TITLE
Confirm should not automatically hide a Generic Dialog

### ISSUE THREAD

**Issue by KenT2** [dddomodossola/remi#100]
After pressing the OK button in a Generic Dialog it would be useful if the dialog box was not automatically hidden, This allows the on_confirm callback to validate the fields in the dialog and hide it only if all are correct. If incorrect the on_confirm callback can instead write an error field which is automatically displayed.

If you are happy with the idea:

In remi/gui.py delete the line self.hide() in confirm_dialog.

In the examples. In  widgets_overview_app.py add self.dialog.hide() at line 246

**Comment by dddomodossola** [comment]
It should be better to inherit the GenericDialog and overloading the confirm_dialog member in order to implement a validation process. Maybe will write an example for this.
