### ISSUE TITLE
Tidy Append has broken Listview in  widgets_overview_app.py

### ISSUE THREAD

**Issue by KenT2** [dddomodossola/remi#102]
When the dialog is confirmed the key of  the selected item in dlistView is used to select the same item in listView in the main page. This relies on the same set of keys being generated for both listViews.

The code of listView needs to be the same as dlistView, but much better could new_from_list() use enumerate to generate a set of integer keys starting in zero. Integer keys starting at 0 are useful because it allows Apps to access internal arrays using the same index value  as the remi Listviews

**Comment by dddomodossola** [comment]
Hi Ken, now should be fixed. I used enumeration as you suggested.
