### ISSUE TITLE
TextInput "on_enter" not working properly

### ISSUE THREAD

**Issue by petrw** [dddomodossola/remi#107]
Hello,

first of all, i'd like say thank you for this library, i really like it. I've stumbled upon issue not being able control properly text value of TextInput widget. 

Example code
<pre>
import remi.gui as gui
from remi import start, App

class MyApp(App):
    def __init__(self, *args):
        super(MyApp, self).__init__(*args)

    def main(self):
        wid = gui.Widget(width=300, height=200)

        self.txt = gui.TextInput(single_line = True)
        self.txt.set_on_enter_listener(self, 'on_enter')        

        wid.set_layout_orientation(gui.Widget.LAYOUT_VERTICAL)

        wid.append(self.txt)

        return wid

    def on_enter(self, text):
        print "Input was", text
        self.txt.set_value("")

if __name__ == "__main__":
    start(MyApp, debug=True)
</pre>

Problem is that value is sometimes set to empty string but sometimes is needed switch between tabs in browser, do page refresh or so. Also few times didnt apply single_line parameter and widget was multiline one. Both glitches seems to be present on pretty recent versions of Chrome and FF. Thanks.

**Comment by dddomodossola** [comment]
Hi petrw,
Thank you so much for reporting this issue. Now should be fixed. Please try it and close if it is ok. ;-)
With this change I discourage the use of both onchange and onenter events. When you type enter, if you register also an onchange event, this will not be triggered.

**Comment by petrw** [comment]
Works like a charm, thank you :).
