### ISSUE TITLE
Memory usage of dynamic RemI interfaces

### ISSUE THREAD

**Issue by PURPORC** [dddomodossola/remi#108]
Hi,

Really having fun using RemI!

It's possible that I am making applications outside the main use case for RemI, but I think this issue can improve this nice little framework for all kinds of applications.

remi.server.runtimeInstances currently doesn't have a way to shrink and having it really big imposes a memory and cpu requirement. Using a weakref.WeakRefDictionary instead of a plain list gets us some free garbage collection of old widgets.

Please take a look at my one-file toy application which creates and destroys some widgets in a way that is realistic for my applications. (Mostly they query from database, display in a table, scrub table & repeat.)

I have instrumented the toy application with the guppy heap viewer, so please `pip install guppy`

To see what I am talking about, try the following on the two versions (differing only by usage of the weakref) I have attached:

1. start the application
2. click 'Add rows'
3. click 'Heap report'
4. click 'Clear rows
5. click 'Heap report'

In the weakref version, all those gui.TableItem instances go away and some memory is freed after the Clear rows.

Let me know if you have any questions or pointers.

Thanks and all the best!

[sample_interface_Standard.zip](https://github.com/dddomodossola/remi/files/162671/sample_interface_Standard.zip)
[sample_interface_weakref.zip](https://github.com/dddomodossola/remi/files/162672/sample_interface_weakref.zip)

**Comment by dddomodossola** [comment]
Created a pull request for the branch weakref_runtimeInstances with a possible solution about this. Would someone review?
@PURPORC Thank you for the contribution ;-)

**Comment by PURPORC** [comment]
It's so much better now! Thank you @dddomodossola
