### ISSUE TITLE
cpu usage during gui_updater()

### ISSUE THREAD

**Issue by PURPORC** [dddomodossola/remi#111]
Hi Davide and RemI community,

Back again! :bowtie: This time with a more nebulous question than the memory thing.

The programs based on RemI currently I have deployed 
* use the `multiple_instance=True`
* create a fair few gui.Widgets (probably 60-4000 per user)
* are configured with `update_interval=15.0`
* have about 15 users

I'm seeing a lot of periodic CPU usage on the server matching that update_interval. You can see it in the sample app ([sample_interface_Standard.zip](https://github.com/dddomodossola/remi/files/162671/sample_interface_Standard.zip)) I made to demo the memory issue too by loading up a few thousand rows and every update_interval, one CPU core maxes out for a couple of seconds and that is just with one instance. 

If I understand it correctly, every `update_interval`, `gui_updater()` does a lot of work building up the widget representations in order to compare to the previously sent widget representation.

Is there some way to ease this by keeping a "dirty" dictionary keyed by id which 
1. stores a boolean value 
2. keyed by widget id
3. set to True any time the widget is mutated
4. reset on successful send to web socket

That would mean `gui_updater()` can walk the tree of widgets and send the "dirty" ones without having to build the strings to compare with the previous copy.

But item 3 is the part that seems really tricky!! Maybe some decorator magic on all of the `gui.Widget`s' `set_XXX()` methods?

The other part of my question is about multi-threading v. multi-process... that is a big can of worms, right?

All the best!

**Comment by nzjrs** [comment]
While I think you might be using Remi for things outside its defined purpose, I agree there is scope for improving efficiency. My suggestion https://github.com/dddomodossola/remi/pull/96 in an earlier bug report was that we will keep wasting time playing whack-a-mole fixing and tweaking our own realtime front/backend communication logic when there are better performing, and in this case more extensible to fix this kind of issue, realtime websocket frameworks available.

Relatedly, I had a branch of remi that did what you suggest - rather than decorating all setters you just replace the attributes/style dicts with some versioned dictionary and bump version ever time it is modified.

**Comment by dddomodossola** [comment]
Improved update efficiency following the suggestion of nzjrs. Now VersionedDictionaries are used to determine changes in a widget and determine the necessity of an update.

**Comment by PURPORC** [comment]
This last update makes a huge difference to CPU usage, many thanks to @nzjrs and @dddomodossola!

Awesome, I don't have to rewrite my prototype yet... Using id() heavily saves so much wiring things up, I just wonder what is the price for that simplicity... :fearful: :ghost:

**Comment by dddomodossola** [comment]
Thank you too @PURPORC ! 

I don't understand what you mean when you say "...I don't have to rewrite my prototype yet... Using id() heavily saves so much wiring things up...". Can you explain me this?

**Comment by PURPORC** [comment]
Sorry for being vague/elliptical. It's all praise.

> I don't have to rewrite my prototype yet ...

= I'm happy that REMI can support my apps with the new-improved performance, and I don't have to turn back to a conventional web framework. The only thing coming up I need to start thinking about is TLS to help with proxy traversal for websockets.

> Using id() heavily saves so much wiring things up...

REMI is interesting in that it has the identity function `id()` at its heart. At first I thought "Wow, this is python written from another planet." But it seems to be what allows you to take python program state and emit the JS model and comms layer. The 'wiring' up involved in a web application framework where generally there is some template with some tags referencing property names declared in data model objects is somehow gone. It is a really neat trick! :spades: 

So far as I can tell, the other websocket frameworks don't do automatic generation of the frontend javascript. Or maybe I don't properly understand them and I could build the REMI-style abstraction on top of them. Well whatever, I can efficiently build something useful with REMI no problems. :grinning: 

Um I don't know the etiquette involved in closing issues, should the opener close it? I consider this issue very satisfactorily closed.

**Comment by nzjrs** [comment]
I also tested this overnight for reliability, so it seems to be fixed.
