### ISSUE TITLE
onclick() for Link widget

### ISSUE THREAD

**Issue by petrw** [dddomodossola/remi#113]
Hi, would be possible to add onclick method to Link widget so can be done page redirect programatically? Thank you.

**Comment by dddomodossola** [comment]
Hello @petrw , can you explain more precisely what you are aiming to do? Do you need a link that open a page of a website or a new view of you Remi application (like a dialog window) ?

**Comment by petrw** [comment]
Just ability to simulate clicking on Link widget and redirect browser window with Remi to some external page.

**Comment by dddomodossola** [comment]
This example shows how to send javascript messages to the browser and so open a new browser page. Is it ok?

```python
import remi.gui as gui
from remi import start, App
from threading import Timer


class MyApp(App):
    def __init__(self, *args):
        super(MyApp, self).__init__(*args)

    def main(self):
        verticalContainer = gui.VBox()
        verticalContainer.style['display'] = 'block'
        verticalContainer.style['overflow'] = 'hidden'

        
        self.count = 5
        self.counter = gui.Label('', width=200, height=30, margin='10px')
        verticalContainer.append(self.counter)
		
        # kick of regular display of counter
        self.start_timer()

        # returning the root widget
        return verticalContainer

    def start_timer(self):
        self.counter.set_text('Opening google in ' + str(self.count) + " seconds")
        self.count -= 1

        if self.count<0:
            javascript_command = "window.open('http://www.google.it')"
            self.send_spontaneous_websocket_message('javascript,' + javascript_command)
        else:
            Timer(1, self.start_timer).start()


if __name__ == "__main__":
    start(MyApp, debug=True, address='0.0.0.0')
```

**Comment by nzjrs** [comment]
I'm still confused why a normal link widget would not work?

**Comment by dddomodossola** [comment]
The normal link works for sure. I'm a bit confused too. I think that @petrw would like to programmatically open a new page without user interaction.

**Comment by petrw** [comment]
@dddomodossola thank you for this snippet, it is great to know that it is possible to invoke js command this way but still not what i had originally on mind.

<pre>
import remi.gui as gui
from remi import start, App
from threading import Timer

class MyApp(App):
    def __init__(self, *args):
        super(MyApp, self).__init__(*args)

    def main(self):
        verticalContainer = gui.VBox()
        verticalContainer.style['display'] = 'block'
        verticalContainer.style['overflow'] = 'hidden'

        self.link = gui.Link('http://google.com',"Link to google", False)
        verticalContainer.append(self.link)
        
        self.btn = gui.Button('Go to the google')
        self.btn.set_on_click_listener(self, "do_redirect")
        
        verticalContainer.append(self.btn)
        verticalContainer.append(self.link)
        
        return verticalContainer
        
    def do_redirect(self):
        # whole remi window gets redirected to google
        self.link.onclick()


if __name__ == "__main__":
    start(MyApp, debug=True, address='0.0.0.0')
</pre>

**Comment by nzjrs** [comment]
```python
self.btn = gui.Button('Go to the google')
self.btn.attributes['onclick'] = "window.location.href='http://www.google.com'"
```

maybe this sort of example should be added to the docs
