### ISSUE TITLE
SSL implementation of remi/server.py

### ISSUE THREAD

**Issue by PURPORC** [dddomodossola/remi#114]
Hi I have a [version of remi server](https://github.com/PURPORC/remi/commit/8352599e7d9b4c6bd9a33edcd53c65aa575123df) which uses an encrypted connection for the two channels. I think this might improve the situation traversing office proxies and it means we can use remi applications without worrying so much that there is tampering or eavesdropping on the communication channel.

The motivation was that I now need to authenticate against a corporate Active Directory and can't in good conscience collect and transport passwords in the clear. Currently I am just playing around with a self-signed one which browsers complain about, though I believe there are now mechanisms to get trusted certificates for free.

My version requires the two files named `server.key` and `server.crt` in the current working directory, but it should, I guess, all be parameterized.

I think it should be possible to implement the option of SSL or unencrypted connection within remi/server.py but I got a bit tangled up in the class inheritance of TCPServer and ThreadingMixIns etc.. :grimacing: ended up with a `server.py` that cannot do the standard unencrypted style.

Is this something that would be helpful generally? If so, I will have another try to make it fit in with the non-encrypted server. Obviously I would prefer to be able to use the official REMI!

All the best! :smile:

**Comment by nzjrs** [comment]
sounds reasonably interesting, but it is easier to discuss once you open a
pull request - I noticed a number of issues with the implementation

**Comment by dddomodossola** [comment]
@PURPORC yeah, it seems interesting. As nzjrs suggests, you can open a pull request in order to provide us access to the code and discuss it better.

**Comment by dddomodossola** [comment]
@PURPORC Have you news about this?
