### ISSUE TITLE
Add TreeView support

### ISSUE THREAD

**Issue by AngelEzquerra** [dddomodossola/remi#116]
REMI does not currently support adding treeview widgets. Many UI applications require representing hierarchical data that is well represented as a tree view.

**Comment by dddomodossola** [comment]
Thank you for your suggestion. I will work on it soon.

**Comment by nzjrs** [comment]
I'd try and do this with css3 only

**Comment by dddomodossola** [comment]
Yeah, should be the best way. :+1:

**Comment by dddomodossola** [comment]
Created a basic TreeView widget. Maybe we could add functionalities about selection and multiple-selection, maybe later.
