### ISSUE TITLE
Feature Request: Example of how to exit

### ISSUE THREAD

**Issue by lwanger** [dddomodossola/remi#119]
I may be missing something, but I don't see how to exit a running app (besides closing the window and hitting ctrl-c). Is there a more elegant way to exit? How about an example with a exit item in the file menu?

Thanks,

Len

**Comment by nzjrs** [comment]
if you want to make a desktop app, then you can use server.StandaloneServer
and then the app will be killed when the user closes the window.

Is that sufficient?

**Comment by lwanger** [comment]
Yes that helps. Is there a way to tell the App to shutdown and exit gracefullt from the code?

Len

Date: Fri, 27 May 2016 09:16:43 -0700

**Comment by nzjrs** [comment]
Not yet sadly

**Comment by lwanger** [comment]
Got it.

It's a really cool project, and I look forward to playing with it more.

Thanks!

Len

Date: Fri, 27 May 2016 11:55:23 -0700

**Comment by dddomodossola** [comment]
Here is implemented https://github.com/dddomodossola/remi/blob/exit_functionality/examples/closeable_app.py
