### ISSUE TITLE
Input dialog splits text at /

### ISSUE THREAD

**Issue by KenT2** [dddomodossola/remi#12]
When InputDialog is a single line, the text is longer than the box, and it contains a / it splits at /  and the remainder goes second line.

**Comment by dddomodossola** [comment]
@KenT2 This is caused by the internal behaviour of the browser. The only thing you can do is to add an attribute to theTtextInput in order to limit its content length:

```python
mydialog.inputText.attributes['maxlength'] = 20
```

**Comment by KenT2** [comment]
Thanks. I can't recreate this now. I might have reported it before single_line was incorporated so that could have fixed it.
