### ISSUE TITLE
input widgets not synchronized between clients

### ISSUE THREAD

**Issue by nzjrs** [dddomodossola/remi#121]
* start examples/widgets_overview_app.py
* open a second tab to the same UI
* adjust any input widget (the SpinBox, the Slider)

While remi detects the input change, it does not update the position of the widget so other clients also see it.

**Comment by dddomodossola** [comment]
@nzjrs I can't reproduce this. Is this already solved?

**Comment by nzjrs** [comment]
Up to you to decide. In my branch I reverted your commit which disabled input widget synchronization

https://github.com/loopbio/remi/commit/d930b214a0e26fc14744bf88089a952c5323dac0

You then reverted my revert here

https://github.com/dddomodossola/remi/commit/033cc770c54a4bdd2f4ab8839b4fa8c33baf7582

And then again here

https://github.com/dddomodossola/remi/commit/f42cc5eda8890507bf30d759e183064985bd19c2

**Comment by dddomodossola** [comment]
You are right, I made a little bit of confusion about this, this because I was searching for the best solution.  The actual implementation seems to be fine with the additional javascript code that restores the focus.
