### ISSUE TITLE
Styling of a push button is funky

### ISSUE THREAD

**Issue by pfalcon** [dddomodossola/remi#125]
With a normal unstyled browser push button, when you click on it, it becomes visibly "pressed", then on mouse up, it's depressed again (even though remains focused, with a marquee around it).

With remi styling, when a button is clicked, it actually becomes "depressed", with its shadow growing (which usually happens when object becomes higher, that's why I'm telling button is "depressed"). On mouse up, it stays "depressed".

**Comment by cyberpro4** [comment]
Mmmmmm I will check the push buttons mood soon!

**Comment by dddomodossola** [comment]
@cyberpro4 what about this?
