### ISSUE TITLE
Editor - position of drop-down widget cannot be changed with mouse

### ISSUE THREAD

**Issue by MrYsLab** [dddomodossola/remi#129]
Once a drop down widget is place on a top level widget, it cannot be repositioned  using a mouse. It can be repositioned manually by changing the values in the Attributes editor panel

**Comment by dddomodossola** [comment]
I've reproduced the bug. Searching for a solution.

**Comment by dddomodossola** [comment]
Fixed by adding a DragHelper on the top left corner of the selected widget.
