### ISSUE TITLE
Single line input dialog and Return key

### ISSUE THREAD

**Issue by KenT2** [dddomodossola/remi#13]
When InputDialog is a single line the Return Key adds a second line of text and the first line disappears.

**Comment by KenT2** [comment]
#48 does not solve this well where the TextInput is in a Generic Dialog and an Enter callback is not required on every field as it is the Dialog. It can be fudged by adding a dummy on_enter_listener to every TextInput field :-(

**Comment by dddomodossola** [comment]
Hi Ken, I think it could not be managed differently in the GenericDialog. I though that, on the textInputs that requires, you can set the on_enter_listener in order to accept the dialog.

**Comment by dddomodossola** [comment]
Now the InputDialog accepts the ENTER key as confirmation action.

**Comment by KenT2** [comment]
OK for InputDialog

In the GenericDialog situation there might be a number of single line TextInput fields the content of which are dependent on one another, so there is a validation function attached to the OK button which checks the dependencies. Pressing enter on each individual field should by default do nothing and, if it is single line, the return should no be placed in the field as the text then disappears. The optional on_enter listener could be used to do a validity check on an individual field but should not close the dialog

**Comment by fohnad** [comment]
Hello I am dealing with this problem now. Can TextInput be a single line? I use it like this:
txt = gui.TextInput(True, width='80%', height='20px')
but this way if I press Enter then it skips to another line and it is not single line anymore.

I would like to be able to have just one line input and after I change more of different textinputs than press some confirmation button.

**Comment by dddomodossola** [comment]
Late, but it's done.
