### ISSUE TITLE
Editor: Cannot use mouse to select widgets after saving and reloading

### ISSUE THREAD

**Issue by MrYsLab** [dddomodossola/remi#132]
Below is a project in progress. All code has been generated by the editor without any changes. After saving this file, closing the editor, reopening the editor and loading the file, individual widgets are no longer selectable (gain focus) by clicking on them. I can still set focus by using the drop down Instances List.
[rr7.txt](https://github.com/dddomodossola/remi/files/531352/rr7.txt)

**Comment by dddomodossola** [comment]
Now is fixed. ;-)

**Comment by MrYsLab** [comment]
Thanks!
