### ISSUE TITLE
Editor: Rendering in editor differs from that in browser

### ISSUE THREAD

**Issue by MrYsLab** [dddomodossola/remi#134]
I am running Ubuntu 16.10 64 bit with Google Chrome Version 54.0.2840.59 (64-bit)
If you compare the Raw Sensor Data panel at the bottom of the screen, the "Line Followers" field is rendered correctly in the editor, but not in the browser (screen shots provided below).

![editor_render](https://cloud.githubusercontent.com/assets/5189838/19413248/cc38eedc-92f5-11e6-8ae8-a6cb1a22842d.png)
![browser_render](https://cloud.githubusercontent.com/assets/5189838/19413250/cfe6c3e2-92f5-11e6-90ae-65bfc7cd115b.png)
Generated Code: [rr8.py](https://github.com/dddomodossola/remi/files/531399/rr8.txt)

**Comment by dddomodossola** [comment]
You will now see an additional css editable parameter 'overflow'. It's value is 'auto' as default. Set it to 'visible', 'hidden' or 'scroll' to have a well defined visual behavior.

**Comment by MrYsLab** [comment]
Thanks!
