### ISSUE TITLE
Editor: labeled checkbox does not generate code for onchange listener signal

### ISSUE THREAD

**Issue by MrYsLab** [dddomodossola/remi#146]
The non-label checkbox does not exhibit this behavior.

 If I add a labeled checkbox and then select an onchange listener in signal connections, no code is generated for this listener. If I select onclick listener, the code for that listener is generated correctly.

**Comment by dddomodossola** [comment]
Fixed ;-) Thank you!

**Comment by MrYsLab** [comment]
Thanks again!
