### ISSUE TITLE
can't open widgets_overview_app.py

### ISSUE THREAD

**Issue by mohsenuss91** [dddomodossola/remi#160]
After
`python setup.py install`

I've got this:

`can't open file 'widgets_overview_app.py': [Errno 2] No such file or directory`

**Comment by dddomodossola** [comment]
Hello mohsenuss91, when you install the library by means of pip, you don't get the examples and the editor. You should download or clone the repo, and you will find inside all you need. Then, go inside the examples folder, and you will find widgets_overview_app.py.  ;-)
