### ISSUE TITLE
Example using plotly

### ISSUE THREAD

**Issue by saewoonam** [dddomodossola/remi#162]
First, I would like to thank you for writing "remi."   I have been using it to control instrument in my research lab.  An additional thing that I needed was a way to plot data being collected.  I have always found matplotlib a little challenging when trying to make real-time plots.

Anyway, I have figured out how to use plotly with remi.   I've attached a piece of example code that I have written.  I hope that you will consider adding it to your examples... Or at least, I hope you can.  I didn't look at the licensing issues with plotly.   

Cheers,
SaeWoo

[plotlyExample.py.txt](https://github.com/dddomodossola/remi/files/602452/plotlyExample.py.txt)

**Comment by dddomodossola** [comment]
@saewoonam Thank you so much for contributing! I will add this script to examples quickly.
