### ISSUE TITLE
Typing negative number into SpinBox

### ISSUE THREAD

**Issue by saewoonam** [dddomodossola/remi#164]
The spinbox class doesn't permit typing a negative number.  The "-" character isn't accepted.  It looks like a simple fix on line 2000 of gui.py.

**Comment by dddomodossola** [comment]
Thank you for reporting. Will be fixed soon! ;-)

**Comment by dddomodossola** [comment]
Should be fixed now. Does it work also for you?

**Comment by saewoonam** [comment]
In the development branch, yes.
