### ISSUE TITLE
MenuItem widgets appear under a button and cannot be used

### ISSUE THREAD

**Issue by KenT2** [dddomodossola/remi#165]
Title says it all. Does not happen with labels or images and I canot see anything special in gui.py about Buttons.

Can be demonstrated on widgets_overview_app by moving the Menus and Button around.

**Comment by dddomodossola** [comment]
@KenT2 Can you please better explain how to reproduce this problem? I'm unable to find it out.

**Comment by KenT2** [comment]
Example attached

I have added dummy menu items to widgets_overview_app.py so that the File menu appears under the button

[menu_demo.py.txt](https://github.com/dddomodossola/remi/files/966657/menu_demo.py.txt)

**Comment by KenT2** [comment]
Attached is another example in which the menu appears below other items.

Changing HBox to Widget in line 27/28 solves the problem, which Is what I do in Pi Presents.

Example is a cut down version of Pi Presents pp_web_editor.py

[menu_hbox.py.txt](https://github.com/dddomodossola/remi/files/966678/menu_hbox.py.txt)

**Comment by dddomodossola** [comment]
Fixed on development branch with commit 2933ee234200529d46ae5062f1f546a45bb373e5. Thank you for reporting @KenT2
