### ISSUE TITLE
Allow Dialogs to be called from Dialogs and a base Dialog class

### ISSUE THREAD

**Issue by KenT2** [dddomodossola/remi#167]
Using the Generic Dialog it is not possible to call Dialogs from Dialogs, only from the main window. The problem is that set_root_widget() is a method of the base instance and not of the current dialog instance.

The attached file is a hack solution to the problem. It is not a good solution because show() has different parameters depending on where it is called from.

I have also extracted the key methods of a dialog from GenericDialog and encapsulated them in a new Class  - Dialog. Including Dialog in gui.py would allow the construction of dialogs entirely to the programmers wishes.

[dialog.txt](https://github.com/dddomodossola/remi/files/659532/dialog.txt)

**Comment by KenT2** [comment]
A better solution is attached. It gets rid of the second parameter thus maintaining backwards compatibility.

Not sure it is the whole solution as it relies on there being only one main window in an App.

[dialog.txt](https://github.com/dddomodossola/remi/files/659700/dialog.txt)

**Comment by KenT2** [comment]
My hack is incorrect. it works perfectly with IP-127.0.0.1 but is unstable when the browser is on a machine other then the server machine

**Comment by dddomodossola** [comment]
Hello Ken,

Here is a possible solution for you
[nested_dialogs_app.py.txt](https://github.com/dddomodossola/remi/files/681361/nested_dialogs_app.py.txt)

Please let me know if this satisfies your needs ;-)

**Comment by KenT2** [comment]
After further investigation I found that the instability was not due to dialogs so the reference to #169 is incorrect.

Davide, thanks, your solution works well. It might be worth adding the App to examples.
