### ISSUE TITLE
Width and height paramters for the file selection dialog.

### ISSUE THREAD

**Issue by KenT2** [dddomodossola/remi#18]
It would be good to have the width and height of the FileSelectionDialog as parameters. As a fix I changed the height of the FileSelectionDialog locally in gui.py but  the number of entries displayed does not change with the height

**Comment by KenT2** [comment]
Width and height work fine if they are specified in the call. However if they are not and the defaults are used I get this error message:

Traceback (most recent call last):
  File "/home/pi/manager-for-pipresents/gui/server.py", line 245, in on_message
    callback(**paramDict)
  File "/home/pi/manager-for-pipresents/gui/gui.py", line 1062, in onclick
    return self.eventManager.propagate(self.EVENT_ONCLICK, params)
  File "/home/pi/manager-for-pipresents/gui/gui.py", line 49, in propagate
    return getattr(listener['instance'], listener['funcname'])(*params)
  File "pp_manager.py", line 460, in on_profile_copy_clicked
    fileselectionDialog = gui.FileSelectionDialog('Copy Profile', 'Select a Profile to copy',multiple_selection = False, selection_folder = self.top_dir)
  File "/home/pi/manager-for-pipresents/gui/gui.py", line 1001, in __init__
    super(FileSelectionDialog, self).__init__(width, 160, title, message)
  File "/home/pi/manager-for-pipresents/gui/gui.py", line 441, in __init__
    t = Label(self.width - 20, 50, title)
TypeError: unsupported operand type(s) for -: 'str' and 'int'

**Comment by dddomodossola** [comment]
Hi Ken,

The problem is that you have to use the 'labels' of the parameters for the title and the message:
fileselectionDialog = gui.FileSelectionDialog(title='Copy Profile', message='Select a Profile to copy',multiple_selection = False, selection_folder = self.top_dir)
Please feedback.

**Comment by KenT2** [comment]
Yes, my mistake. All works fine thanks.
