### ISSUE TITLE
New Widget: Title

### ISSUE THREAD

**Issue by merlink01** [dddomodossola/remi#189]
It would be nice to have a Title Widget that generates a text widget with h1 to h6.

I did create a title with a label, but this wasn't very nice.

**Comment by MaxMorais** [comment]
@merlink01 you can use the `gui.Tag` or `gui.Widget` constructors, for that case they are the same

eg:

```py
h1 = gui.Tag(_type="h1")
h1.add_child("text", "Hello H1")
```

The difference between `gui.Tag` and `gui.Widget` is that `gui.Widget` support all most events, while `gui.Tag` not!

**Comment by merlink01** [comment]
Hi Max, this was fast.

Thank you for this hint. 

Could this also be done in editor?

**Comment by MaxMorais** [comment]
@merlink01 no, for now the editor, doesn't provide any option to handle that
