### ISSUE TITLE
FileDownloader not chunk based --> MemoryError

### ISSUE THREAD

**Issue by merlink01** [dddomodossola/remi#193]
The File Downloader should work fit tilesystem objects and deliver downloads chunk by chunk.

At the Moment bigger files Crash with an Memory Error.

I tried to workaround this problem by patching the Downloader Class:

    class Downloader(gui.FileDownloader):
        def __init__(self, *args, **kwargs):
            super(Downloader, self).__init__(*args, **kwargs)
            self.filehandle = kwargs["filehandle"]

        def download(self):
            headers = {'Content-type': 'application/octet-stream',
                       'Content-Disposition': 'attachment; filename=%s' % self._filename}
            return [self.filehandle, headers] 

But it didn't work. The Object String is returned.

**Comment by dddomodossola** [comment]
Thank you for reporting. Can you please provide a traceback about the Memory Error you mentioned? Where you get the error, on python or browser side?

**Comment by merlink01** [comment]
See gui.py Line 2494

    class FileDownloader(Widget, _MixinTextualWidget):
        """FileDownloader widget. Allows to start a file download."""

        @decorate_constructor_parameter_types([str, str, str])
        def __init__(self, text, filename, path_separator='/', **kwargs):
            super(FileDownloader, self).__init__(**kwargs)
            self.type = 'a'
            self.attributes['download'] = os.path.basename(filename)
            self.attributes['href'] = "/%s/download" % self.identifier
            self.set_text(text)
            self._filename = filename
            self._path_separator = path_separator

        def download(self):
            with open(self._filename, 'r+b') as f:
                content = f.read()
            headers = {'Content-type': 'application/octet-stream',
                       'Content-Disposition': 'attachment; filename=%s' % os.path.basename(self._filename)}
            return [content, headers]

in the Line:
content = f.read() 

Python throws a Memory Error.

In this line the whole file is read into the variable content (into ram).

If the Filesize is small, there is no problem, but if you use a File that is really big, python crashes.

I can provide a small testscript if you want.

**Comment by merlink01** [comment]
Here is the traceback:

  File "...\__remi__bug\remi\server.py", line 789, in do_GET
    self._process_all(path)
  File "...\__remi__bug\remi\server.py", line 858, in _process_all
    content, headers = get_method_by_name(get_method_by_id(widget), function)(**param_dict)
  File "...\__remi__bug\remi\gui.py", line 2509, in download
    content = f.read()
    MemoryError

**Comment by merlink01** [comment]
Here it the testscript:

    import remi
    import remi.gui as gui
    class App(remi.App):
        def main(self):
            #Root
            f = open('test.bin',"wb")
            size = (1024*1024*10000)
            f.seek(size-1)
            f.write("\0")
            f.close()
            self.root = gui.Widget(width='100%', height='100%')
             #~ text, filename
            downloader = gui.FileDownloader('Download Me', 'test.bin')
            self.root.append(downloader)
            return self.root
    if __name__ == '__main__':
        remi.start(App)

Attention, this script creates a 10GB file in the working directory!

**Comment by merlink01** [comment]
Here is a workaround I found:
Line 875 in server.py:

            try:
                if hasattr(content,'read'):
                    while True:
                        data = content.read(1024*100)
                        if not data:
                            content.close()
                            break
                        self.wfile.write(data)
                else:
                    self.wfile.write(content)
            except:
                self.wfile.write(encode_text(content))

So the way is:
Check if variable content is a filelike object, with the function "read()",
if so read chunks (100kB) and write them to the client.

For this to run you have to change the Downloader function:

    class FileDownloader(Widget, _MixinTextualWidget):
        """FileDownloader widget. Allows to start a file download."""

        @decorate_constructor_parameter_types([str, str, str])
        def __init__(self, text, filename, path_separator='/', **kwargs):
            super(FileDownloader, self).__init__(**kwargs)
            self.type = 'a'
            self.attributes['download'] = os.path.basename(filename)
            self.attributes['href'] = "/%s/download" % self.identifier
            self.set_text(text)
            self._filename = filename
            self._path_separator = path_separator

        def download(self):
            f = open(self._filename, 'r+b'):
            headers = {'Content-type': 'application/octet-stream',
                       'Content-Disposition': 'attachment; filename=%s' % os.path.basename(self._filename)}
            return [f, headers]

**Comment by merlink01** [comment]
Here a version with 2 more features:
1. Put the Filesize in the headers, so firefox could calculate remaining time.
2. Optional use a filelike object instead of a filename. So you could download data out of StringIO for example.

    class FileDownloader(Widget, _MixinTextualWidget):
        """FileDownloader widget. Allows to start a file download."""

        @decorate_constructor_parameter_types([str, str, str])
        def __init__(self, text, filename, path_separator='/', fileobj=None, **kwargs):
            super(FileDownloader, self).__init__(**kwargs)
            self.type = 'a'
            self.attributes['download'] = os.path.basename(filename)
            self.attributes['href'] = "/%s/download" % self.identifier
            self.set_text(text)
            self._filename = filename
            self._fileobj = fileobj
            self._path_separator = path_separator

        def download(self):
            if self._fileobj:
                content = self._fileobj
            else:
                content = open(self._filename, 'r+b')
                
            headers = {'Content-type': 'application/octet-stream',
                       'Content-Disposition': 'attachment; filename=%s' % os.path.basename(self._filename)}
                       
            if hasattr(content,'seek'):
                try:
                    content.seek(0,2)
                    headers['Content-Length'] = str(content.tell())
                    content.seek(0)
                except:
                    pass
                    
            return [content, headers]

**Comment by dddomodossola** [comment]
@merlink01 Thank you a lot for the great work! I will try this soon and merge it ;-)

**Comment by merlink01** [comment]
Found a second small bug:
     'Content-Disposition': 'attachment; filename=%s' % os.path.basename(self._filename)}
should be:
     'Content-Disposition': 'attachment; filename="%s"' % os.path.basename(self._filename)}

if an space is in filename, the filename is cutted:
Fe: "test file.txt" will be "test" on downloads.

**Comment by dddomodossola** [comment]
Thank you so much! Will merge this soon

**Comment by dddomodossola** [comment]
@merlink01 I feel a bit uncomfortable about chunking the file to download in an arbitrary size of 1024*100. The memory error depends on platform and system characteristics. Maybe the best chunk size should determined by the peculiarities of http protocol itself. What is the best size for an http packet?

**Comment by merlink01** [comment]
Whats about an optional Parameter?

**Comment by nzjrs** [comment]
This whole thing feels kind of terrible. The more workarounds like this get added, the more remi will end up building a very bad webserver and not focusing on it's core competency as a web-ui-toolkit. Due to the whole architecture of remi this whole thing ends up going via memory as it's just not possible to do lazy yielding chunked request handling like werkzeug or alike do.
