### ISSUE TITLE
set_on_dblklick _listener not implemented yet?

### ISSUE THREAD

**Issue by merlink01** [dddomodossola/remi#194]
I can see in the widget documentation the existance of an ondblclick event,

Bit there doesn't seems an implementation of this.

Is a dblklick function usable at the moment, or should I implement it somehow?

Thanks.

**Comment by dddomodossola** [comment]
This is because of an incompatiblity with other events. In particular (if I remebmer right) it couldn't coexist with on_click event. You can however get the double click by the onclick, just considering a timeout.
