### ISSUE TITLE
on_key_down listener on a TextInput widget

### ISSUE THREAD

**Issue by batzkass** [dddomodossola/remi#197]
I would like to trigger an event when the user changes a value in a TextInput widget.
So I do : my_text_input.set_on_key_down_listener(...)
But now, when I try to change the value in the TextInput, my change is only taken into account half the time. See [this example](http://francois.kneib.free.fr/bug_on_key_down.py) to watch the behaviour.

**Comment by dddomodossola** [comment]
@batzkass Should be fixed now in **development** branch. Please confirm this. Furthermore I would like to inform you a new event "onkeyup" implemented. "onkeyup" generates when user releases a key. In comparison "onkeydown" event returns always one char behind.

**Comment by batzkass** [comment]
Many thanks, your fix is working in my setup.
