### ISSUE TITLE
Remi Examples / Editor fail on Table Widgets

### ISSUE THREAD

**Issue by jemcgrath1** [dddomodossola/remi#198]
HI,

Current Master build examples work except for anything that does NOT contain the table widget.
Attempting to run the following examples fails with an error, as an example:

table_widget example

  File "C:\Program Files\Python36\lib\site-packages\remi\server.py", line 788, in do_GET
    self.client.root = self.main(*self.server.userdata)
  File "table_widget_app.py", line 32, in main
    table = gui.TableWidget(10, 3, True, True, width=300, height=300)
**AttributeError: module 'remi.gui' has no attribute 'TableWidget'**

and editor

  File "C:\Program Files\Python36\lib\site-packages\remi\server.py", line 788, in do_GET
    self.client.root = self.main(*self.server.userdata)
  File "editor.py", line 435, in main
    self.widgetsCollection = editor_widgets.WidgetCollection(self, width='100%', height='50%')
  File "C:\Temp\remi-master\editor\editor_widgets.py", line 462, in __init__
    self.add_widget_to_collection(gui.TableWidget, width='100px', height='100px')
**AttributeError: module 'remi.gui' has no attribute 'TableWidget'**

Any suggestions/solutions to address this?

**Comment by dddomodossola** [comment]
@jemcgrath1 I tried it just now and it works. It could be probably you are using another version different from master? Maybe you installed from pip?

**Comment by jemcgrath1** [comment]
Hmmm... you may be right.

I will remove and install manually and advise tomorrow

Kind regards,

James McGrath

**Comment by jemcgrath1** [comment]
Just tested with a manual install direct from master, can now confirm that it is working :)

I must have installed via pip.

Thank you for the rapid response

**Comment by dddomodossola** [comment]
You are welcome ;-)

**Comment by ConnorSMaynes** [comment]
I am now having this problem. I downloaded from github and installed manually.
