### ISSUE TITLE
Idle Method configuration parameter

### ISSUE THREAD

**Issue by KenT2** [dddomodossola/remi#20]
The idle interval configuration parameter affects gui's response to button presses etc.  In addition it affects how often the idle method is run. It would be good to separate these so the config is just for idle()

**Comment by dddomodossola** [comment]
Right now, the idle function is strictly related to the graphic update. What's the purpose of your request?

**Comment by KenT2** [comment]
I need to poll another process at intervals to see if it is running. I need to do this regularly, not just when there is a user event and Idle seemed to be the way you wanted it done,

Having thought about it further I think it would be better for Remi to implement an interval alarm like the tkinter.after() function

obj = gui.After(Interval (mS),'callback') and gui.AfterCancel(obj)

the alarm time is guaranteed to be not less than Interval but it can be more. It is a single shot alarm so if you want a repetitive interval you call After inside the callback.

This is probably safer from race conditions than Idle and more flexible. It would however need the ability to set an initial interval alarm in main() or in a callback that happens just after main() but before user events are serviced.

**Comment by nzjrs** [comment]
you can start your own thread.Timers in main() and then do what you want in that callback.

**Comment by dddomodossola** [comment]
Here is an example in order to start a new Timer with preferred interval:
```py

class MyApp(App):
    def main(self):
        my_interval_func(0.1) #first call, then the function is called automatically by timer

def my_interval_func(update_interval):
    #here your operations executed at every update_interval
    Timer(update_interval, my_interval_func, (update_interval,)).start()
```

**Comment by KenT2** [comment]
Thanks
Have added an example of use to widgets_overview_app.py
