### ISSUE TITLE
There is no Textinput type "password"

### ISSUE THREAD

**Issue by eseunghwan** [dddomodossola/remi#206]
I'm testing remi, building a simple login page.
But I found there is no "password" type in Textinput class, so I used trick like below.
self.attributes[self.EVENT_ONKEYUP] = "var self = document.getElementById('%(id)s');" \
                "var key_code = event.keyCode ? event.keyCode : event.charCode;" \
                "if ( (key_code >= 48 && key_code <= 57) || (key_code >= 65 && key_code <= 90) || (key_code >= 97 && key_code <= 122) ) {" \
                "self.attributes['text'].value += event.key;" \
                "if (self.attributes['type'].value == 'password') {" \
                "var show_text = '';" \
                "for (var i in self.attributes['text'].value) {" \
                "show_text += '*';" \
                "}" \
                "self.value = show_text;" \
                "}" \
                "}" \
                "else if (key_code == 8) {" \
                "self.attributes['text'].value = self.attributes['text'].value.slice(0, -1)" \
                "}" % {'id': self.identifier}

but attribues didn't changed.

Is there any way to use masking?

here is my current output.
![image](https://user-images.githubusercontent.com/22045289/33795377-8ee78e2a-dd23-11e7-9e75-ef6b01e60f5e.png)

**Comment by dddomodossola** [comment]
Hello @eseunghwan, here is an example for you. The generic "Input" class is the solution ;-)

```python
import remi.gui as gui
from remi import start, App


class MyApp(App):
    def __init__(self, *args):
        super(MyApp, self).__init__(*args)

    def main(self):
        wid = gui.HBox(width=300, height=200, margin='0px auto')
        wid.style['padding'] = '10px'
        lbl = gui.Label("Type your password and press enter")
        lbl.style['margin'] = 'auto'

        self.pwdInput = gui.Input(input_type='password')
        self.pwdInput.set_on_change_listener(self.on_pwd_enter, lbl)

        wid.append(lbl)
        wid.append(self.pwdInput)

        # returning the root widget
        return wid

    # listener function
    def on_pwd_enter(self, emitter, pwd, lbl):
        #self.notification_message("Pwd ok", pwd, "")
        lbl.set_text("Password entered: " + pwd)

if __name__ == "__main__":
    start(MyApp, debug=True)
```
