### ISSUE TITLE
gui.Image can't properly read image

### ISSUE THREAD

**Issue by GdoongMathew** [dddomodossola/remi#207]
Hi, first of all, This library really saved a lot of my time. Thank you.
my problem is, when I set my image path in gui.Image(), it seems that it can only read images under folder '/remi/res/'. Even after I set it to my absolute path (let's just say "/home/pi/Downloads/static/images/img.jpg" since i'm using raspberry pi as the platform.), the website ends up no image. I'm not sure if i was doing it properly or it's actually a bug. 
Thanks.

**Comment by dddomodossola** [comment]
@Gdoong426 I'm pleased to see you found remi library useful. I suppose you get this problem because you forgot to specify the 'static_file_path' parameter to the App super constructor. Look at minefield_app.py example for the usage. If this is not enough,  please share your code to precisely find the possible mistake ;-)

**Comment by Gdoong426** [comment]
Thanks for the quick reply. After I specified the static_file_path parameter the same as the example, the webpage still shows nothing. My working dir is '/home/pi/Downloads', and my images are stored under '/home/pi/Downloads/static/image'. 
the following is a partial of my code:
` 
class MyApp(App):
    def __init__(self, *args):
        # statci_path is '/home/pi/Downloads/'
        static_path = os.path.dirname(os.path.abspath(__file__))
        super(MyApp, self).__init__(*args, static_file_path=static_path)

    def main(self, name='world'):
        # the arguments are width - height - layoutOrientationOrizontal
        global camera, resol_h, resol_w
        wid = gui.Widget(width=850, height=900, margin='0px auto')
        self.opencvideo_widget = camera
        self.opencvideo_widget.style['margin'] = '20px'

        horizontalContainer = gui.Widget(width='100%', layout_orientation=gui.Widget.LAYOUT_HORIZONTAL, margin='0px', style={'display': 'block', 'overflow': 'auto'})
        self.subContainerLeft = gui.Widget(width='410', style={'display': 'block', 'overflow': 'auto', 'text-align': 'center'})
        self.subContainerRight = gui.Widget(style={'width': '410px', 'display': 'block', 'overflow': 'auto', 'text-align': 'center'})

        self.weldimg = gui.Image('/Downloads/static/image/weld.jpg', width=int(resol_w / 2.5), height=int(resol_h / 2.5), margin='10px')
        self.noweldimg = gui.Image('/Downloads/static/image/noweld.jpg', width=int(resol_w / 2.5), height=int(resol_h / 2.5), margin='10px')`

**Comment by Gdoong426** [comment]
probably it's my fault. it seems that the image can show up on  the webpage only when the image is under '/res/', thus I changed my static_file_path to os.path.join(os.path.dirname(os.path.abspath(__file__)), 'res'), and my image path to gui.Image('/res/weld.jpg'). and now it works. 
Thanks for your help.

**Comment by dddomodossola** [comment]
You don't need to have your images under a *res* folder. After you specified the static_file_path,  you  have to refer to your images with */res/myimage.png* . But this don't necessary means the image is under a folder named res.

**Comment by Gdoong426** [comment]
Thank you, I've changed it and it works. You really help me alot.

**Comment by dddomodossola** [comment]
@Gdoong426 you are welcome ;-)
