### ISSUE TITLE
Got stuck on loading animation

### ISSUE THREAD

**Issue by tmxak** [dddomodossola/remi#208]
when I run any script in examples the web interface is getting stuck on loading(just loading and thats it) animation and nothing else. Animation is great, but the main purpose is the app behind. Thanks
![image](https://user-images.githubusercontent.com/17516391/34201303-ba7ef332-e57c-11e7-9ceb-03592020b191.png)

**Comment by dddomodossola** [comment]
@tmxak this happens when websocket fails to connect. I assume you are accessing your interface remotely, and maybe you foroot to NAT websocket port on the router. If not, please provide more info

**Comment by tmxak** [comment]
Yep you're right. My centos server is on cloud. Firewall configured to allow connections on 8081 and 8082 port. I'm starting the app with config:
start(MyApp, debug=True, address='0.0.0.0', port=8081, websocket_port=8082, update_interval=0.1, username='user', password='pass')
in netstat i see that websocket and app is runnning
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State          PID/Program name
tcp        0       0        0.0.0.0:8081                0.0.0.0:*                   LISTEN          7714/python
tcp        0       0        0.0.0.0:8082                0.0.0.0:*                   LISTEN          7714/python

Could you help what I'm doing wrong?

**Comment by dddomodossola** [comment]
If you are sure about the port accessibility there is another possibility. Maybe the communication is slow andown causing timeout on websocket.  Consider to setup the parameter  "websocket_timeout_timer_ms" with greater value until you get a stable connection.  Default is 1000.
Please let me know if you solve this way

**Comment by dddomodossola** [comment]
You have to pass that parameter to *start* function call

**Comment by tmxak** [comment]
Thanks, but not working. I've tried 2000 and 4000 but no result..

**Comment by dddomodossola** [comment]
Is your server based on platforms like C9 or something similar?

**Comment by tmxak** [comment]
I dont thin so. wrote to your mail

**Comment by tmxak** [comment]
I think i've found the problem ->
https://cloud.google.com/appengine/docs/standard/python/sockets/#limitations-and-restrictions
"Sockets are only available for paid apps"
I will try to deploy on my own server (not in cloud) and will write down the results

**Comment by dddomodossola** [comment]
Ok ;-) 
However I haven't received the e-mail you told me previously

**Comment by tmxak** [comment]
Confirm it. Tested on remote server which isnt in Google cloud. Thanks you
