### ISSUE TITLE
TableWidget fails when Trying to Start GUI Editor

### ISSUE THREAD

**Issue by ConnorSMaynes** [dddomodossola/remi#213]
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\remi\server.py", line 788, in do_GET
    self.client.root = self.main(*self.server.userdata)
  File "editor.py", line 435, in main
    self.widgetsCollection = editor_widgets.WidgetCollection(self, width='100%', height='50%')
  File "C:\Users\conno\OneDrive\Desktop\remi-master\editor\editor_widgets.py", line 462, in __init__
    self.add_widget_to_collection(gui.TableWidget, width='100px', height='100px')
AttributeError: 'module' object has no attribute 'TableWidget'

**Comment by dddomodossola** [comment]
It seems you have installed remi from pip and using the editor from the master branch, that is different commits ahead. Is this possible?

**Comment by ConnorSMaynes** [comment]
Okay, destroying every version I downloaded between pip and Github and then reinstalling worked.
