### ISSUE TITLE
All clients get the same instance

### ISSUE THREAD

**Issue by renerocksai** [dddomodossola/remi#214]
Hi, first of all: remi is **awesome**! I have written an "app" and deployed it to a testing server.

What I can't fix is:

* all clients (e.g. 2 laptops) with the same external IP (using the same WiFi router) get the same application instance / state of the user interface.
* When I connect in n different tabs, they all get the same instance, too

I noticed the following comment in `server.py`, in `_instance()`:

```python
        """
        This method is used to get the Application instance previously created
        managing on this, it is possible to switch to "single instance for
        multiple clients" or "multiple instance for multiple clients" execution way
        """
```

How can I switch to _multiple instance for multiple clients_?

**Comment by renerocksai** [comment]
BTW: I use `multiple_instance=True`.

Is it possible, that each browser connection gets its own application instance?

**Comment by renerocksai** [comment]
Thank you for digging into this. Multiple instances on different browser tabs would (just) be nice to have. It would behave more like a GUI desktop app one can start multiple instances of - which is not too uncommon. Think: session. I can have multiple identities on GitHub, for instance, each of them being logged in in a different browser tab.

As some sort of workaround (which I could live with if I had got it to work) I played around with passing an authentication dict `{username:password}` to the `Server` in `start()` and identifying "sessions" through authentication token. While identification works in `do_GET()`, I haven't found a way to map an app instance / ws_server to the identified user. 

But one instance per distinct laptop would definitely help a lot, so more than just one of my colleagues would be able to use this app (and future apps) at the same time.

**Comment by nzjrs** [comment]
@renerocksai Allow me to chip in. I've been using Remi for couple of years and contributed to it quite a bit before that. I've been shipping it in commercial products for at least a year too. Multiple instance support was in principle working in the past but I would never recommend using it. It doesn't quite gel with the architecture IMO. Remi is absolutely fantastic for presenting a share single interface of a system, and I can recommend it without reservation in this case, but if you are just using it as a tool to avoid writing HTML+JS for a normal web-app with concurrent different session access patterns, then I don't think it's the correct fit.

**Comment by renerocksai** [comment]
@nzjrs Thank you for clarification. I would still _like_ to do it. For in-house apps, making stuff available to my colleagues. I didn't have a full-blown web portal in mind. Also, I don't like the idea of having to re-write my python code to make functionality available via the browser. My current use cases are  PyQt apps where it was pretty easy to replace the GUI with remi. The PyQt apps I usually cx_freeze / pyinstaller into an executable which ends up 250-500MB large because of all the dependencies. It is so much easier to just send a link via e-mail once, than getting people to download huge executables for every update. It looked like remi could be a cool remedy for that situation.

**Comment by dddomodossola** [comment]
Hello @nzjrs , I still thank you so much for your contribution that was determinant for the project success, you are a very skilled developer. In the actual remi version, multiple_instance execution is ok, it just works with a well defined logic, that sometimes doesn't fit user requirements.
However, in the particular case of @renerocksai I will implement an example where the instance is related to an http session cookie value, instead of using client's ip.

**Comment by renerocksai** [comment]
@dddomodossola Yeah! Such an example would be super-awesome 👍 😄

**Comment by dddomodossola** [comment]
@renerocksai Excuse me for the late reply. I've created another branch called **session_identified_instance** with an initial implementation of session identified app instance. Tomorrow i will continue testing and other refinements. You can already test it if you want, but could contain bugs. Your apps doesn't need changes to adapt.

**Comment by renerocksai** [comment]
@dddomodossola Thanks for your efforts --- and no worries, you are not late! This is an open source project 😄 . While it might have been a bit early, I just quickly (really quickly) ran the `session_identified_instance` branch and from the same laptop - and tend to always get `session=0`. Tested with 2 browsers (chrome first, then also edge, both on Win). Haven't done more tests, though.

**Comment by dddomodossola** [comment]
@renerocksai I made few tests yesterday but seems to work correctly. Is the flag *multiple_instance* True in your test? Are Cookies enabled in browser? Which browser you tested? I need these info for further debug. Thank you for your patience. ;-)
However consider to see also at the example https://github.com/dddomodossola/remi/blob/master/examples/session_app.py that shows a different approch, using a user login session, it's a possible alternative.

**Comment by renerocksai** [comment]
@dddomodossola thanks for getting back to me. I had indeed forgotten the `multiple_instance=True` in my previous quick-test. I am currently on a Windows 10 machine. I use chrome for testing. Previously I used edge, too. Here is the output from 3 connections: 

* First connection from Chrome
* Second connection from Chrome in a separate tab
* Third connection from Chrome in a new window

* `multiple_instance=True`
* cookies are enabled in Chrome

current start call is `start(MyApp, title="xxx", standalone=False, port=8082, multiple_instance=True)`.

Thanks for pointing me to the `session_app.py` which I will definitely check out. By the sound of it, this would be the perfect alternative!

**Comment by renerocksai** [comment]
forgot to send the output. here you can see, the session is always the same?!?

```
remi.server      INFO     Started websocket server 127.0.0.1:50137
remi.server      INFO     Started httpserver http://127.0.0.1:8082/
remi.request     INFO     built UI (path=/)
>>>>>>>self.headers['cookie'] session=0
session id 0 not in clients dict_keys([])
_________setting up session 1522134743209
remi.server.ws   INFO     connection established: ('127.0.0.1', 50143)
remi.server.ws   INFO     handshake complete
>>>>>>>self.headers['cookie'] session=1522134743209
>>>>>>>self.headers['cookie'] session=1522134743209
>>>>>>>self.headers['cookie'] session=1522134743209
>>>>>>>self.headers['cookie'] session=1522134743209
>>>>>>>self.headers['cookie'] session=1522134743209
>>>>>>>self.headers['cookie'] session=1522134743209
>>>>>>>self.headers['cookie'] session=1522134743209
remi.server.ws   INFO     connection established: ('127.0.0.1', 50165)
remi.server.ws   INFO     handshake complete
>>>>>>>self.headers['cookie'] session=1522134743209
>>>>>>>self.headers['cookie'] session=1522134743209
>>>>>>>self.headers['cookie'] session=1522134743209
>>>>>>>self.headers['cookie'] session=1522134743209
>>>>>>>self.headers['cookie'] session=1522134743209
>>>>>>>self.headers['cookie'] session=1522134743209
remi.server.ws   INFO     connection established: ('127.0.0.1', 50243)
remi.server.ws   INFO     handshake complete
>>>>>>>self.headers['cookie'] session=1522134743209
>>>>>>>self.headers['cookie'] session=1522134743209
>>>>>>>self.headers['cookie'] session=1522134743209
>>>>>>>self.headers['cookie'] session=1522134743209
>>>>>>>self.headers['cookie'] session=1522134743209
```

**Comment by dddomodossola** [comment]
@renerocksai The results you get are correct. I missed to explain that this version doesn't provide different instances in the same browser. The browser shares session value to all windows/tabs. This version provides different instances between different browsers and clients. This way all the clients (users) in your company will get different instances. You can do testing with two separate browsers.

**Comment by renerocksai** [comment]
@dddomodossola WOW!!!!!!!!!!!!!!!!!!!!!!!!!! It works 😄 👍 😄 !!!! Thanks a lot! This is awesome! I will still have a look at the session app, as this is also very interesting. But the problem is solved!
