### ISSUE TITLE
Upgrade websocket connection instead of using a separate socket on a different port

### ISSUE THREAD

**Issue by pbsds** [dddomodossola/remi#216]
I want to host a remi application behind a reverse proxy which handles ssl encryption for me. remi uses a separate port for its websocket connections, instead of using the upgrade mechanic in http.
To make this work, I have to forward two tunnels to my remi application: one for https:// to http:// and one from wss:// to ws://. But I'm having two issues when trying to do this:

* remi has no option to tell the web client to start a websocket on port A, while the server is listening on port B instead. The reverse proxy and remi can't be listening to the same port when on the same host.

* When remi is accessed with https through a reverse proxy, it still tells the client to connect using ws instead of wss. Any browser worth their salt will block any attempts from webpages loaded using https to make unsecure websocket connections over ws.

To make this possible i need two features:
* An option to make remi tell the client to use wss instead of ws. Alternatively, you could use javascript to detect whether http or https is being used and act accordingly.

An one of these fixes:
* Make an option to tell the client to start a websocket using port A instead of port B, which the server is actually listening on.
* Support upgrading http to websocket on the main port (meaning port and websocket_port can be the same)

Websockets were designed to start as a http request, before being upgraded to a fully fledged socket connection. Websockets were designed this way to be secure and be easy to handle by reverse proxies and load balancing solutions. Supporting the last fix would be the best solution in my opinion.

Thank you for your time

**Comment by dddomodossola** [comment]
Hello @pbsds . I tried to implement the protocol upgrade in the same class but without success. However about wss https look at this branch **wss_clean_implementation**.

**Comment by dddomodossola** [comment]
@pbsds Done! You can try the version on the master branch. ;-)

**Comment by pbsds** [comment]
Great! I'm reading through `server.py` now, and i'm liking the cleanup you've done aswell!
