### ISSUE TITLE
Standalone Option not Working on Win10 x64 Python 3.6

### ISSUE THREAD

**Issue by Semnodime** [dddomodossola/remi#217]
Hi!
I am testing the standalone option under windows 10 x64 with Python3.6 and the app seems to open in a non-browser window and I provided the classic Hello World example from your code (couldn't find simple_app). Though the windows seems to "disconnect" short after it has been launched.

Is standalone still exerimental or can you guide me how to make this work?
Thanks!
![screenshot_7](https://user-images.githubusercontent.com/19511852/38762181-c3ef7b46-3f89-11e8-9a57-ed5d78bc6b60.png)

**Comment by dddomodossola** [comment]
Hello @Semnodime the standalone execution is not experimental. It works. The problem you are experiencing depends from the libraries used by  pywebview. It can use Qt components for example, to create the window. On your system these libraries have to be updated. Look at the great pywebview project for more info ;-)

**Comment by Semnodime** [comment]
Thanks for the hint.

- Pywebview currently does not use QT under Windows though. I think it uses pythonnet.
But as this didn't work out and I am a fan of QT I patched pywebview in order to launch with QT even under windows. (Look into[ pywebview __init__](https://github.com/r0x0r/pywebview/blob/master/webview/__init__.py) to understand how to patch)

- But another problem turned out to be a bug inside the QT version check of pywebview for which I [created a patch](https://github.com/r0x0r/pywebview/issues/214) and issued a pull request.

Now REMi works as standalone under windows with QT, yay!
![image](https://user-images.githubusercontent.com/19511852/38770628-1430cbaa-4016-11e8-871c-3b9df4b06de6.png)

**Comment by Semnodime** [comment]
You can close the issue either now or if pywebview releases the new patched version.

**Comment by tetirenpy** [comment]
![image](https://user-images.githubusercontent.com/33869513/45872605-0251fc80-bdc3-11e8-9ec9-81d79a3382d9.png)
I was also troubled by this problem. I modified the source code（pywebview init ） like this, it works.

**Comment by dddomodossola** [comment]
Thank you for sharing @tetirenpy
