### ISSUE TITLE
standalone mode - full screen

### ISSUE THREAD

**Issue by shmrymbd** [dddomodossola/remi#223]
anyone can help to point how to set to full screen mode in standalone mode?

if __name__ == "__main__":
    # starts the webserver
    # optional parameters
    start(MyApp, debug=True,standalone=True)

**Comment by dddomodossola** [comment]
Try using parameter "fullscreen=True". I suggest you to add a close button to your interface, because the pywebview's fullscreen mode hides close button.

**Comment by shmrymbd** [comment]
thank you. its work!!
