### ISSUE TITLE
running local video

### ISSUE THREAD

**Issue by shmrymbd** [dddomodossola/remi#224]
hi.. i try the video iframe work using example on browser but error = video cant run on standalone( pywebview )
1. failed to run local video using example. Also try self.video = gui.VideoPlayer (None,True,True) but the video cant play. i am using .mp4
2.what type of video supported. thank you.

**Comment by shmrymbd** [comment]
anyone can help me does above possible?

**Comment by dddomodossola** [comment]
@shmrymbd please excuse me for the late reply. Tomorrow I will show you an example. The supported format are the same of the html5 **video** tag https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats

The problem you are getting running local videos: have you defined a resource folder? Look at the template_app.py
