### ISSUE TITLE
Request: OnSelect listeners for TreeView

### ISSUE THREAD

**Issue by saddy001** [dddomodossola/remi#227]
Without the TreeView items being connectable with onselect actions, the TreeView is quite useless.
So it would be very nice to have an on_selection_listener for the TreeView just like ListView has.

**Comment by dddomodossola** [comment]
Hello @saddy001 , thank you for the suggestion. However remember that you can set the onclick listener for each TreeItem.

**Comment by saddy001** [comment]
Unfortunately this doesn't work, because onclick is already overriden on TreeItem to provide the tree expand function. So set_on_click_listener is non-functional.

**Comment by saddy001** [comment]
Sorry, my mistake. The above is only true for TreeView, not TreeItem. Thanks.
