### ISSUE TITLE
Error socket launch in Windows 8

### ISSUE THREAD

**Issue by samtux** [dddomodossola/remi#231]
In Windows 8, launching the app causes the following error with **widgets_overview_app.py**:

>  PS C:\tmp\remi-master> python .\examples\widgets_overview_app.py
remi.server      INFO     Started httpserver http://127.0.0.1:8081/
127.0.0.1 - - [11/Jul/2018 15:12:19] "GET / HTTP/1.1" 200 -
remi.request     INFO     built UI (path=/)
remi.request     DEBUG    get: /
127.0.0.1 - - [11/Jul/2018 15:12:19] "GET / HTTP/1.1" 200 -
cookie_to_cook: session=1531339939118
cookie_to_cook: session=1531339939118
found session id: session=1531339939118
found session id: session=1531339939118
remi.request     DEBUG    get: /res/style.css?7e7421c8fede27d23793172efe65d3d9
remi.request     DEBUG    get: /res/logo.png
127.0.0.1 - - [11/Jul/2018 15:12:19] "GET /res/style.css?7e7421c8fede27d23793172efe65d3d9 HTTP/1.1" 200 -
127.0.0.1 - - [11/Jul/2018 15:12:19] "GET /res/logo.png HTTP/1.1" 200 -
remi.request     ERROR    error processing GET request
Traceback (most recent call last):
  File "C:\Python 3.5\lib\site-packages\remi-1.2-py3.5.egg\remi\server.py", line 813, in do_GET
    self._process_all(path)
  File "C:\Python 3.5\lib\site-packages\remi-1.2-py3.5.egg\remi\server.py", line 870, in _process_all
    self.wfile.write(content)
  File "C:\Python 3.5\lib\socket.py", line 589, in write
    return self._sock.send(b)
ConnectionAbortedError: [Socket Error 10053 - An established connection was aborted by the software in your host machine.
cookie_to_cook: session=1531339939118
found session id: session=1531339939118
remi.request     DEBUG    get: /res/plus.png
127.0.0.1 - - [11/Jul/2018 15:12:19] "GET /res/plus.png HTTP/1.1" 200 -
remi.server.ws   INFO     connection established: ('127.0.0.1', 36781)

For standalone app  crashes  with looping error **"Socket Error 10053 - An established connection was aborted by the software in your host machine."**.

**Comment by dddomodossola** [comment]
@samtux does this problem happens only in standalone mode?

**Comment by dddomodossola** [comment]
I see you started running widgets_overview_app.py. I can suppose that a firewall is blocking the connection. Is firewall enabled? Is python in firewall exceptions?

**Comment by samtux** [comment]
@dddomodossola With some of the examples that are not estandalone (widgets_overview_app.py), however the app works correctly in the browser. But for all standalone apps, it crashes showing the loader and the error loop  **"Socket Error 10053 - An established connection was aborted by the software in your host machine."**.

![](https://i.imgur.com/cHJRDAO.png)

**Comment by samtux** [comment]
@dddomodossola  I've tried to disable the firewall before, but it still has the same errors. I don't know if this case is related with https://github.com/dddomodossola/remi/issues/217.

**Comment by samtux** [comment]
@dddomodossola I don't know if you know the following project to launch a standalone application https://github.com/flexxui/webruntime. I think that pywebview, gives some errors, and testing this webruntime module I have managed to launch the app correctly. The commands are very simple, you can choose for example different Browser Runtimes:

```python
> from webruntime import FirefoxRuntime
> f = FirefoxRuntimeRuntime("C://tmp/icono.ico", title="Geocodificador de IDECA", size=(800,600), windowmode="normal")
> f.launch_app("http://127.0.0.1:8081")
> f.close()
```

**Comment by dddomodossola** [comment]
@samtux thank you for the tip. However I think you can do the same directly opening a firefox subprocess with some parameters, this way you can avoid additional dependencies.

**Comment by samtux** [comment]
Personally, I like the idea of the desktop application "look and feel" without the user thinking it is a web application.  Additionally the possibility of packaging.

I really congratulate @dddomodossola on your project and see a great development alternative with the philosophy of a small library.

**Comment by dddomodossola** [comment]
Thank you a lot @samtux.

Look at this for launching a firefix subprocess without the browser window https://developer.mozilla.org/en-US/Firefox/Headless_mode

;-)

**Comment by samtux** [comment]
Fixed in https://github.com/dddomodossola/remi/issues/217
