### ISSUE TITLE
Detect ssl in JavaScript

### ISSUE THREAD

**Issue by amasad** [dddomodossola/remi#237]
If you do SSL termination at the proxy level (e.g. cloudflare) then the server doesn't have to be running https but the website will be served as https but remi will try to connect via `ws` instead of `wss`.

Detecting from the client side should be easy. If this of interest then I can send a PR.

**Comment by dddomodossola** [comment]
Done, let me know if this works for you. ;-)

**Comment by amasad** [comment]
Works! https://repl.it/@amasad/remi-repl-demo-1

**Comment by dddomodossola** [comment]
Awesome! Thank you for sharing
