### ISSUE TITLE
ListView text within <> not displayed

### ISSUE THREAD

**Issue by AndriesSHP** [dddomodossola/remi#245]
I have defined a gui.ListView and when I append a message with a value in pointy brackets, then the text is not displayed.
The example below gives as output:
Message =xxx=
Message
instead of <xxx>

`import remi.gui as gui
from remi import start, App

class MyApp(App):
    def __init__(self, *args):
        super(MyApp, self).__init__(*args)

    def main(self):

        #tb = gui.TabBox(width='80%')
        list_view = gui.ListView(width='100%', height='100%')
        string = 'xxx'
        message = 'Message ={}='.format(string) 
        list_view.append(message)
        message = 'Message <{}>'.format(string)
        list_view.append(message)

        return list_view

if __name__ == "__main__":
    start(MyApp, title="ListView-test", standalone=False)`

**Comment by dddomodossola** [comment]
Hello Andries, 
There is already a fix for this, you have to use the version on master branch. I will make a release on pypi soon. Try the version on master branch and let me know if solves your problem.
I made this update just yesterday.

**Comment by AndriesSHP** [comment]
Hello Davide,
Indeed that solved the problem.
Thanks
