### ISSUE TITLE
support mutiple instances

### ISSUE THREAD

**Issue by nzjrs** [dddomodossola/remi#25]
I can only run one gui based app at a time because the port number is hardcoded.

**Comment by dddomodossola** [comment]
Yes, in case of different applications you can change the port by the configuration.py file. But maybe we can enable the library on finding automatically the best port number.

**Comment by nzjrs** [comment]
yes I know I can change it, but what if I want to launch the same app with the same source code twice?

you can do something like this to get a random free port

server = TCPServer(('127.0.0.1', 0), Handler)
host, port = server.socket.getsockname()[:2]
print "we are on port", port

**Comment by dddomodossola** [comment]
Fine, I will do this soon. ;-)

**Comment by KenT2** [comment]
If you are going to do this please make it optional. I intend to autostart the server when the Pi is powered up and a terminal window will not be open to see the port number that is printed.

The solution could be that if the port is left blank in configuration.py then a port is automatically selected. Presumably something will need to be done for the websocket port as well.

**Comment by nzjrs** [comment]
the websocket port is an implementation detail. it should always be an ephemeral port

**Comment by cyberpro4** [comment]
A great solution could be listen on default port (from code / configuration file) and, when already used, switch to random port

**Comment by nzjrs** [comment]
I'm working on this, and cleaning up the whole configuration system, in https://github.com/nzjrs/gui/tree/multiple-instance

**Comment by dddomodossola** [comment]
Ok John, but take care about the parameter MULTIPLE_INSTANCE in configuration.py file. This parameter changes the behavior of the server in case of multiple clients to the same App. If True, multiple instances of App class are created. If False instead, all the clients shares the same App class instance.

**Comment by nzjrs** [comment]
Thanks, it was a bit confusing!

What would be a reason to run MULTIPLE_INSTANCE=True? I can't think of a use at the moment

**Comment by dddomodossola** [comment]
Image a collaborative App, multiple user can interact on the same interface.. I do not have a specific use case now.

**Comment by cyberpro4** [comment]
A simple address book application, with a name/surname filter: when someone change the filter, this one shouldn't be shared with other clients.

**Comment by nzjrs** [comment]
> A simple address book application, with a name/surname filter: when someone change the filter, this 
> one shouldn't be shared with other clients.

how is the author of such an app expected to know which client they are talking to, and should they care? is it expected that you poke around in self.client_address from main? are all apps otherwise destined to be stateless?
