### ISSUE TITLE
Some Problems with the Editor

### ISSUE THREAD

**Issue by bashkan** [dddomodossola/remi#252]
Hi,
I have some problems with the editor and couldn't solve them by myself. I am using Remi 1.2.2 installed manually (not using pip). 
1) Editor refuses to open files which are located outside the editor folder.
2) I have copied some examples into the editor folder. But when I try to open them with the editor (i.e. root_widget_change_app.py), It does nothing. The error I get from the command line is: object has no attribute configuration.
I know that the remi should be consistent regarding its version and the examples in it. But as I said I have manually downloaded version 1.2.2 so I am assuming it should be consistent. 
Thank you in advance.

**Comment by dddomodossola** [comment]
Hello @bashkan , the editor application is able to open only scripts made with the editor itself. This means that you can't open the examples that are not made by the editor.

**Comment by bashkan** [comment]
Hi,
Thank you for the clarification. Now it makes sense :)
Keep up the good work & Regards,
