### ISSUE TITLE
Example to add multiple resource folders?

### ISSUE THREAD

**Issue by bashkan** [dddomodossola/remi#255]
Hello again,
I realized that REMI does not want to look at folders (i.e. for an image file) other than /res/. I understand that the following lines of code add /res/ folder as a resource location to a script:
res_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'res')
super(MyApp, self).__init__(*args, static_file_path=res_path)

But what if I have more than one folder to use as resources? For example; I have /images/ , /gcodes/, /helper_files/ folders that I need to include. Can you please kindly tell how to achieve this?
Thank you in advance.

**Comment by Navarro11** [comment]
On main page changelog says:

`super(MyApp, self).__init__(*args, static_file_path = {'my_resources':'./files/resources/', 'my_other_res':'./other/'})`
 and then
`my_widget.attributes['background-image'] = "url('/my_resources:image.png')"`

This works for me.

**Comment by bashkan** [comment]
Thank you for your reply.
Is your solution based on relative or absolute paths? I mean does ./files/resources/ correspond to C:\files\resources or relative to where the script is?

**Comment by Navarro11** [comment]
It's relative to script destination if you use "./".

**Comment by dddomodossola** [comment]
@bashkan The info provided you by @Navarro11 are correct. Have you got it working?

@Navarro11 Thank you for helping ;-)
