### ISSUE TITLE
Printing to command prompt/terminal?

### ISSUE THREAD

**Issue by bashkan** [dddomodossola/remi#256]
Is it possible to print things on the command prompt while the script is running? I use it a lot to debug things. However when I run a remi script, the command prompt seems to be hijacked (sorry for the poor choice of word) by the script and I can not print anything.
I do apologize if this is a stupid question, I am a newbie, trying to learn and progress.

**Comment by Navarro11** [comment]
Hello,
that's weird, I use print function successfully (on raspbian).

**Comment by bashkan** [comment]
Hello,
My experience is that the command prompt prints a few lines, and then it stays still until the script is terminated:
![command prompt](https://user-images.githubusercontent.com/27769228/49498184-3fcf0d80-f87b-11e8-952e-e9bdd061ed19.png)

**Comment by nzjrs** [comment]
This is incorrect and nothing to do with remi.

**Comment by bashkan** [comment]
Can you please tell what is incorrect? Any help is welcome because I am stuck.

**Comment by dddomodossola** [comment]
@bashkan For questions about remi applications, but not directly related to the development of the library itself, it's better to ask on this dedicated forum  reddit https://www.reddit.com/r/remigui . If you still have problems using **print** command, please show your code there. Regards.

**Comment by bashkan** [comment]
@dddomodossola Thank you for your reply. I am sorry for taking your time. I will check the reddit forum.
Best Regards.

**Comment by dddomodossola** [comment]
@bashkan you are welcome ;-)  see you on reddit forum
