### ISSUE TITLE
rename framework

### ISSUE THREAD

**Issue by nzjrs** [dddomodossola/remi#26]
'gui' is too broad of a name to be used for a framework. it is a general term that is already known and used.

can you select another one?

it would also better allow you to clean up the project structure as per #21

**Comment by cyberpro4** [comment]
Any suggestions for the name?

**Comment by nzjrs** [comment]
browsertk, browtk (like Tk or gtk, tk=toolkit)

    import browtk as btk
    w = btk.Window()

looks ok. 

I like three letter abbreviations for frameworks, seaborn=sns, matplotlib=plt, etc

**Comment by cyberpro4** [comment]
Thank you for the feedback. I've already discussed about the name with dddomodossola: I'll try again to change his mind about!

**Comment by KenT2** [comment]
So we're ganging up on poor Davide now ;-)
I agree gui is too broad. The important features of this project for me is that it is a Web Based Gui for Python so WGP  or WBGP would be a good abbreviation.

**Comment by nzjrs** [comment]
It will also be more productive to fork and contribute once all files are all moved to a correct module namespace.

**Comment by dddomodossola** [comment]
Are you sure you would like to add another strange name to the tons of already existing (https://wiki.python.org/moin/GuiProgramming) ? GUI seems to me the better solution... Why you do not feel comfortable with it? :-D
@Jhon, you like three letters names, GUI is naturally composed by three

**Comment by nzjrs** [comment]
I don't feel comfortable with it because it is incorrect and a touch rude (it implicitly assumes that it is the only gui framework). It is also impossible to google - what if the project gets popular?

**Comment by KenT2** [comment]
How about
PyWebGui - already used, one instance looks a bit dodgy
PyWebUI
WebGuiPy - A sticky sweet for spiders (sorry for bad English Pun)

All 3 tell you a little bit about what it is, and they are googlable

**Comment by nzjrs** [comment]
I don't like having 'Py' in the name. All the best python libraries don't have python in the name

numpy, scipy, matplotlib, seaborn, requests, sqlalchemy, pillow, scrapy, etc.

there are exceptions, pygame for example, but I prefer without py.

**Comment by dddomodossola** [comment]
So, the name have to be changed, this is sure. But it's difficult to find a good name... Most of important frameworks have names not related to their use. 'Qt', 'Kivy', 'gtk'...

What about:
* RemI: REMote Interface
* YoUI: Your UI

Should be simple to remember and simple to speech.

**Comment by nzjrs** [comment]
Remi sounds good!

**Comment by dddomodossola** [comment]
I think so, KenT2 and cyberpro4?

**Comment by cyberpro4** [comment]
It wouldn't be better RemUI? (remote user interface)

**Comment by nzjrs** [comment]
OK, maybe RemUI is a bit better, although that kinda means it will be forever written as RemUI. Personally I think weird capitalisation is depressingly common in free software projects, at least Remi would be capitalised normally.

Anyway, both are good and better than YoUI.

**Comment by dddomodossola** [comment]
Remi is simpler to remember and simpler to speech.
Il 25/ott/2015 04:46 PM, "John Stowers" <notifications@github.com> ha
scritto:

**Comment by KenT2** [comment]
I prefer Remi over RemUI for the same reasons as Davide. Both are better than YoUI 

Remi has no important clashes on Google.

**Comment by dddomodossola** [comment]
RENAMED :-D
It requires some reworking in source code scripts.
