### ISSUE TITLE
Color picker not available on mobile browser

### ISSUE THREAD

**Issue by bashkan** [dddomodossola/remi#260]
Hi,
I was testing the widgets_overview_app.py example on different platforms and saw that the color picker tool is not visible to Safari on iPhone. It works perfectly on Chrome and MS Edge, although with different looks. Is this a known thing? The color picker is the center element for my project (I am building a kinetic art project where I will be changing the color of an led strip from web interface using a cell phone) so does anyone know how to solve this?
Thanks & Best Regards,
![iphone_screenshot](https://user-images.githubusercontent.com/27769228/50209526-0fac6200-0385-11e9-97ba-a060f2ec0083.PNG)

**Comment by dddomodossola** [comment]
hello @bashkan it should be simple to implement a custom widget, with 3 Slider or SpinBox for red geen blue values to setup a color value, maybe you can add also a simple rectangle that changes the background color with the choosen rgb value. do you know how to do this?

**Comment by dddomodossola** [comment]
eventually you can change the page view as desktop. is it possible on iPhone? Android has this option

**Comment by bashkan** [comment]
Hello @dddomodossola ,
Your idea with 3 sliders is great! I will definitely work on that. But I don't know how to do the rectangle that changes background color. Can you please tell how to do that? Or at least how I should research it?
Regarding viewing the page as desktop, I don't think that is possible on iPhone.
Thanks for your reply and great idea :)

**Comment by dddomodossola** [comment]
you can use the standard Widget and size it as you want. the backgroud can be set as

    mywidget.style ['background-color']= 'rgb(%s, %s, %s)'%(sliderRed.get_value(), sliderGreen.get_value(), sliderBlue.get_value())

**Comment by bashkan** [comment]
@dddomodossola, you rock bro :)
I will make the custom widget right now.
Thanks again...

**Comment by dddomodossola** [comment]
@bashkan you are welcome ;-)

**Comment by bashkan** [comment]
@dddomodossola,
I am sorry to bother you with this subject again. But I couldn't make it work no matter what I did. I have created a vBox with some buttons and sliders to change the color of another vBox which is on it. However to color of the vBox is grey and does not change when I move the sliders. Do I need to create onChange events for the sliders?
Here is the code for the vBox that I want to change the color: (I didn't include the whole code so it is easier to see it)
`color_box = gui.VBox(style={'width':'300px', 'height':'100px', 'margin':'0px'})
 color_box.style['background-color'] = 'rgb(%s, %s, %s)'%(self.red_slider.get_value(), self.green_slider.get_value(), self.blue_slider.get_value())`

And here is the screenshot:
![screenshot2](https://user-images.githubusercontent.com/27769228/50280992-2de69080-045f-11e9-98c0-c0bdaed7bcc2.PNG)

**Comment by dddomodossola** [comment]
hello @bashkan , yes you should execute that code when onchange event happens on sliders

**Comment by bashkan** [comment]
Worked exactly as you said :)
Many thanks...

**Comment by dddomodossola** [comment]
wonderful :D have a good code development
