### ISSUE TITLE
Is vertical slider a possibility?

### ISSUE THREAD

**Issue by bashkan** [dddomodossola/remi#261]
Hi,
As the title explains it, I am wondering if it is possible to make the sliders vertical? (move the slider up/down to change the values rather than left/right).
I know this is a minor thing and it is OK if it's not possible. It's just that when using horizontal sliders on mobile devices, 80% of the time, the page wants to browse back/forth when you move your finger left or right. I am sorry if I am being too picky, just asking :)
Best Regards.

**Comment by dddomodossola** [comment]
Hello @bashkan ,

You can use the **transform** css attribute:
    myslider.style['transform']='rotate(90deg)'

However this could cause layouting issues, it could be difficult to correctly size containers

**Comment by bashkan** [comment]
Hi @dddomodossola,
You are right. It is not worth the trouble. But thanks anyway.
Best Regards.

**Comment by dddomodossola** [comment]
;-)
