### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by Brianzhengca** [dddomodossola/remi#262]
Sorry for this stupid question but how are you supposed to install this editor?

**Comment by dddomodossola** [comment]
Hello, you should download the repo (you can use this link https://github.com/dddomodossola/remi/archive/master.zip ).
Then unzip the folder, and run directly the editor/editor_app.py.
It doesn't require an installation process.

**Comment by Brianzhengca** [comment]
thank you so much !!!!

**Comment by Brianzhengca** [comment]
I am going to close this thread now
