### ISSUE TITLE
remi label set_text() newlines

### ISSUE THREAD

**Issue by Brianzhengca** [dddomodossola/remi#263]
Hello I am trying to display a multi-line file with the Remi label object and the set_text() method. However, the set_text() method does not seem to respond to /n and the label shows a giant blob of text. Thank you for your help

**Comment by awesomebytes** [comment]
Maybe you need to use <br>

**Comment by Brianzhengca** [comment]
@dddomodossola I currently don't have access to my code now. I will post it when I have access(probably tonight)

**Comment by Brianzhengca** [comment]
also, by giant blob of text I mean the multi-line file in one single blob :)

**Comment by Brianzhengca** [comment]
class untitled:
    @staticmethod
    def construct_ui():
        #some code generated by remi editor
        label = Label('')
        #some other code generated by remi editor
        mainContainer.children['button'].set_on_click_listener(self, 'onclick_button')
        #some more code generated by remi editor
    def onclick_button(self, emitter):
        lines = open('chat1.txt', 'r').readlines()
        mainContainer.children['label'].set_text(' '.join(lines))
        #some more code

**Comment by Brianzhengca** [comment]
chat1.txt is something like:
test0: hello
test1: blahblahblah
test0: just testing
test1: random random random
.......

**Comment by Brianzhengca** [comment]
@dddomodossola I do not prefer the textInput widget since it can be edited. is there any other ways to do this?

**Comment by Brianzhengca** [comment]
@dddomodossola I am using \n not /n sorry about that

**Comment by Brianzhengca** [comment]
thank you I will give it a try tonight ;)

**Comment by dddomodossola** [comment]
@Brianzhengca you have to set the style property **white-space** to **pre** for your label:

mylabel.style["white-space"] = "pre"

this will work ;-)

**Comment by Brianzhengca** [comment]
than you so much !

**Comment by Brianzhengca** [comment]
:)

**Comment by Brianzhengca** [comment]
I will close this thread now
