### ISSUE TITLE
load html

### ISSUE THREAD

**Issue by Brianzhengca** [dddomodossola/remi#267]
is there a way to load html/javascript into the gui?

**Comment by dddomodossola** [comment]
Hello @Brianzhengca yes that's possible. What you want to do?

**Comment by Brianzhengca** [comment]
I want to load a few elements like <center> to position the elements since it is a pain to define the exact location through css

**Comment by dddomodossola** [comment]
@Brianzhengca have you tried with Remi graphical editor? It makes it simple to position elements manually

However you can append html to a widget by doing:
    mywidget.add_child("myexamplehtml", "<p>example</p>")

For these kind of questions it is better to post on the remi forum https://www.reddit.com/r/RemiGUI . I will help you on the forum too ;-)
GitHub issues should be focused on internal library problems.
