### ISSUE TITLE
loading animation

### ISSUE THREAD

**Issue by Brianzhengca** [dddomodossola/remi#268]
Is it possible to create something like [this](https://www.google.com/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwjIpuGUsvHfAhUK0lQKHacbDWEQjRx6BAgBEAU&url=%2Furl%3Fsa%3Di%26source%3Dimages%26cd%3D%26ved%3D%26url%3Dhttps%253A%252F%252Fwww.videoblocks.com%252Fvideo%252Fblue-circle-loading-animation-rhai_q5imxlp1uu%26psig%3DAOvVaw3kX-mIU4hbQeXfOpu9ThGo%26ust%3D1547696835070154&psig=AOvVaw3kX-mIU4hbQeXfOpu9ThGo&ust=1547696835070154)???

**Comment by dddomodossola** [comment]
In remi you can do almost everything that can be done with html css javascript. Altough it could require a bit of work.

**Comment by Brianzhengca** [comment]
thank you
