### ISSUE TITLE
insert widgets

### ISSUE THREAD

**Issue by Brianzhengca** [dddomodossola/remi#270]
is it possible to insert widgets between widgets that are in the same container?
here is my code
`
    # listener function
    def on_button_pressed(self, widget):
        self.lbl.set_text('Button pressed!')
        self.bt.set_text('Hi!')
        for i in range(5):
            print(self.container)
            self.lbl = gui.Label("oof")
            #insert self.lbl in between two widgets
            self.container.append(self.lbl)

if __name__ == "__main__":
    start(
        MyApp, debug=False, address='0.0.0.0', port=0, multiple_instance=True)
`

**Comment by Brianzhengca** [comment]
sorry for the indentation I am new to github

**Comment by dddomodossola** [comment]
Actually that's not implemented, but it should be simple to remove and insert again ordered widgets.
However, VBox and HBox containers allows to define the order of the contained widgets. For each child you can set the style 'order'. 

    child1.style['order'] = '1'
    child2style['order'] = '10'
    child3.style['order'] = '2'

child3 will be placed between child1 and child2.

**Comment by Brianzhengca** [comment]
@Brianzhengca thank you !!!!
