### ISSUE TITLE
Label gets truncated

### ISSUE THREAD

**Issue by Brianzhengca** [dddomodossola/remi#271]
Hello I have a issue with my app. The issue is that some of the Labels get truncated when there is too many labels in a container even though i set overflow to auto
[here](https://pastebin.com/eUupH0CB) is my code

**Comment by Brianzhengca** [comment]
![image](https://user-images.githubusercontent.com/30914529/51364450-09e39280-1a91-11e9-85a0-6da1c883fdb3.png)
The top part got truncated

**Comment by dddomodossola** [comment]
Hello @Brianzhengca ,

You should size elements correctly. **self.message_container** has height 100%, but it is not the sole widget in the **self.container**.

**Comment by Brianzhengca** [comment]
Sorry but the problem did not get solved, I set the height for self.message_container to 60 percent and still problem still persists. Thank you so much for your help!

**Comment by dddomodossola** [comment]
Here is a working code @Brianzhengca 

    import remi.gui as gui
    from remi import start, App
    import random


    class MyApp(App):
        """Tic Tac Toe game build using remi"""
        def __init__(self, *args):
            super(MyApp, self).__init__(*args)
        def main(self):
            self.container = gui.VBox(style={'overflow':'auto','width':'80%','height':'100%', 'position':'absolute','top': '0', 'left': '0', 'bottom': '0', 'right': '0',
            'align-items': 'center', 'margin':'auto', 'float': 'right','justify-content': 'flex-start'})
            self.message_container = gui.VBox(style={'overflow':'auto','margin-top':'auto','width':'80%','height':'100%', 'position':'relative'})
            self.message_container.style['justify-content'] = 'flex-start'
            self.bt = gui.Button('Press me!')

            # setting the listener for the onclick event of the button
            self.bt.onclick.connect(self.on_button_pressed)

            # appending a widget to another, the first argument is a string key
            self.container.append(self.message_container)
            self.container.append(self.bt)

            # returning the root widget
            return self.container

        # listener function
        def on_button_pressed(self, widget):
            for i in range(1):
                print(self.container)
                self.lbl = gui.Label(str(random.randint(0,9)))
                self.message_container.append(self.lbl)

    if __name__ == "__main__":
        start(
            MyApp, debug=False, address='0.0.0.0', port=0, multiple_instance=True)


It was required to setup *self.message_container.style['justify-content'] = 'flex-start'*
Otherwise you can also use a Widget container instead of VBox in that situation.

**Comment by Brianzhengca** [comment]
Thank You so much it solved the problem!!!! XD
