### ISSUE TITLE
Custom components

### ISSUE THREAD

**Issue by stef-pellegrino** [dddomodossola/remi#272]
Hi,

Is there a doc/tutorial which describes the way for creating a component ?

thanks

**Comment by dddomodossola** [comment]
@stef-pellegrino  Unfortunately there isn't a guide for this, but you can look at gui.py, it should be simple to mimic what's already done. 
Which kind of widget you need?

**Comment by stef-pellegrino** [comment]
Ok, I'm gonna take a look at gui.py... 
I need "lot" of widgets basically :)

In fact, the idea behind REMI (one language on front/back side) is quite interesting...
And Python is sooooo much more productive than JS.

Thanks for your help... And for REMI ;)

**Comment by dddomodossola** [comment]
@stef-pellegrino Have you found required info in gui.py?

**Comment by stef-pellegrino** [comment]
Hi, yes thanks, I'm working on it... ;)
