### ISSUE TITLE
To stop remi server within the python script?

### ISSUE THREAD

**Issue by bashkan** [dddomodossola/remi#274]
Hi,
Thanks again for the great library, it is really awesome.
I have a long script (over 1200 lines) which completely depends on REMI. The script does a lot of things including reading from/writing to an INI file. I have actually managed to read the INI file again within the script but there are times when the script needs to start over from the beginning (it's a long story). I tried this:
import os
import sys

And then within the code when a certain button is clicked on the web interface the following code runs:
if os.geteuid() == 0: #I run the script as root
    os.execvp("sudo", ["sudo"] + ["python"] + sys.argv)

What happens is, the script actually tries to restart but fails complaining: "socket.error: [Errno 98] Address already in use". I am guessing that the ports opened when remi server started were not closed so it can not start again. My question is; Is there a way to close ports/sockets and/or stop remi server (just before restarting) within the python script?
Thank you in advance.

**Comment by dddomodossola** [comment]
Hello @bashkan,

Here is an example to stop the server, making it available the listen port again:

    import remi.gui as gui
    from remi import start, App
    import os

    class MyApp(App):
        def main(self):
            main_container = gui.VBox(width=300, height=200, style={'margin':'0px auto'})
            main_container.onclick.connect(self.stop_server_and_restart)
            return main_container
        
        def stop_server_and_restart(self, emitter):
            self.server.server_starter_instance._alive = False
            self.server.server_starter_instance._sserver.shutdown()
            print("server stopped")
            #here the code to start again the script

    if __name__ == "__main__":
        # starts the webserver
        start(MyApp, address='0.0.0.0', port=8080, start_browser=True)

**Comment by bashkan** [comment]
Hello @dddomodossola,
Thank you for your detailed answer.
Unfortunately the result is the same. I even put a time.sleep(5) but it didn't change anything. Just for your information, I tried to understand the root cause, and looked at line 224 at socket.py where the error occurred. But it is way beyond my knowledge and coding skills :D I think I have to admit defeat and remove restart functionality.  But thank you anyway, you are always a great help.
Best Regards.
