### ISSUE TITLE
[PySimpleGUI] Specifying an image in gui.Image (solved)

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [dddomodossola/remi#278]
I read through this description of the Image Widget:
https://github.com/dddomodossola/remi/issues/207

I would like to allow the user to specify an image anywhere on the system... any arbitrary path.

I have tried setting the parameter `static_file_path` with no luck. I get a blank area where the image should be.
`
                super(Window.MyApp, self).__init__(*args, static_file_path=os.path.abspath(r'C:\Python\PycharmProjects\GooeyGUI\Logos'))`

When I make my calls with your filename `/res:logo.png' your logo shows up fine.  So, I at least know my "Image Element" is mapping correctly to your "Image Widget".  I just cannot seem to get the filename into a format that it likes.

Is it possible to set it up so that any filename the use chooses can be displayed?

I'm sorry if this is a bit of a repeat.  I didn't find the answer I needed in the #207 issue.

**Comment by MikeTheWatchGuy** [comment]
OK, I finally "figured it out" after reading something on gitter you wrote.

The key for me was the alternate format for `static_file_format`

Here is my call from MyApp init.

`super(Window.MyApp, self).__init__(*args,  static_file_path={'psg_res':r'c:'})`

Once I got this in, then I was able to choose files from drive C.  I would like to set it to root so that c:, d:, etc can be used.

**Comment by MikeTheWatchGuy** [comment]
OK, nevermind on getting image sizes.  If I don't set any size then it seems to set it to the image size.


I would very much like to work with Base64 images.  I use them heavily in other PySimpleGUI ports as it allows images without any external files.  Rather than write them to a temp file, I would prefer to do something else.  **_Can I pass to you something besides a "filename" when creating an Image?_**

**Comment by MikeTheWatchGuy** [comment]
This is my final static_file_path settings:
```python
                super(Window.MyApp, self).__init__(*args,  static_file_path={'C':'c:','c':'c:','D':'d:', 'd':'d:', 'E':'e:', 'e':'e:', 'dot':'.', '.':'.'})
```

These definitions allow me to use statements like these in my code:
```
            [sg.Image(filename=r'e:\DownloadsE\60a1a06a9458ccd6575333e06cb42f1b-png.jpg')],
            [sg.Image(filename=r'C:\Python\PycharmProjects\GooeyGUI\Logos\PySimpleGUI Icon.png', enable_events=True, key='_IMAGE_')],
            [sg.Image(filename=r'dot:logo.jpg')],
            [sg.Image(filename=r'res:logo.png')],
```

My `Image` object automatically adds the '\' that is needed by Remi before these filenames.  By defining the drive letters in the static_file_path, it has enabled me to be able to use what looks like normal windows file paths.

**Comment by dddomodossola** [comment]
@MikeTheWatchGuy This is not a good solution to add all the drive letters to the resource paths. You should instead use a different image widget, loading the image data directly instead of making it loaded by the server. With the standard Image widget the situation is this:
- You setup an image name, together with a resource path name;
- the webpage, asks to the remi server for the image;
- the remi server looks for the resource path name, checks its conformity, checks the file exists and returns the content.

You can avoid all this. You can make the webpage to ask for the image data calling a well defined method ("defined by you") where you will return the image data, loading its content by file.

Here is a widget for you
```python
class SuperImage(gui.Image):
    def __init__(self, file_path_name=None, **kwargs):
        super(SuperImage, self).__init__("/res/logo.png", **kwargs)
        
        self.imagedata = None
        self.mimetype = None
        self.encoding = None
        self.load(file_path_name)

    def load(self, file_path_name):
        self.mimetype, self.encoding = mimetypes.guess_type(file_path_name)
        with open(file_path_name, 'rb') as f:
            self.imagedata = f.read()
        self.refresh()

    def refresh(self):
        i = int(time.time() * 1e6)
        self.attributes['src'] = "/%s/get_image_data?update_index=%d" % (id(self), i)

    def get_image_data(self, update_index):
        headers = {'Content-type': self.mimetype if self.mimetype else 'application/octet-stream'}
        return [self.imagedata, headers]

```

An example here:
[repl](https://repl.it/@DavideRosa/sliderchangeminmax)

;-)

**Comment by MikeTheWatchGuy** [comment]
OH!  Just now noticed this... I'll work on integrating it instead of continuing the way I have been.

I could have never written a class like this.  Thank you SO much!
