### ISSUE TITLE
[PySimpleGUI] How to startup in a repl.it friendly way

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [dddomodossola/remi#280]
I'm able to run my programs locally with no trouble.

I'm able to sometimes run my repl.it versions of the same program with no issues.  

BUT, I'm finding if I have a browser window open with another repl.it script running, then my scripts have issues.  At least I think that's part of the problem.

I also find that the MyApp object's init call is made several times.

Here is my current "start" call:

```python
        remi.start(self.MyApp, title=self.Title ,debug=False, address='0.0.0.0', port=0,  start_browser=True, update_interval=.00001, userdata=(self,))
```

Here's my repl.it code:  https://repl.it/@PySimpleGUI/Design-Pattern-1-One-shot-Window

And here's the errors I got despite it working

> Python 3.6.1 (default, Dec 2015, 13:05:11)
> [GCC 4.8.2] on linux
> starting up...
> starting up...
> 172.18.0.1 - - [18/Feb/2019 22:38:51] "HEAD / HTTP/1.1" 200 -
> 172.18.0.1 - - [18/Feb/2019 22:38:51] "HEAD / HTTP/1.1" 200 -
> 172.18.0.1 - - [18/Feb/2019 22:38:51] "GET / HTTP/1.1" 200 -
> 172.18.0.1 - - [18/Feb/2019 22:38:51] "GET / HTTP/1.1" 200 -
> ----------------------------------------
> Exception happened during processing of request from ('172.18.0.1',41676)
> 172.18.0.1 - - [18/Feb/2019 22:38:51] "HEAD / HTTP/1.1" 200 -
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/socketserver.py", line 639, in process_request_thread
>     self.finish_request(request, client_address)
>   File "/usr/local/lib/python3.6/socketserver.py", line 361, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "/home/runner/.site-packages/PySimpleGUIWeb/PySimpleGUIWeb.py", line 3214, in __init__
>     super(Window.MyApp, self).__init__(*args)
>   File "/home/runner/.site-packages/remi/server.py", line 305, in __init__
>     super(App, self).__init__(request, client_address, server)
>   File "/usr/local/lib/python3.6/socketserver.py", line 696, in __init__
>     self.handle()
>   File "/usr/local/lib/python3.6/http/server.py", line 418, in handle
>     self.handle_one_request()
>   File "/usr/local/lib/python3.6/http/server.py", line 406, in handle_one_request
>     method()
>   File "/home/runner/.site-packages/remi/server.py", line 558, in do_GET
>     ws = WebSocketsHandler(self.headers, self.request, self.client_address, self.server)
>   File "/home/runner/.site-packages/remi/server.py", line 122, in __init__
>     socketserver.StreamRequestHandler.__init__(self, *args, **kwargs)
>   File "/usr/local/lib/python3.6/socketserver.py", line 696, in __init__
>     self.handle()
>   File "/home/runner/.site-packages/remi/server.py", line 138, in handle
>     clients[self.session].websockets.remove(self)
> ValueError: list.remove(x): x not in list
> ----------------------------------------
> ----------------------------------------
> Exception happened during processing of request from ('172.18.0.1',41344)
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/socketserver.py", line 639, in process_request_thread
>     self.finish_request(request, client_address)
>   File "/usr/local/lib/python3.6/socketserver.py", line 361, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "/home/runner/.site-packages/PySimpleGUIWeb/PySimpleGUIWeb.py", line 3214, in __init__
>     super(Window.MyApp, self).__init__(*args)
>   File "/home/runner/.site-packages/remi/server.py", line 305, in __init__
>     super(App, self).__init__(request, client_address, server)
>   File "/usr/local/lib/python3.6/socketserver.py", line 696, in __init__
>     self.handle()
>   File "/usr/local/lib/python3.6/http/server.py", line 418, in handle
>     self.handle_one_request()
>   File "/usr/local/lib/python3.6/http/server.py", line 406, in handle_one_request
>     method()
>   File "/home/runner/.site-packages/remi/server.py", line 558, in do_GET
>     ws = WebSocketsHandler(self.headers, self.request, self.client_address, self.server)
>   File "/home/runner/.site-packages/remi/server.py", line 122, in __init__
>     socketserver.StreamRequestHandler.__init__(self, *args, **kwargs)
>   File "/usr/local/lib/python3.6/socketserver.py", line 696, in __init__
>     self.handle()
>   File "/home/runner/.site-packages/remi/server.py", line 138, in handle
>     clients[self.session].websockets.remove(self)
> ValueError: list.remove(x): x not in list
> ----------------------------------------
> 172.18.0.1 - - [18/Feb/2019 22:38:52] "GET / HTTP/1.1" 200 -
> 172.18.0.1 - - [18/Feb/2019 22:38:52] "HEAD / HTTP/1.1" 200 -
> 172.18.0.1 - - [18/Feb/2019 22:38:52] "GET / HTTP/1.1" 200 -
> 172.18.0.1 - - [18/Feb/2019 22:38:52] "GET / HTTP/1.1" 200 -
> 172.18.0.1 - - [18/Feb/2019 22:38:57] "HEAD / HTTP/1.1" 200 -
> 172.18.0.1 - - [18/Feb/2019 22:38:57] "GET / HTTP/1.1" 200 -
>

**Comment by dddomodossola** [comment]
Hello @MikeTheWatchGuy ,
I've seen the same problem on repl.it. Now I'm making some tests to make remi working on Heroku. 
We can't solve the problem on repl.it without the technical support of the repl's staff.

**Comment by MikeTheWatchGuy** [comment]
Whew!  I'm glad it's not just me!

I took a peek at Heroku.  You're fearless!  I couldn't make sense of any of it, but I'm not a web guy.

**Comment by dddomodossola** [comment]
@MikeTheWatchGuy got it working on Heroku https://remitest.herokuapp.com/
I will give you some directions tonight

**Comment by MikeTheWatchGuy** [comment]
Oh wow!  You're SO productive!  This is amazing

**Comment by dddomodossola** [comment]
Here is an heroku "tutorial":

Download Heroku console from here [heroku](https://devcenter.heroku.com/articles/getting-started-with-python#set-up)
Open a windows console (cmd) and run the following command "heroku login", then login to heroku
Open the heroku [dashboard](https://dashboard.heroku.com/apps)
Create a new App named pysimpleguitest and click on "Create app"
From the windows console type "heroku git:clone -a pysimpleguitest" and press enter
then "cd pysimpleguitest"
in this folder create a file named "runtime.txt" and write in it `python-3.7.2` and save
create another file named "requirements.txt" and write inside the dependencies i.e. "remi"
create your script named my_app.py, here is the content:
```python
import remi.gui as gui
from remi import start, App
import os

class MyApp(App):
    def main(self):
        main_container = gui.VBox(width=300, height=200, style={'margin':'0px auto'})
        return main_container

if __name__ == "__main__":
    heroku_port = int(os.environ['PORT'])
    start(MyApp, address='0.0.0.0', port=heroku_port, start_browser=False)
```

create a file named "Procfile" without extension and write inside `web: python my_app.py`

From the windows console type the following commands
```
git add *
git commit -am "first commit"
git push heroku master
heroku ps:scale web=1
heroku open
```

let me know if it works for you ;-)

**Comment by khink** [comment]
Following these steps works. Thanks @dddomodossola !

**Comment by dddomodossola** [comment]
you are welcome ;-)

**Comment by MikeTheWatchGuy** [comment]
I never completed getting it working... I've got too many other fixes to put into my code that you've already given me.

**Comment by MikeTheWatchGuy** [comment]
Oh, I do have a question.... I am unable to run some of my repl.it scripts if it is loaded on another web page.  I tried experimenting with the startup settings but didn't find a workaround.  As long as it's the only repl.it thing running, It all works great.

**Comment by MikeTheWatchGuy** [comment]
This one can be closed as I've been working with repl.it folks for any problems I've had on there recently.
