### ISSUE TITLE
Does Remi run on Google Colab?

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [dddomodossola/remi#281]
I was able to pip install both PySimpleGUIWeb and Remi.
https://colab.research.google.com/drive/1gK695vLEPDuQ5P22pB7FrWouPvhe69QP

I dunno if you can see it or not.

I'm not able to connect to the window or see any output. It appears to be running the code however.

**Comment by dddomodossola** [comment]
Hello @MikeTheWatchGuy ,
unfortunately google colab is not able to host website/webapplications. You can't see the webpages created with remi or flask or django and so on.
