### ISSUE TITLE
[PySimpleGUI] Scroll to End of Input Text Widget

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [dddomodossola/remi#282]
We started this discussion over on Reddit.
https://www.reddit.com/r/RemiGUI/comments/akt14w/how_to_autoscroll_a_multiline_text_input_field/

I had given up for a while now and want to return.  My apologies for not getting it right the first time.  I still have to go find all the stuff you already gave me.  I'll continue to gather.

I have made this repl.it out of the source code to my PySimpleGUIWeb package.
https://repl.it/@PySimpleGUI/PySimpleGUIWebpy

It is this code that interfaces with Remi.  It comes with a test harness.  If you type characters into the upper part of the window, it will output stuff in middle large scrolling area.
![image](https://user-images.githubusercontent.com/13696193/53829608-87366a00-3f4e-11e9-8b6d-43e436c47d83.png)

I have a line of code commented out on line 1087 that looks like this and I believe something that you asked me to add.

```
app.execute_javascript("document.getElementById('%s').scrollTop=%s;" % (self.Widget.identifier, 9999))  # 9999 number of pixel to scroll
```

When I uncomment it, I get this error.
```
Traceback (most recent call last):
  File "main.py", line 6479, in <module>
    main()
  File "main.py", line 6470, in main
    window.Element('_MULTIOUT_').Update('EVENT: ' + str(event), append=True)
  File "main.py", line 1087, in Update
    app.execute_javascript("document.getElementById('%s').scrollTop=%s;" % (self.Widget.identifier, 9999))  # 9999 number of pixel to scroll
  File "/home/runner/.site-packages/remi/server.py", line 479, in execute_javascript
    self._send_spontaneous_websocket_message(_MSG_JS + code)
  File "/home/runner/.site-packages/remi/server.py", line 465, in _send_spontaneous_websocket_message
    for ws in self.websockets:
AttributeError: 'MyApp' object has no attribute 'websockets'
```

**Comment by dddomodossola** [comment]
Hello @MikeTheWatchGuy ,

here is the corrected version https://repl.it/@DavideRosa/PySimpleGUIWebpy-2

the fixes made are:

    #>>>> protected the call <<<<
    if hasattr(app, "websockets"):
                app.execute_javascript("document.getElementById('%s').scrollTop=%s;" % (self.Widget.identifier, 9999))


and:

    class MyApp(remi.App):
        def __init__(self,*args, userdata2=None):
            # self.window = window    # type:  Window
            # print(args[-1])
            if userdata2 is None:
                userdata = args[-1].userdata
                self.window = userdata[0]       # type: Window
            else:
                self.window = userdata2         # type: Window
            
            self.master_widget = None
            if userdata2 is None:
                res_path = os.path.dirname(os.path.abspath(__file__))
                # print('res path', res_path)
                super(Window.MyApp, self).__init__(*args,  static_file_path={'C':'c:','c':'c:','D':'d:', 'd':'d:', 'E':'e:', 'e':'e:', 'dot':'.', '.':'.'})
            #>>>> MOVED THE FOLLOWING LINE AFTER the super(...) <<<< 
            self.window.App = self

and:

    #>>>> update interval MUST be 0 to make it possible predictable sequence of javascript messages and update messages <<<<
    web_update_interval=0

**Comment by MikeTheWatchGuy** [comment]
OMG, you actually directly modified my PySimpleGUI code!!

Damn,... that's SO HELPFUL!  Because, IT WORKS!!!

I'm sorry you had to wade through all my crappy code.  I don't know what I'm doing so much of it is hit or miss.  You nailed this one for me.

**Comment by MikeTheWatchGuy** [comment]
I just finished merging your changes into the latest PySimpleGUIWeb.py file and it's working GREAT!!!

I appreciate this SO much Davide.

**Comment by dddomodossola** [comment]
@MikeTheWatchGuy you are really welcome, and thank you to be patient

**Comment by MikeTheWatchGuy** [comment]
By the way, moving this line of code to after the super call broke my code:
```
            super(Window.MyApp, self).__init__(*args,  static_file_path={'C':'c:','c':'c:','D':'d:', 'd':'d:', 'E':'e:', 'e':'e:', 'dot':'.', '.':'.'})
        #>>>> MOVED THE FOLLOWING LINE AFTER the super(...) <<<< 
        self.window.App = self
```

It appears as if it never returns to execute that statement.  I moved it before the super and all is well again.
