### ISSUE TITLE
[PySimpleGUI] How to reroute STDOUT

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [dddomodossola/remi#283]
In all of my ports of PySimpleGUI, I have a Widget (Element) named Output.  This is the same as a multi-line text output Element except that whatever you print will go to this window instead of the console.

When I create a multiline output element now, I use a Remi TextInput Widget.
```python
               remi.gui.TextInput(single_line=False)
```

I use this widget for both input and output, but make a distinction so that the output one cannot be erased by the user (by setting the widget as disabled)

I'm guessing that this re-reoute is actually something that belongs in my code and not the code that interfaces to Remi, but am asking anyway just in case you've seen something like this done before with Remi.

**Comment by dddomodossola** [comment]
@MikeTheWatchGuy Here is the promised solution. In the following example stdout gets redirected to a StringIO. In **idle** loop the content of the StringIO is copied into a TextInput.

```
import remi.gui as gui
from remi import start, App
import sys
try:
    from io import StringIO
except:
    from cStringIO import StringIO

stdout_string_io = StringIO()
sys.stdout = stdout_string_io

class MyApp(App):
    def idle(self):
        stdout_string_io.seek(0)
        lines = stdout_string_io.readlines()
        lines.reverse()
        self.stdout_text_input_widget.set_text("".join(lines))

    def main(self):
        #creating a container VBox type, vertical (you can use also HBox or Widget)
        main_container = gui.VBox(width=300, height=200, style={'margin':'0px auto'})
        
        print("test")
        
        self.stdout_text_input_widget = gui.TextInput(singleline=False, width="100%",height="100%")
        self.stdout_text_input_widget.attributes['disabled'] = 'true'

        bt_do_a_print = gui.Button("do a print")
        bt_do_a_print.onclick.connect(self.do_a_print)

        main_container.append([self.stdout_text_input_widget, bt_do_a_print])
        # returning the root widget
        return main_container

    def do_a_print(self, emitter):
        print("this print will be appended to the textInput widget")


if __name__ == "__main__":
    start(MyApp, start_browser=True)

```

**Comment by MikeTheWatchGuy** [comment]
Thank you thank you!!

Let me see how to work this into my code!

I forgot what I'm using as the "Multiline Output" element that I'll be hooking to. 

This looks awesome!

I SO APPRECIATE THE HELP!

**Comment by dddomodossola** [comment]
@MikeTheWatchGuy you are really welcome ;-)

**Comment by MikeTheWatchGuy** [comment]
I hooked it up to my code and even put it into a repl.it for examination:
https://repl.it/@PySimpleGUI/Remi-Stdout-Test

I don't seem to be getting to the Idle function however, and thus my Output Element isn't being updated.

My console output does stop, so I know stdout is going somewhere different.

Do I need to do something special to get the idle function to run?

**Comment by MikeTheWatchGuy** [comment]
Oh wait!!!

It WORKS if I change my update_interval from 0 to 1.

I used to have it set to .00000001  but you told me to set it to 0 for some reason that I don't recall now.

**Comment by MikeTheWatchGuy** [comment]
I'm finding now that the output is inverted in terms for first last, last first and the "autoscroll" feature needs to be added.

I'm trying to move over or call directly, the code that will "autoscroll" to the bottom, etc, like my other multiline output elements are working.

You can see the problem here.  Every time you click OK, a new line is printed with a higher number:
https://repl.it/@PySimpleGUI/Remi-Stdout-Test

I LOVE repl.it now!  I can send someone code and they don't have to even download it to try it out and see the behavior.

![image](https://user-images.githubusercontent.com/13696193/55687511-99376e00-593b-11e9-863e-b149d3482a83.png)

**Comment by MikeTheWatchGuy** [comment]
OK, fixed it all!
I just needed to remove a reverse and then call code I already got help on that appended to the bottom of the widget and then immediately scrolled to the bottom.

THIS IS GREAT!!
