### ISSUE TITLE
First Item in DropDown Menu Not Returning Correct get_key()

### ISSUE THREAD

**Issue by Trent1048** [dddomodossola/remi#284]
I have a DropDown menu that holds a bunch of files in a folder in the current directory. I have it set up so when I click on one and then press a button it will open the file by taking the file location from the key of the item and interpreting the file to do something on the website. This will work on all of the files in the DropDown except for the first one if it is not the first thing you press on the website. Let me give an example. I open up the website and select the first file, click open, it opens. Then I click on file 2 and then open it. Then when I click on file number 1 and hit open, it will reopen file number 2. When file 1 is selected it is probably either returning the key of the previous item pressed, or nothing at all so the program doesn't think you ever clicked the item with the first file.

**Comment by dddomodossola** [comment]
Hello @Trent1048 ,
can you please provide an example that reproduce the problem, to make it possible diagnose the causes?

**Comment by Trent1048** [comment]
Turns out I had faulty code
