### ISSUE TITLE
Latest version?

### ISSUE THREAD

**Issue by MisterY** [dddomodossola/remi#290]
Hi,

I see the version 2019.4 available on pip. However, I fail to find it in the source code. Is this repository containing the latest version of the code? The ReadMe suggests to use the git clone but in this case it seems that the repository has an even older version than is available in PyPi.

Great project, BTW. Just doing some experiments initially. Hope to be able to contribute.

Cheers

**Comment by dddomodossola** [comment]
Hello @MisterY 
I forgot to apply a tag to the last commit. The last commit correspond to the last pip version. Have a good coding

**Comment by MisterY** [comment]
Great, thanks! [setup.py](https://github.com/dddomodossola/remi/blob/master/setup.py) shows 2018.12, which confuses me.

**Comment by dddomodossola** [comment]
Thank you for reporting this, I make a correction now
