### ISSUE TITLE
Progress Bar Style

### ISSUE THREAD

**Issue by KamilGrudz** [dddomodossola/remi#292]
Is it possible to change the progress bar style? I've tried the "color"' and "background-color" tags in  the style settings but it does not seem to work correctly. What I wanted to change is especially the color of the progress bar, as well as the color and thickness of the outline.

**Comment by dddomodossola** [comment]
@KamilGrudz unfortunately it should be not possible/not simple to do , this beacuse it is a "standard browser widget". 
But however you can simply create your own progress bar with Svg elements and so with custom style.
Here is an example about Slider widget made with Svg elements:

    import remi.gui as gui
    from remi import start, App
    import os


    class SvgDraggablePoint(gui.SvgCircle):
        def __init__(self, x, y, radius, *args, **kwargs):
            super(SvgDraggablePoint, self).__init__(x, y, radius, *args, **kwargs)
            self.radius = radius
            self.active = False
        
        def start_drag(self, emitter, x, y):
            self.active = True

        @gui.decorate_event
        def stop_drag(self, emitter, x, y):
            self.active = False
            return ()

        def on_drag(self, emitter, x, y):
            if self.active:
                self.set_position(x, self.attributes['cy'])


    class SvgSlider(gui.Svg):
        def __init__(self, value, _min, _max, step, width, height, *args, **kwargs):
            super(SvgSlider, self).__init__(width, height, *args, **kwargs)
            self.min = _min
            self.max = _max
            self.step = step
            self.width = int(self.attributes['width'])
            self.height = int(self.attributes['height'])

            self.horizontal_line = gui.SvgRectangle(self.height/2,self.height/2-2, self.width-self.height, 2)
            self.horizontal_line.set_fill('gray')
            self.horizontal_line.set_stroke(1, 'lighgray')

            self.pointer = SvgDraggablePoint(self.width/2, self.height/2, self.height/2)
            self.pointer.set_fill('lightblue')
            self.pointer.set_stroke(1, 'lightgray')
            self.onmousedown.do(self.pointer.start_drag)
            self.onmouseup.do(self.pointer.stop_drag)
            self.onmouseleave.do(self.pointer.stop_drag, 0, 0)
            self.onmousemove.do(self.pointer.on_drag)

            self.append([self.horizontal_line, self.pointer])
            self.pointer.stop_drag.do(self.onchange)

            self.set_value(value)

        @gui.decorate_event
        def onchange(self, emitter):
            self.set_value( (float(self.pointer.attributes['cx'])-self.pointer.radius)*(self.max-self.min)/(self.width-self.pointer.radius*2) + self.min )
            return (self.value, )

        def set_value(self, value):
            self.value = max(self.min, value)
            self.value = min(self.max, self.value)
            self.pointer.attributes['cx'] = str(int((self.value-self.min)*(self.width-self.pointer.radius*2)/(self.max-self.min))+self.pointer.radius)

        def get_value(self):
            return self.value
        

    class MyApp(App):
        def main(self):
            #creating a container VBox type, vertical (you can use also HBox or Widget)
            main_container = gui.VBox(width=300, height=200, style={'margin':'0px auto'})
            self.label = gui.Label("slider value: 10")

            self.slider = SvgSlider(10, -10, 18, 1, 200, 50)
            self.slider.onchange.do(self.on_slider_changed)

            main_container.append([self.label, self.slider])
            # returning the root widget
            return main_container
        
        def on_slider_changed(self, emitter, value):
            self.label.set_text("slider value: %s"%value)


    if __name__ == "__main__":
        # starts the webserver
        start(MyApp, address='0.0.0.0', port=0, start_browser=True)

**Comment by KamilGrudz** [comment]
Thank you very much for your response and for example! It will definitely be useful.

**Comment by MikeTheWatchGuy** [comment]
I'm so glad I saw this issue! I never thought about making my own progress meter!  That's exactly what I'm going to do in the short term, use the primitives I already have working.

Here is how a simple bar turned out when I used an Svg where I drew rectangles to show progress.  The result was excellent in my opinion given how little code it required.


![Progress Meter Web](https://user-images.githubusercontent.com/13696193/57167306-4ed6cf00-6dcb-11e9-954b-98c93639e5c2.gif)

I know it's not Remi code, but here's how my PySimpleGUIWeb code looks that created the GIF.

```python
import PySimpleGUIWeb as sg

BAR_SIZE = (200,20)
MAX = 1000
BACKGROUND_COLOR = 'gray'
BAR_COLOR = 'red'

def draw_bar(graph:sg.Graph, current, max, color):
    graph.Erase()
    graph.DrawRectangle((0,BAR_SIZE[1]), (int(BAR_SIZE[0]* current/max),0), fill_color=color)


def main():

    layout = [  [sg.Text('Progress Bar Simulation')],
                [sg.Graph(BAR_SIZE, (0,0), BAR_SIZE, background_color=BACKGROUND_COLOR, key='_GRAPH_' )],
                [sg.Button('Exit')]]

    window = sg.Window('Simulating a Progress Meter', layout)
    graph = window.Element('_GRAPH_')
    for count in range(MAX):             # Event Loop
        event, values = window.Read(timeout=1)
        if event in (None, 'Exit'):
            break
        draw_bar(graph, count, MAX, BAR_COLOR)
    sg.Popup('Maximum amount reached... exiting application')
    window.Close()

main()
```
