### ISSUE TITLE
How to  move an entire Svg "drawing"

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [dddomodossola/remi#294]
One of my Graph Element's methods is `Graph.Move()`.  What it does is move all of the graphic items that have been drawn, at the same time.  It's a good way to shift an entire graph over, for example.

How can I move everything at once, or do I get a list of children and move each of them?

My "containing" widget is an Svg.

**Comment by dddomodossola** [comment]
@MikeTheWatchGuy you can add all the elements in an SvgGroup widget, and then append it to the Svg widget. This way, if you move the SvgGroup, all its content will move.

**Comment by MikeTheWatchGuy** [comment]
Can I make the group and add new contents to it as a way of drawing?  In other words, do I make a single group when I create the Svg and then all future figures are appended to that group?

**Comment by dddomodossola** [comment]
yes of course ;-)

**Comment by MikeTheWatchGuy** [comment]
It's working!

**Comment by MikeTheWatchGuy** [comment]
It's the image one that I REALLY am looking forward to help on!!  It's the last piece.  If I can "DrawImage" onto the Svg Widget, I'll be set!

**Comment by dddomodossola** [comment]
look at the issue #279 I already replied you there about this
