### ISSUE TITLE
How to get Mouse Position within Svg Widget

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [dddomodossola/remi#297]
I am using an Svg Widget to be my Graph Element.  This is a PySimpleGUI Element (widget) that can be used to draw figures (circles, lines, images). 

One feature I offer is the ability to get events with the mouse location every time the mouse moves when inside that Element.  I also generate mouse down evens when clicks occur.

You've provided some code for me already that I'm using, but I don't have all of it integrated and am not sure I have all the right stuff.  

For clues I'm looking at the Star Field code that you gave me to show me how to integrate with PyGame.

**Comment by dddomodossola** [comment]
Hello @MikeTheWatchGuy ,
Of course you can use the same events as for the Widget class. This means that you can do:

    mysvg_element.onmousemove.connect(self.onmousemove)

the listener will be:

    def onmousemove(self, emitter, x, y):
        print("the mouse position is: ", x, y)

**Comment by MikeTheWatchGuy** [comment]
Thank you again!

I'm able to get these mouse moves events now.

But, I'm not able to get the mouse down and mouse up events.  The goal is to be able to detect when a "DRAG" happens.  In PySimpleGUI a DRAG is when the mouse button is down and the mouse moves.

Here is how I setup the callbacks for those events:

```python
                if element.DragSubmits:
                    element.Widget.onmousedown.connect(element.MouseDownCallback)
                    element.Widget.onmouseup.connect(element.MouseUpCallback)
                    element.Widget.onmousemove.connect(element.DragCallback)
```

I'm not seeing my mouse down callback nor up callback functions being called.  Are these valid events for the remi.gui.Svg class?

**Comment by MikeTheWatchGuy** [comment]
Check out what I can do now!

I just need to be able to detect mouse button down and up now so that I draw only when the button is down.

![Dragging with PSGWeb](https://user-images.githubusercontent.com/13696193/57151409-e245db00-6d9e-11e9-96c4-0769c0cf5e49.gif)

PySimpleGUIWeb code is returning mouse drag events while inside the Graph Element.

Here is the code that does the drawing:
```python
    elif event == '_GRAPH_':
        if prev_point is not None:
            window.Element('_GRAPH_').DrawLine(prev_point, values['_GRAPH_'],'black', 2)
        prev_point = values['_GRAPH_']
```

If I get a graph event then I am simply drawing a line from the last known location to the current.  Super simple!

**Comment by MikeTheWatchGuy** [comment]
I found my problem!

It was in the declaration of the callback function.

I'm still struggling with not seeing exceptions.

I did my own detection when I do the initial setup of my code by adding a try block around my code.  But I don't seem to get exceptions if they happen within the Remi code and in this case that was when it called back the function and I had an incorrect number of parameters.

After I changed the functions to this it worked:
```python
    def MouseDownCallback(self, *args):
        self.MouseButtonDown = True

    def MouseUpCallback(self, *args):
        self.MouseButtonDown = False
```

One problem I have at the moment is getting the position when a CLICK happens.... not a click and drag, but just a click.  How do I get the x,y position from the onclick callback?

**Comment by MikeTheWatchGuy** [comment]
I ended up utilizing Mouse Up as the "click" event instead of `onclick`.

I was never able to get the x,y coordinates when using the `onclick` callback.  When I thought about it all, I remembered that a "click" gets registered typically not when you push down on the mouse button, but rather when you release the button.

Using this technique I'm now able to report clicks along with the x,y position of the click.

As a result, I'm going to close this one.

```python
                    element.Widget.onmouseup.connect(element.MouseUpCallback)
                    # element.Widget.onclick.connect(element.ClickCallback)
```
