### ISSUE TITLE
[Request] Get listed in the readme?

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [dddomodossola/remi#298]
Would it be possible to get PySimpleGUIWeb listed in the "Projects that use Remi" section of the Readme?  I can understand if it's not a fit however as PySimpleGUI isn't an application.

**Comment by dddomodossola** [comment]
Hello @MikeTheWatchGuy of course, I will do this soon!

**Comment by dddomodossola** [comment]
@MikeTheWatchGuy done ;-)

**Comment by MikeTheWatchGuy** [comment]
OMG, you didn't have to include all that info!  How generous!  Damn....

**Comment by dddomodossola** [comment]
I took that from your repository, I think it is a good idea to mention your great project with an exhaustive description.
