### ISSUE TITLE
Include get_value()/get_key() as appropriate in these widgets please

### ISSUE THREAD

**Issue by KenT2** [dddomodossola/remi#30]
This could be a duplicate, original seems to have got lost in Github when changing to remi  :-(

Include get_value()/get_key() as appropriate in these widgets
SpinBox - value
ListView - key and value of selected item
DropDown - key and value of selected item
Input - value
Slider - value
ColorPicker - value
Date - value

**Comment by dddomodossola** [comment]
I missed it. :-)  I will do!

**Comment by dddomodossola** [comment]
Ken, it is done. Take care about that SpinBox is changed a little bit especially in the constructor, in order to be compliant to others Input widgets. Please feedback if it is ok for you.

**Comment by KenT2** [comment]
Works fine,thanks
