### ISSUE TITLE
Appending 2 VBox Widgets resulted in unexpected location

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [dddomodossola/remi#302]
I use the VBox container widget for what I call the Column Element.  These elements act like windows within windows in a way.  I can put a series of Elements inside of one and then place the entire "Column" of widgets.

The way I lay out my windows is row by row.  A single "Row" is an HBox.  Thus, to build up a row of widgets, I call `append` to add a new widget to the row.

When I do this with Columns, the location of the Widgets ended up at the bottom portion of the screen when I expected them to be at the top:

![image](https://user-images.githubusercontent.com/13696193/57195484-37115f00-6f21-11e9-8a67-3436185ed0be.png)

Executing my code on tkinter and Qt I get the results that I expected:
![image](https://user-images.githubusercontent.com/13696193/57195488-4db7b600-6f21-11e9-93a6-e0b1bcafdda9.png)

How can I get my VBox to align at the top of the widget to its left?

I don't expect you to understand my internal PySimpleGUI code, but here is how I go about creating one of these Columns using Remi:

```python
            if element_type == ELEM_TYPE_COLUMN:
                element = element   # type: Column
                element.Widget = column_widget = remi.gui.VBox()
                if element.Justification.startswith('c'):
                    # print('CENTERING')
                    column_widget.style['align-items'] = 'center'
                    column_widget.style['justify-content'] = 'center'
                else:
                    column_widget.style['justify-content'] = 'flex-start'
                    column_widget.style['align-items'] = 'baseline'
                if element.BackgroundColor not in (None, COLOR_SYSTEM_DEFAULT):
                    column_widget.style['background-color'] = element.BackgroundColor
                PackFormIntoFrame(element, column_widget, toplevel_form)
                tk_row_frame.append(element.Widget)
```

The call to `PackFormIntoFrame` is a recursive call into the same function that is currently being executed.  In other words, this portion of code is from the function `PackFormIntoFrame'.

The variable `tk_row_frame` is an HBox widget.

It was these style settings:
```python
            tk_row_frame.style['align-items'] = 'baseline'
            tk_row_frame.style['justify-content'] = 'flex-start'
```

**Comment by MikeTheWatchGuy** [comment]
Ooops.... I think I found my answer.

When I changed the tk_row_frame_style to this it worked as expected:
`            tk_row_frame.style['align-items'] = 'flex-start'
`

**Comment by dddomodossola** [comment]
;-) that's right @MikeTheWatchGuy
