### ISSUE TITLE
[Question] How to delete a figure from a drawing

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [dddomodossola/remi#303]
I "draw" various "figures" in my code.  I do this using an Svg and an svgGroup.

I have no problem creating and adding stuff to these 2 widgets, but I'm having difficulty deleting individual figures.  I can empty the entire Svg easy by calling widget.empty() and creating a new Group that I append to the widget (the Svg).

How can I delete a circle, line, etc, that I've created?  I've tried calling figure.empty() but that isn't working.

**Comment by MikeTheWatchGuy** [comment]
Nevermind, this seemed to do it!
```
        self.SvgGroup.remove_child(figure)
        del figure
```

**Comment by MikeTheWatchGuy** [comment]
I'm able to run my game of life in the browser now, unchanged, from the tkinter version.

**Comment by dddomodossola** [comment]
Wonderful, well done @MikeTheWatchGuy
