### ISSUE TITLE
[Bug?] Sliders only shown as horizontal

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [dddomodossola/remi#305]
I've checked what is being sent to the call to slider.  I set the value to either LAYOUT_HORIZONTAL or LAYOUT_VERTICLE which seems to be True or False.  I always get vertical sliders.  

```
orient = remi.gui.Widget.LAYOUT_HORIZONTAL if element.Orientation.lower().startswith('h') else remi.gui.Widget.LAYOUT_VERTICAL

element.Widget = remi.gui.Slider(layout_orientation = orient, default_value=element.DefaultValue, min=element.Range[0], max=element.Range[1],step=element.Resolution)
```

**Comment by dddomodossola** [comment]
@MikeTheWatchGuy  the standard slider widget can't be rotated. The best solution would be to make an svg slider widget, as you already seen for the progress bar. Here is an example:

https://www.reddit.com/r/RemiGUI/comments/9f60p2/a_simple_example_that_implements_a_slider_widget/

**Comment by MikeTheWatchGuy** [comment]
Thank you!
