### ISSUE TITLE
[Question] How to force Menu Items on top of other widgets

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [dddomodossola/remi#308]
I finally have menus building and displaying!  Getting closer and closer to having all the features done.

My menu entries are being blocked by the other widgets that are below it.

Here the left side of the "File" entries is chopped off by the images.

![image](https://user-images.githubusercontent.com/13696193/57531105-b8446980-7306-11e9-8d23-00c3ab751649.png)

If I place something large in front of the Menu, then I don't see any of the menu entries

**Comment by dddomodossola** [comment]
@MikeTheWatchGuy this is not a bug, depends on the structure of the layout.
You should be able to solve this by increasing the 'z-index' attribute of the widget you want to move up, in this case the *menu* or *menu bar*

    menubar.style['z-index']='1' #or something more

**Comment by MikeTheWatchGuy** [comment]
Hmmm.... here's my new code.  Did't appear to have an impact.

```python
                element.Widget = menubar = remi.gui.MenuBar(width='100%', height='30px')
                menubar.append(menu)
                tk_row_frame.append(element.Widget)
                element.Widget.style['z-index'] = '1'
```

**Comment by MikeTheWatchGuy** [comment]
I tried applying the same style to all menu related items including the `MenuItem` entries themselves:
`menu_item.style['z-index'] = '100'`

But nothing seems to be helping.  I'll try setting all other widgets to a lower number.

**Comment by dddomodossola** [comment]
If this doesn't work, please save the webpage and send me the html file, I will analyze it

**Comment by MikeTheWatchGuy** [comment]
[PySimpleGUIWeb Test Harness Window.txt](https://github.com/dddomodossola/remi/files/3166787/PySimpleGUIWeb.Test.Harness.Window.txt)


Here ya go!

Thank you!!!!

**Comment by dddomodossola** [comment]
@MikeTheWatchGuy the problem should be that you enclosed the menubar inside a subcontainer. The menubar should stay inside the main container. 
Another solution could be to increase the z-index of the menubar container.

**Comment by MikeTheWatchGuy** [comment]
The way my layouts work is that I get a VBox, then I "pack" all my stuff in there.

Packing means getting appending a series of HBoxes to that VBox.  

I tried adding the Menu to the VBox directly and it put it at the bottom for some reason despite it being the first thing that I appended.

I'll eventually get there now that I know more about the need to be in a different container and the zorder control.

**Comment by MikeTheWatchGuy** [comment]
Hard to believe this is a web page!

![menus](https://user-images.githubusercontent.com/13696193/57573987-00df4e00-73ff-11e9-8b3d-c2a7519720b6.gif)

**Comment by dddomodossola** [comment]
Well done @MikeTheWatchGuy ! 
What about your tests on microcontrollers?

**Comment by MikeTheWatchGuy** [comment]
(sent you a message about those)

**Comment by MikeTheWatchGuy** [comment]
Officially done!

**Comment by MikeTheWatchGuy** [comment]
You've made this so easy to do!
My Menu definition looks like this:
```python
[Menu(menu_def, key='_MENU_', text_color='yellow', background_color='#475841',  font='Courier 18')],
```

And it looks like this when displayed on Remi
![image](https://user-images.githubusercontent.com/13696193/57585600-4ad83a80-74b8-11e9-9ed7-35ff3d23c95f.png)

**Comment by MikeTheWatchGuy** [comment]
Oh!  
## QUESTION

Should I be able to disable individual menu items?  Or top level menu entries? I've tried setting disabled like I do other widgets but I don't see any difference.
