### ISSUE TITLE
[Question/Request] How to create a "Portable" version of Remi

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [dddomodossola/remi#309]
I want to be able to run Remi on embedded systems (along with `PySimpleGUIWeb `of course).

What I would like to give to developers is a single folder or zip file, that when unzipped into their application folder, they will be able to `import PySimpleGUIWeb` which in turn will `import remi`.

Can you help build an "image" that I could distribute?  I'm trying to make something super-simple, guaranteed to work every time, no setup things to run.  Just unzip and go.

**Comment by dddomodossola** [comment]
You can achieve this by simple copying remi sources in the same folder of the pysimpleguiweb, in the same folder if the user script.

**Comment by MikeTheWatchGuy** [comment]
This structure seems to work.

However, the contents of the res folder make the overall size larger than what it needs to be in my opinion.  For the Circuit Python folks, every byte seems to count.

It's working however so I'll close this one!   Thank you!!

**Comment by dddomodossola** [comment]
@MikeTheWatchGuy I think you can delete all resources without problems. Only the style.css  is important.
