### ISSUE TITLE
Callback for widget update

### ISSUE THREAD

**Issue by jmakitalo** [dddomodossola/remi#310]
Sometimes it is required to run javascript to perform an action on widget's HTML element and this action is to be performed immediately after the widget is updated. For example, if I create a log window and I want it to scroll down whenever a new line of text is appended. I can call execute_javascript() for JS that refers to the newly inserted element. However, because Remi updates elements in a separate thread, the element might not be yet in DOM when the JS is executed.

If I could hook some Python function to be called when my Widget has been updated as part of the DOM, I could then run the JS code.

**Comment by dddomodossola** [comment]
Hello @jmakitalo ,

you can achieve this by overloading *App.do_gui_update* method:

    import remi.gui as gui
    from remi import start, App
    import os


    class MyApp(App):
        def main(self):
            #creating a container VBox type, vertical (you can use also HBox or Widget)
            main_container = gui.VBox(width=300, height=200, style={'margin':'0px auto'})
            main_container.onclick.do(self.change_background)
            # returning the root widget
            return main_container

        def change_background(self, emitter):
            #this will trigger an update
            emitter.style['background-color'] = 'green'

        def do_gui_update(self):
            App.do_gui_update(self)
            with self.update_lock:
                #here you can execute you javascript after every gui update
                self.execute_javascript("console.debug('update');")


    if __name__ == "__main__":
        start(MyApp)

**Comment by jmakitalo** [comment]
Thanks for the fast response! I'm currently stuck with remi-1.0 where `do_gui_update` does not exist but I think I can do something similar with that version.

**Comment by dddomodossola** [comment]
Can I help you porting to the newest remi version?

**Comment by jmakitalo** [comment]
Thank you for offering help. At the moment I understand some of the differences between the versions but don't have the time to do the porting. I'll be in touch when I have more time.
