### ISSUE TITLE
Incorrect display of GridBox in Internet Explorer and Edge

### ISSUE THREAD

**Issue by Derriick** [dddomodossola/remi#313]
Hello,
I'm trying to use a GridBox to display items like in a table, but it doesn't work well in Internet Explorer (version 11) and Edge (not tested with Chrome): the elements put themselves under each other instead of making a grid.

The desired display (Firefox):
---
![firefox](https://user-images.githubusercontent.com/24304593/59030133-65f05d00-8860-11e9-8d21-c976aada403b.png)
---

The display in Internet Explorer 11:
---
![internet_explorer](https://user-images.githubusercontent.com/24304593/59030138-6a1c7a80-8860-11e9-9f5c-7731e2954944.png)
---

The display in Edge:
---
![edge](https://user-images.githubusercontent.com/24304593/59030140-6be63e00-8860-11e9-81c5-51bf5b719315.png)
---

**Comment by dddomodossola** [comment]
Hello @Derriick,
I'm unable to reproduce the problem. Can you show me an example script that causes this problem?

**Comment by Derriick** [comment]
Hello @dddomodossola,

I am on another computer (workday is over), which has the same version of Internet Explorer but another version of Edge.
The problem still appears in IE 11, but no longer in Edge, probably more up-to-date than on my work computer (Windows Enterprise).

I would have liked to do without Internet Explorer, but unfortunately it won't be possible for me, and Remi is just perfect for my project.

Here is a script that reproduces the problem:
```
#!/usr/bin/env python3

import remi.gui as gui
from remi import start, App

class MyApp(App):
	def __init__(self, *args):
		super(MyApp, self).__init__(*args)

	def main(self):
		wid  = gui.VBox(width='80%', margin='20px auto 0 auto')
		grid = gui.GridBox(width='80%')

		grid.define_grid([
			['label1', 'value1'],
			['label2', 'value2'],
			['label3', 'value3'],
			['label4', 'value4']
		])
		grid.append({
			'label1': gui.Label('Label 1'), 'value1': gui.CheckBox(False),
			'label2': gui.Label('Label 2'), 'value2': gui.CheckBox(True),
			'label3': gui.Label('Label 3'), 'value3': gui.TextInput('Value 3'),
			'label4': gui.Label('Label 4'), 'value4': gui.Label('Value 4')
		})
		
		wid.append(grid)
		return wid


if __name__ == "__main__":
	start(
		MyApp,
		debug=False,
		address='0.0.0.0',
		port=8080,
		multiple_instance=False,
		enable_file_cache=False,
		start_browser=False
	)
```

**Comment by mcondarelli** [comment]
Note that IE implements an [older version](https://www.w3.org/TR/2011/WD-css3-grid-layout-20110407/) of grid-layout specifications while Edge got fixed at v16. (see: https://caniuse.com/#feat=css-grid).
Could this be a problem?

**Comment by dddomodossola** [comment]
@mcondarelli that's right, as you correctly report grid layout is incompatible with ie11.
@Derriick here is an alternative implementation with Widget container

```python
#!/usr/bin/env python3

import remi.gui as gui
from remi import start, App

class MyApp(App):
	def __init__(self, *args):
		super(MyApp, self).__init__(*args)

	def main(self):
		wid  = gui.Widget(width='800px', margin='0px auto')

		children = [
			{'label': gui.Label('Label 1', width="50%"), 'value': gui.CheckBox(False, width="50%")},
			{'label': gui.Label('Label 2', width="50%"), 'value': gui.CheckBox(True, width="50%")},
			{'label': gui.Label('Label 3', width="50%"), 'value': gui.TextInput('Value 3', width="50%")},
			{'label': gui.Label('Label 4', width="50%"), 'value': gui.Label('Value 4', width="50%")}
		]

		for c in children:
			wid.append(gui.Widget(children=(c['label'], c['value']), width="100%", height=50, layout_orientation=gui.Widget.LAYOUT_HORIZONTAL))

		
		return wid


if __name__ == "__main__":
	start(
		MyApp,
		debug=False,
		address='0.0.0.0',
		port=8080,
		multiple_instance=False,
		enable_file_cache=False,
		start_browser=False
	)

```

**Comment by Derriick** [comment]
It's not perfect yet, but it's IE's fault. At least I have a grid 😄 
I'll start with that, thanks for the help!

**Comment by Derriick** [comment]
In fact, I also need to regularly update the displayed data (once or several times a second), but I can't find something that doesn't blink (I see the lines disappear and appear).
Any ideas?

**Comment by dddomodossola** [comment]
How do you update the content? Never seen blinking

**Comment by Derriick** [comment]
I haven't understood that I could indicate a key in addition to the value to be displayed to update it.
At first, I was trying to create lines and add them instead of others in my widget (with `add_child`).
Then I tried with `append`, thinking that I had to empty and fill my widget every time.

Now everything is working fine.

**Comment by dddomodossola** [comment]
@Derriick well done ;-)
