### ISSUE TITLE
Proper file navigation clientside

### ISSUE THREAD

**Issue by gglaive** [dddomodossola/remi#317]
Hello @dddomodossola 

First of all, remi is amazing. I needed a python GUI at work with little dependencies and remi is perfect for my needs. Thank you for this awesome project

So, here's my case : I have my remi script running on a server, and clients can connect remotely.
Before deploying my script on server, I was using it locally. I want users to select files and folders from their system. I used Tkinter within my remi app for the file navigation, because I found Tkinter more suitable for my case than what remi has to offer for files and folders selection.

However, and has you might expect, when the client click a button that open a Tkinter's file navigator, it opens on the server side, and not on clientside. Since remi is managing sockets by itself, I could'nt find a way yet to go around this issue.

So I came back to the FileUploader widget. Thanks to one of your reply on reddit, I've found the way to use it with a Button widget, so I could customize its appearance. It works perfectly in my case; The client can now navigate through his files, and the file navigator interface is the same as Tkinter.

At this point, my problems are :

- FileUploader does exactly what I need : It goes through the client's files and not the server's files, with the same look as Tkinter (That was the point of FileUploader, you would say). But FileUploader uploads the selected files to the server directly when selected, obviously, and I DON'T WANT that.
- I have nothing for folders' selection that looks and does the same as FileUploader (w/o the upload part, of course). Widgets such has FileSelectionDialog don't have the design that goes with my needs, and they navigate through the server's folders.

So what I need is :

- A way to do the same thing as FileUploader (client file selection) and look the same, but without uploading selected files on server (I suppose I need to overwrite a method, but dunno which one)
- The possibility to select folders in the same way too. I know I can turn around the problem by selecting a file, then getting the parent folder, but I need a folder selection here.
- Or a way to adapt Tkinter so it opens on the client's computer. (aka how to properly manage remi sockets)

Hope I was clear with my needs. Since the weekend is near I won't be able to test possible solutions you may give to me, just to reply to it. Thank you :-)

**Comment by dddomodossola** [comment]
Hello @gglaive ,
You are clear, but unfortunately the file browsing on the client side is limited by the browsers security rules, and is not under complete remi control. Furthermore you can't show a tkinter window on the client side, tkinter can't do this.
Using remi FileUpload widget you can only select multiple files, no folder selection is allowed.
Why you need to do so?

**Comment by gglaive** [comment]
Thank you for your answer.
I needed a folder selection because it was more practical. My application is used by nuclear engineers. They have a folder containing simulation elements : they select this folder so that the next items to be filled in or created refer directly to the contents of this folder. But the more I think about it, the less I found it essential. I certainly could find a way to turn around this with FileUpload. Unless I can't refer to the parent folder clientside with it. It was mostly a time saver. But if it's possible, that's good to me.
So I guess the only thing that I would like to be solved is how can I prevent FileUpload to upload on the server what is selected clientside, and basically just use it as a file selection/browser ? Unless it's mandatory for it to work..

**Comment by dddomodossola** [comment]
I can make an example for you that allows to select files and get its names. After the file selection, I suppose you would do something with these files. Maybe you would like to upload them later with a specific command, or simply process the content?

**Comment by gglaive** [comment]
It's more the second option. When they refer those files and launch a simulation, the simulation will uses data from those files (as you may guess, it goes to the parent folder path, and (tries to) open and read the files filled in by the user). Then, the simulation itself creates results files. From that point I suppose I could retrieve them with FileDownloader, but there's a lot of them, and inside results folders created during the simulation.
So, since the simulations would be run on server, is it necessary for the server to have the data files, or can it read them by searching through the client path ? If the second case was possible, then I would have no use for them to be uploaded on the server. Otherwise, You gave me an idea of how to make it properly now at least, since there will be a lot of them.
I wouldn't mind if you have an example of a clean way to upload those data files, then for the client to download all results (maybe a download all, or download separately), (I think there's not yet such an example here?), but it's fine if you don't have time, I have ideas I could try now, then tell you how it went. 
Anyway, thank you for taking the time to answer, I understand better how it works and it helps me a lot.

**Comment by dddomodossola** [comment]
@gglaive Excuse me, I hadn't the time to make an example for you because I'm busy for work. I will try to do this soon.

**Comment by gglaive** [comment]
No problem, do it whenever you have time to do so.
I tried to work around FileUploader since last time, and I am at a fairly successful stage now. I'm more worried about FileDownloader now, since I need a way to download multiple result files on one side, and a folder on the other side. So yeah, an example showing the possibilities with FileUploader and FileDownloader would be the best.
Also, it's somewhat related but not much, I would need to separate the results between users on server, therefore to retrieve the username used for connection (w/o password) in order to make/use this user's own specific folder. We could see that later eventually, according to what will happen. Thank you anyway, and have a great weekend.

**Comment by dddomodossola** [comment]
@gglaive Here is the promised example. It allows to upload multiple files and automatically start the download of the processed content (you can implement your own processing).

```
import remi.gui as gui
from remi import start, App
import os

class MyFileUploader(gui.FileUploader):
    def __init__(self, savepath='./', multiple_selection_allowed=False, *args, **kwargs):
        super(MyFileUploader, self).__init__(savepath, multiple_selection_allowed, *args, **kwargs)

    @gui.decorate_set_on_listener("(self, emitter, filedata, filename)")
    @gui.decorate_event
    def ondata(self, filedata, filename):
        # overloading this method to prevent file upload saving
        #with open(os.path.join(self._savepath, filename), 'wb') as f:
        #    f.write(filedata)
        return (filedata, filename)


class MyFileDownloader(gui.Widget, gui._MixinTextualWidget):
    """This file downloader allows to download files that are not stored locally.
        The file is kept in memory ready to be processed.
    """
    def __init__(self, text, filename, *args, **kwargs):
        super(MyFileDownloader, self).__init__(*args, **kwargs)
        self.type = 'a'
        self.attributes['download'] = os.path.basename(filename)
        self.attributes['href'] = "/%s/download" % self.identifier
        self.set_text(text)
        self._filename = filename
        self.data = []
        self.data_complete = False

    def add_data(self, chunk):
        self.data.append(chunk)

    def upload_complete_and_so_process(self):
        self.data_complete = True
        
    def download(self):
        headers = {'Content-type': 'application/octet-stream',
                   'Content-Disposition': 'attachment; filename="%s"' % os.path.basename(self._filename)}
        return [*self.data, headers]


class MyApp(App):
    def main(self):
        #creating a container VBox type, vertical (you can use also HBox or Widget)
        self.main_container = gui.VBox(width=300, height=200, style={'margin':'0px auto'})

        self.file_upload = MyFileUploader(multiple_selection_allowed=True)
        self.file_upload.ondata.do(self.process_data)
        self.file_upload.onsuccess.do(self.upload_terminated)
        self.main_container.append(self.file_upload)

        #here I will store MyFileDownloader instances that are created each time a file is uploaded
        self.file_downloaders = {}

        # returning the root widget
        return self.main_container

    def upload_terminated(self, emitter, filename):
        print("finish:", filename)
        #this method is called when the upload is complete, here you can process the file
        self.file_downloaders[filename].upload_complete_and_so_process()

        #here I start the download, but you can do it later, with other events
        self.execute_javascript("window.open('%s');"%self.file_downloaders[filename].attributes['href'])

    def process_data(self, emitter, filedata, filename):
        print("process:", filename)
        if not filename in self.file_downloaders:
            self.file_downloaders[filename] = MyFileDownloader(filename, "processed_" + filename)
            #I don't add this to the gui, just keep it in memory
            # but if you want to show it
            # self.main_container.append(self.file_downloaders[filename])
        self.file_downloaders[filename].add_data(filedata)


if __name__ == "__main__":
    # starts the webserver
    start(MyApp, address='0.0.0.0', port=0, start_browser=True)
```

**Comment by gglaive** [comment]
Thank you for this example ! I'm working around it now.
I have one more question : In your example, It will add a new FileDowloader each time a new file is uploaded. Is there a way to have only one FileDowloader to download all files at once ? And is it possible to download a folder with it, or is the use you make of it in your example the only way to work with FileDownloader ?
After that, I think I'll have everything I need for this case. Thank you again !

**Comment by dddomodossola** [comment]
@gglaive FileDownloader does nothing special, it executes a javascript command to start a file download. Of course that class can hold more than one file and initiate the download of all of them. Do you need an example about this? 
You can't download a folder, but however you can consider to compress all the files in a zip archive to be downloaded.

**Comment by gglaive** [comment]
@dddomodossola I would love an example of it, and with the zip archive you mentionned.

**Comment by dddomodossola** [comment]
@gglaive I will do my best, but I'm a bit busy, please be patient.

**Comment by gglaive** [comment]
@dddomodossola Sure, I will, no worries. Thank you !

**Comment by dddomodossola** [comment]
@gglaive Here is the example to download files compressed in a zip archive:

```python
import remi.gui as gui
from remi import start, App
import os
import zipfile
import io

class MyFileUploader(gui.FileUploader):
    def __init__(self, savepath='./', multiple_selection_allowed=False, *args, **kwargs):
        super(MyFileUploader, self).__init__(savepath, multiple_selection_allowed, *args, **kwargs)

    @gui.decorate_set_on_listener("(self, emitter, filedata, filename)")
    @gui.decorate_event
    def ondata(self, filedata, filename):
        # overloading this method to prevent file upload saving
        #with open(os.path.join(self._savepath, filename), 'wb') as f:
        #    f.write(filedata)
        return (filedata, filename)


class MyFileDownloader(gui.Widget, gui._MixinTextualWidget):
    """This file downloader allows to download files that are not stored locally.
        The file is kept in memory ready to be processed.
    """
    def __init__(self, *args, **kwargs):
        super(MyFileDownloader, self).__init__(*args, **kwargs)
        self.type = 'a'
        self.attributes['href'] = "/%s/download" % self.identifier
        self.files = {}

    def add_data(self, filename, chunk):
        if filename not in self.files:
            self.files[filename] = {}
            self.files[filename]['data'] = []
            self.files[filename]['data_complete'] = False
        self.files[filename]['data'].append(chunk)

    def upload_complete_and_so_process(self, filename):
        self.files[filename]['data_complete'] = True
        
    def download(self):
        #packaging files in a zip archive
        bio = io.BytesIO()
        zfile = zipfile.ZipFile(bio, "w")
        for filename in self.files.keys():
            zfile.writestr(filename, *self.files[filename]['data'])
        zfile.close()
        bio.seek(0)

        #removing files from memory, to be ready for other uploads
        self.files = {}

        headers = {'Content-type': 'application/octet-stream',
                   'Content-Disposition': 'attachment; filename="%s"' % "results.zip"}
        #return [*self.data, headers]
        return [bio.read(-1), headers]


class MyApp(App):
    def main(self):
        #creating a container VBox type, vertical (you can use also HBox or Widget)
        self.main_container = gui.VBox(width=300, height=200, style={'margin':'0px auto'})

        self.file_upload = MyFileUploader(multiple_selection_allowed=True)
        self.file_upload.ondata.do(self.process_data)
        self.file_upload.onsuccess.do(self.upload_terminated)
        self.main_container.append(self.file_upload)

        self.file_downloader = MyFileDownloader()

        # returning the root widget
        return self.main_container

    def upload_terminated(self, emitter, filename):
        print("finish:", filename)
        #this method is called when the upload is complete, here you can process the file
        self.file_downloader.upload_complete_and_so_process(filename)

        #here I start the download, but you can do it later, with other events
        self.execute_javascript("window.open('%s');"%self.file_downloader.attributes['href'])

    def process_data(self, emitter, filedata, filename):
        print("process:", filename)
        self.file_downloader.add_data(filename, filedata)


if __name__ == "__main__":
    # starts the webserver
    start(MyApp, address='0.0.0.0', port=0, start_browser=True)
```

**Comment by gglaive** [comment]
@dddomodossola Thanks for this example. Do you have a version of this FileDowloader but with files that are stored locally ? I don't need the whole thing, I have self.files = [] on MyFileDowloader which contains all my files correctly already, basically just the dowload method that I can't figure how to use correctly.
Something like :
```
       with zipfile.ZipFile('results.zip', "w") as zfile:
            for filename in self.files:
                zfile.write(filename)
        zfile.close()

        headers = {'Content-type': 'application/octet-stream',
                   'Content-Disposition': 'attachment; filename="%s"' % zfile(?)}
        return [zfile(?), headers]
```

**Comment by dddomodossola** [comment]
;)
