### ISSUE TITLE
[Question] Can I update a table?

### ISSUE THREAD

**Issue by johnneren** [dddomodossola/remi#320]
Hi.

I'm currently trying to create a table for displaying 10 data points with names and values. (like in excel)
These data points changes every second.

I have made a table which looks great but I can't seem to figure out how to update my table with new data.

Is this possible?
And if not, what type of widget do you recommend for displaying live data?

Thanks

**Comment by johnneren** [comment]
My table looks something like this.
I would like to replace the 'None' every second in idle() :)
 ```
     self.table = gui.Table.new_from_list([('Name', 'Value'),
                                 ('Outside 1', 'None'),
                                 ('Outside 2', 'None'),
                                 ('Inside 1', 'None'),
                                 ('Inside 2', 'None'),
                                 ('Inside 3', 'None'),
                                 ('Inside 4', 'None')], width=250, height=200, margin='5px')
```

**Comment by dddomodossola** [comment]
Hello @johnneren ,
Of course you can update a table. I'm not at my computer now, so I can't write fancy example.
To say it simply you can do:

my table.children['rowindex'].children['columnindex'].set_text('new_value')

tomorrow I can write you more info ;)

**Comment by johnneren** [comment]
Thanks a lot for the quick reply!
That was exactly what I was missing for it to work :)

👍
