### ISSUE TITLE
Errors on embedded machine

### ISSUE THREAD

**Issue by dovydasz** [dddomodossola/remi#322]
Hello,
I'm trying to run REMI on the ATSAMA5D27-SOM1 board. REMI and all the OS is built with Buildroot tool.
I try to run python widgets_overview_app.py. Firstly it shows messages that the server is running, but just try to open on browser http://192.168.10.5:8091 and these errors came up..
What I'm missing? :)

```
login as: root
# uname -r
4.14.73-linux4sam_6.0
# python -V
Python 2.7.15
# python widgets_overview_app.py
remi.server      INFO     Started websocket server 0.0.0.0:40223
remi.server      INFO     Started httpserver http://127.0.0.1:8091/
remi.request     INFO     built UI (path=/)
remi.update      ERROR    error updating gui
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/remi/server.py", line 337, in run
    client.idle()
  File "widgets_overview_app.py", line 25, in idle
    self.counter.set_text('Running Time: ' + str(self.count))
AttributeError: 'MyApp' object has no attribute 'counter'
remi.request     ERROR    error processing GET request
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/remi/server.py", line 809, in do_GET
    self.client.root = self.main(*self.server.userdata)
  File "widgets_overview_app.py", line 36, in main
    self.img.onclick.do(self.on_img_clicked)
AttributeError: 'function' object has no attribute 'do'
```

**Comment by dddomodossola** [comment]
Hello @dovydasz ,
Could it be possible you are using an older remi version? The "do" instruction is a recent update (1 April 2019). Try to update the remi version to the laster one. There are no reasons that can prevent remi to run on embedded devices.

**Comment by dovydasz** [comment]
Buildroot uses this package for remi
https://github.com/buildroot/buildroot/blob/master/package/python-remi/Config.in

Isn't the 'master' newest?

**Comment by dddomodossola** [comment]
The buildroot master version uses the remi version 1.1.
There were several updates to remi since that version. 
Refer to this page for that specific version (examples from this page will work for sure): https://github.com/dddomodossola/remi/tree/v1.1

**Comment by dovydasz** [comment]
Yes, you were right. My mistake. Thanks!

**Comment by dddomodossola** [comment]
@dovydasz you are welcome
