### ISSUE TITLE
remote access not loading page for pipresents

### ISSUE THREAD

**Issue by boschwakka** [dddomodossola/remi#325]
Hi
KenT2 from pipresents said i must chat to Davide, KenT2 is useing remi to send python code to a web page, if i am on the local network remi works fine and Pipresents works, i have put a dydns name in a router and set port forwarding for ports 8081 to 8082 linked to ip address of Pipresents server and i just get the folding square nothing else, image attached : what am i missing are there other ports i need to open in port forwarding?
![image](https://user-images.githubusercontent.com/28925207/61790528-ba06cf00-ae17-11e9-902e-9faa6f8bc9f6.png)
thanks

**Comment by dddomodossola** [comment]
Hello @boschwakka , which version of remi are you using? If you runs an updated version of remi, you don't need to open other ports. Older versions uses different ports for websocket and http.

**Comment by boschwakka** [comment]
The version used is the one i downloaded in pipresents developed by KenT2 version 1.3.5. downloaded last week and installed on a rasberry pi B+ . the access works on local network when i open firefox and at the address bar type 192.168.8.30:8081 it works. BUT when i have dns setup and connect to say pimedia.dyndns.org:8081 then i get the screen above. the above screen shown the page is loading but nothing else happens.

**Comment by dddomodossola** [comment]
Unfortunately the latest pipresent version uses an old remi version with missing features. You should try to upgrade to a new remi version.

**Comment by boschwakka** [comment]
thanks will try
