### ISSUE TITLE
Remi stops responding (websocket spontaneous message)

### ISSUE THREAD

**Issue by johnneren** [dddomodossola/remi#326]
Hi.

Sometimes (1 in 20 perhaps) I encounter an error when closing the webpage hosted by remi.
```python
remi.request     ERROR    sending websocket spontaneous message
Traceback (most recent call last):
  File "C:\python\lib\site-packages\remi\server.py", line 469, in _send_spontaneous_websocket_message
    ws.send_message(message)
  File "C:\python\lib\site-packages\remi\server.py", line 193, in send_message
    self.request.send(out)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
remi.server.ws   ERROR    error parsing websocket
Traceback (most recent call last):
  File "C:\python\lib\site-packages\remi\server.py", line 252, in on_message
    callback = get_method_by_name(runtimeInstances[widget_id], function_name)
  File "C:\python\lib\weakref.py", line 137, in __getitem__
    o = self.data[key]()
KeyError: '74977232'
```

When the error occurs I have to restart my remi application again to be able to reconnect with my webbrowser.
It seems to me the error relates to the socket being closed by the webbrowser at a bad time and the server cannot recover from this.

My application executes a live update of some tables and a PyGal graph every second from the remi idle thread. 
So I'm constantly pushing new data to the web browser. 
The error could relate to a missing exception handling when the soccket is getting closed during this type of update.

But I'm just guessing :)
Let me know if you have any tips or ideas.

/Johnny

**Comment by dddomodossola** [comment]
Hello @johnneren , can you please show me your script, or a simplified version of it? 
I suppose the problem could be caused by a Thread you instantiated that holds the App.update_lock, or an error that is not catched maybe when you send data to web browser.

Regards

**Comment by johnneren** [comment]
Hi @dddomodossola and thanks for replying.

I will try and make a simplified version for you, however precisely because I didn't want to deal with any locking issues I'm not creating any threads in my application.

I just have a *if 1 sec has passed* handling in the remi idle thread which uses 100-500ms processing time.
I am using sockets through a C library to a proprietary protocol which has a keep alive thread.
But this is the only thread I have and has no interaction with GUI.

My *one second* updates in the idle thread to the web browser is 100% through remi table and pygal objects.
Like this:
```python
      self.table_values.children['1'].children['1'].set_text(mode_str)
      self.table_values.children['2'].children['1'].set_text("%.2f °C" %(self.house.climate.outside_climate.get_temperature()))
      self.table_values.children['3'].children['1'].set_text("%.1f %%" %(self.house.climate.outside_climate.get_humidity()))
```

Or pygal:
`python
self.pygal_humidity.children['chart'] = self.draw_humidity_graph().render()
`

But I will try and see if I can recreate the issue with a 'stubbed' version where only GUI is running and get back to you in a few weeks :)

**Comment by dddomodossola** [comment]
@johnneren thank you, you are welcome

**Comment by johnneren** [comment]
@dddomodossola 
I had a little time and manage to recreate it using the 'widgets_overview_app.py' demo with a few modifications.

Changes made to demo:
- multiple_instances=False (required or you cannot recreate it. I use it because I need the webpages pages to have the same state even if multiple connections are active)
- Press Me! button triggers a 5 second sleep in idle thread. (simulates a one time 'connect to target' call I have which I think aggravates this problem a bit)
- port is 8091 instead of 8081 (just change it back if you want to)

How to recreate:
1. Run widgets_overview_app.py (spawns a new tab with the web page)
2. Open a extra tab to remi from a different host. (so now you have two tabs connected)
3. From tab 1 press 'Press me!'
4. After one second, close tab 2 (while the idle thread is sleeping)
5. Close remi server, so tab 1 activates the reconnect icon.
6. Start remi again, wait for tab 1 to reconnect. (You should now have two tabs connected again, the tab 1 which reconnected and the newly spawned tab 2)
7. From tab 1 press 'Press me!' (like in step 3)
8. After one second, close tab 2 (like step 4) (you should now get a non fatal exception)
9. Close tab 1 so all tabs are closed, this should trigger a second exception which is the fatal one.
10. Now you should not be able to connect anymore with new tabs.

I have included a debug_log when I recreated it using these steps with widgets_overview_app.py
[demo_with_log.zip](https://github.com/dddomodossola/remi/files/3428876/demo_with_log.zip)

It seems to me that close/cleanup of a connection will throw an exception if the idle thread is running while the close event triggers.
Furthermore if this occurs before a close event on a connection that has reconnected bad things happens.

Hope this helps :)

**Comment by dddomodossola** [comment]
@johnneren Thank you for the detailed information. I will test it soon and provide you a solution.

**Comment by dddomodossola** [comment]
@johnneren I was able to reproduce the problem. I'm working on a solution and will inform you soon

**Comment by dddomodossola** [comment]
Hello @johnneren should be fixed now. Can you please confirm? You should install the master branch version.

**Comment by johnneren** [comment]
Hi @dddomodossola 

I can confirm that the fix works and I can no longer force remi into an unresponsive state (yay!) 
Thanks for looking into this :)

FYI
One small observation which has nothing to do with this issue:
![billede](https://user-images.githubusercontent.com/6613864/62409797-e3281c00-b5dc-11e9-9b6c-b42af7c174b0.png)
When connecting first time with firefox to a remi server it seems to throw a few exceptions.
It still behaves as it should and it does not throw exceptions with chrome or edge so it might be something with firefox.
But it is not critical.
If I have the time to look into it and find a solution, I'll do a pull request and we can look at it then.

Cheers! (you may close this issue now)

**Comment by dddomodossola** [comment]
@johnneren thank you for the collaboration. The error you get is caused by the fact that browsers opens multiple concurrent connections at page open, this is done to load resources rapidly. Remi handles multiple connections coming from a node by overwriting them, so the concurrents are closed. The error is handled by remi and the error message is provided for debug purposes (for other situations). ;-)

**Comment by johnneren** [comment]
@dddomodossola likewise! And thank you for explaining the Firefox behavior :) 
I will close this issue.
