### ISSUE TITLE
Standalone app example terminates immediately

### ISSUE THREAD

**Issue by mrdimfox** [dddomodossola/remi#329]
I start `examples/standalone_app.py` but it terminates right after the start. The only print out I have in terminal is
```
remi.server      INFO     Started httpserver http://127.0.0.1:7769/
```
So, I had a little debug session and found out these lines:

```python
Server.start(self)
webview.create_window(self.title, self.address, **self._application_conf)
Server.stop(self)
```

As you can see, Server class starts, then webview window is created and right after that Server stops. I think a line `webview.start()` was missed, so it should be like this:

```python
Server.start(self)
webview.create_window(self.title, self.address, **self._application_conf)
webview.start()
Server.stop(self)
```

Am I right?

**Comment by dddomodossola** [comment]
@mrdimfox Thank you a lot, you are right! I will fix this rapidly.

**Comment by dddomodossola** [comment]
Fixed ;-)
The fix is only available on github master branch. I will make a release in a near future.

**Comment by mrdimfox** [comment]
@dddomodossola, awesome! Thanks!
