### ISSUE TITLE
FileUploader limit possible extentions for file selection

### ISSUE THREAD

**Issue by jra-skov-dk** [dddomodossola/remi#334]
Hi.

As far as I can see it is not possible to limit the extensions allowed for file selection using the FileUploader widget.

In the FileUploader contructor the 'accept' is set to.
`self.attributes['accept'] = '*.*'`

I tried something like this, but that didn't seem to work
```
self.browse = gui.FileUploader('./', width=100, height=20, margin='5px', style={'padding-top': '5px'})
self.browse.attributes['accept'] = '*.json'
```

Is this possible to do in another way?
(I need a *.json + *.csv accept filter if possible)

A second question if you don't mind.
My remi setup uses several pages which the user can switch between. (They are only initialized the first time you enter a page and then table values are refreshed on a timer)
When a file is selected and the 'No file selected is replaced with 'my_file.json' it works as expected.
But for some reason after I switch between another page and back to the page with my browse button the text is reset to 'No file selected (all of my other widgets on that page keep their state)
Can I change this behavior or 'load' the browse text with my own stored filename?

Thanks!

**Comment by dddomodossola** [comment]
@jra-skov-dk Unfortunately browsers doesn't implement correctly the "accept" attribute, so there is no solution for this.

About the second question: when you change the page, the browser loses the information about the fileUploadWidget. I suggest you to upload the file as soon as it is selected, and show in a label the filename. Then, if the user wants to discard that file, you can provide a "delete button" or simply overwrite it when a new file gets selected. Let me know if you need help about this. ;-)

**Comment by jra-skov-dk** [comment]
@dddomodossola 
Ok, I guess that's just how it works then :)
I will make a label with the file name in it and display that.

Thanks for replying!

/Johnny

**Comment by dddomodossola** [comment]
@jra-skov-dk you are welcome. Which kind of application are you making? Just for curiosity

**Comment by jra-skov-dk** [comment]
@dddomodossola 

I'm creating a simulation model for the climate behavior in a closed space. (like a  storage house/barn/chicken house etc.)
It calculates how inside temperature and humidity is affected by ventilation, heating, outside temperature, isolation, animals etc.

I use REMI as the GUI for the simulator.
I just wanted something web based in python which was easy to get started with.

I have a configuration page where you select some config files (json) which changes the simulation model and then you can monitor the simulation via 'tabs' made through REMI.
![image](https://user-images.githubusercontent.com/27812585/63841556-4eb69c80-c983-11e9-8c71-e6c04cd9bf95.png)

The taps are each separate python classes and files (to make it easy to add new functionality)
The main entry for the GUI is a page handler which handles the top status bar and 'redirects' menu button presses to generate the correct class.

Simplified it's something like this 

Adding Menu buttons with classes:
```python
   #generate top bars
   def generate_top_bars(self):
      self.infobar = gui.Menu(width='100%', height='30px', style={'font-size': '12px', 'color': 'white', 'background-color': 'rgb(19, 108, 209)'})
      self.menu = gui.Menu(width='100%', height='30px')
      
      #create top menus
      m1 = gui.MenuItem('Configuration', width=100, height=30)
      m2 = gui.MenuItem('Overview', width=100, height=30)
      m3 = gui.MenuItem('Climate', width=100, height=30)
      m4 = gui.MenuItem('Production', width=100, height=30)
      m5 = gui.MenuItem('Events', width=100, height=30)
      m6 = gui.MenuItem('Verification', width=100, height=30)
      m7 = gui.MenuItem('Selftest', width=100, height=30)
      m8 = gui.MenuItem('Tools', width=100, height=30)
      #ADD_NEW_PAGE_HERE

      #connect classes to top menus
      # pylint: disable=E1101
      m1.onclick.do(self.generate_page, self.configuration)
      m2.onclick.do(self.generate_page, self.overview)
      m3.onclick.do(self.generate_page, self.climate)
      m4.onclick.do(self.generate_page, self.production)
      m5.onclick.do(self.generate_page, self.events)
      m6.onclick.do(self.generate_page, self.verification)
      m7.onclick.do(self.generate_page, self.selftest)
      m8.onclick.do(self.generate_page, self.tools)
```
Main GUI generation class
```python
   def generate_page(self, emitter, content_class):
      
      if(content_class.gui_container is None):
         #get class specific content
         class_specific = content_class.init_page()

         #give up if no page
         if(class_specific is None):
            return

         container = gui.Widget(width='100%', margin='0px auto', style={'display': 'block', 'overflow': 'hidden'})

         #add to main container
         container.append(self.infobar)
         container.append(self.menubar)
         container.append(class_specific)

         #store container
         content_class.gui_container = container
      else:
         try:
            content_class.reinit_page()
         except AttributeError:
            pass

      #change page
      self.active_class = content_class
      self.set_root_widget(content_class.gui_container)
      return content_class.gui_container

```

All GUI classes implement a init/reinit and onesec function which is called on the class when the page is selected/active.

I use PyGal for plotting various data and sqlite for logging data.
![image](https://user-images.githubusercontent.com/27812585/63842814-a0602680-c985-11e9-927b-315038017037.png)


All in all REMI has been great to work with.
But sometimes I hit a snag where I cant quite figure out how to do it ;)

**Comment by dddomodossola** [comment]
@jra-skov-dk That's really cool! I know that the missing documentation is a problem. Ask me if you need help, you are welcome ;-)
