### ISSUE TITLE
gui.TabBox() no longer works with relative containers

### ISSUE THREAD

**Issue by jimbob88** [dddomodossola/remi#349]
I recently updated my code to use the latest version of remi (2019.4 -> 2019.11), which meant changing my `gui.Widget` code to `gui.Container`, with this I encountered an issue with my `gui.TabBox()` widget, where the relative setting made the Containers overlap the Tabs:

`2019.4`:
![Screenshot from 2019-12-26 12-52-19](https://user-images.githubusercontent.com/9913366/71476754-94bf2800-27de-11ea-97fc-296d82328ae5.png)

`2019.11`:
![Screenshot from 2019-12-26 12-53-04](https://user-images.githubusercontent.com/9913366/71476777-b15b6000-27de-11ea-8c8d-1573afdb116c.png)

**Comment by dddomodossola** [comment]
Hello @jimbob88 , what you mean when you says "the relative setting"? Can I see your code? I will help you to fix this

**Comment by jimbob88** [comment]
Hi, I have uploaded an example file on [pastebin](https://pastebin.com/kcqWSKJX), which shows the issue in action, the Label - i believe, correct me if I'm wrong - should be underneath the tab header not inside it (tested version:`2019.11`)

**Comment by dddomodossola** [comment]
Hello @jimbob88 it should be now fixed. The fix is on the master branch, not available on pypi. Please test it and let me know if it is ok for you.

**Comment by jimbob88** [comment]
Thanks for your help, this fixed the issue (at first I had an issue but then realised I had to force uninstall remi, then install the latest commit)!
