### ISSUE TITLE
Custom Dialog with TabBox error "no attribute page"

### ISSUE THREAD

**Issue by jimbob88** [dddomodossola/remi#356]
With my code I create a custom login and register dialogue but when I click register ( to change tab) nothing happens and this error appears:
```
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 42018)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "main.py", line 126, in __init__
    login.login_dialogue().show(self)
  File "/media/james/Development/Programming/Python/beer_engine/remi/venv/lib/python3.7/site-packages/remi/gui.py", line 2454, in show
    self._base_app_instance.set_root_widget(self)
  File "/media/james/Development/Programming/Python/beer_engine/remi/venv/lib/python3.7/site-packages/remi/server.py", line 462, in set_root_widget
    self.page.children['body'].append(widget, 'root')
AttributeError: 'beer_engine' object has no attribute 'page'
----------------------------------------
```

The code is available [login.py](https://pastebin.com/9yTuPU41) and [main.py](https://pastebin.com/UvKrAGB7).
Remi: 2019.11 (tested 2020.1.16 same issue)
OS: Ubuntu 19.04

Hope this can be fixed,
James

EDIT: For my code I was  able to get this to work by having a login button; however, it would be nice to be able to call a popup before `construct_ui` and if not perhaps a function that is automatically ran after `main` has finished!

**Comment by dddomodossola** [comment]
Hello @jimbob88 ,

excuse me the late reply. Here is an example to show a dialog on startup:

    import remi.gui as gui
    from remi import start, App
    import os

    class MyApp(App):
        def main(self):
            #creating a container VBox type, vertical (you can use also HBox or Widget)
            main_container = gui.VBox(width=300, height=200, style={'margin':'0px auto'})

            # returning the root widget
            return main_container

        def onpageshow(self, emitter, width, height):
            """ WebPage Event that occurs on webpage gets shown """
            diag = gui.GenericDialog('title', 'message')
            diag.show(self)
            super(MyApp, self).onpageshow(emitter, width, height)


    if __name__ == "__main__":
        # starts the webserver
        start(MyApp, address='0.0.0.0', port=0, start_browser=True, username=None, password=None)

hope this can help ;-)

**Comment by jimbob88** [comment]
Thank you very much for your help!
