### ISSUE TITLE
SyntaxError on running python3 widgets_overview_app.py

### ISSUE THREAD

**Issue by pawelevans** [dddomodossola/remi#359]
Hi,
Just going through the tutorial, and getting the following error:

File "widgets_overview_app.py", line 7
  <!DOCTYPE html>
SyntaxError: invalid syntax

Any suggestions?
Thanks

**Comment by dddomodossola** [comment]
Hello @pawelevans , which python version are you using? Can you show me the complete error message?

**Comment by pawelevans** [comment]
Hi and thanks for speed reply.
I just tried running the example scripts and they work fine.
I'm using python 3.5.2
The complete message is exactly as I posted.

**Comment by dddomodossola** [comment]
I installed python3.5.2 and I have no problems. I suggest you to download again the remi examples. Let me know if the problem persist.

**Comment by pawelevans** [comment]
Thanks for your help, the examples are working fine.
I am looking to use remi to run a webserver on a device which will show sensor data such as digital inputs and also control digital outputs on another device via coap messages.  So for example, a browser selects an input which will direct the server to call a coap function to get the status from the device, and this status will automatically update the binary input status on the web page.  At first glance, Remi looks to be a viable solution and much simpler than for example Django/Ajax, do you agree?

**Comment by dddomodossola** [comment]
@pawelevans yes of course, you should be able to make a GUI for this with very few lines of code. You can also feel it simple to use the graphical editor. Here I am if you need help ;-)

**Comment by pawelevans** [comment]
graphical editor sounds great, is there a link for this or a guide on how to use this?
Thanks again for your help, much appreciated!
I am playing with examples that are there, but I would like to start one from scratch :-)

**Comment by dddomodossola** [comment]
Here is a link to the online version of the Editor https://remiguieditor.daviderosa.repl.co/
It could apper to be slow, for a comfortable use you can download the entire Remi repository, the editor is a subfolder. 
If you want to start from scratch, copy and paste the "template_app.py" script, it would be a good start point.

**Comment by pawelevans** [comment]
That's really great help, thank you  I will try it now!

**Comment by pawelevans** [comment]
Hi, I have opened up the editor in both Chrome and Firefox.  I am unable to move or resize the widget using the arrows around the widget, or by grabbing the widget and moving it.  Any ideas?

**Comment by dddomodossola** [comment]
The tutorial is a bit outdated. In the new Editor version you can set all widgets properties (also the name and label content) by the panel on the right side.
The cloned version does not work because you are using the Editor from the GitHub master branch (most updated) and the remi version on pypi (stable and older). You should download the older Editor (from here https://github.com/dddomodossola/remi/tree/2020.1.16) or install a most updated remi version from the GitHub master branch (download the repository and run the **python setup.py --install**)

**Comment by pawelevans** [comment]
Thanks again for that! I managed to get a basic container set up with a couple of labels and buttons.
The button however is not updating the label.
Sorry for all the questions!

python3 myFirstApp.py 
remi.server      INFO     Started httpserver http://0.0.0.0:8081/
remi.request     INFO     built UI (path=/)
127.0.0.1 - - [05/Feb/2020 11:22:49] "GET / HTTP/1.1" 200 -
remi.server.ws   INFO     connection established: ('127.0.0.1', 51804)
remi.server.ws   INFO     handshake complete
remi.server.ws   ERROR    error parsing websocket
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/remi-2020.2.5-py3.5.egg/remi/server.py", line 261, in on_message
    callback(**param_dict)
  File "/usr/local/lib/python3.5/dist-packages/remi-2020.2.5-py3.5.egg/remi/gui.py", line 169, in __call__
    return self.callback(self.event_source_instance, *callback_params, **self.kwuserdata)
  File "myFirstApp.py", line 123, in onclick_input0GetValue
    self.container0.children['input0label'].set_text('Hello Input1!')
KeyError: 'input0label'

The code:
...
        input0Label.variable_name = "input0Label"
        container0.append(input0Label,'input0Label')
        input1Label = Label()
        input1Label.attr_editor_newclass = False
        input1Label.css_height = "30px"
        input1Label.css_left = "375.0px"
        input1Label.css_margin = "0px"
        input1Label.css_position = "absolute"
        input1Label.css_top = "210.0px"
        input1Label.css_width = "100px"
        input1Label.text = ""
        input1Label.variable_name = "input1Label"
        container0.append(input1Label,'input1Label')
        container0.children['input0GetValue'].onclick.do(self.onclick_input0GetValue)
        container0.children['input1GetValue'].onclick.do(self.onclick_input1GetValue)


        self.container0 = container0
        return self.container0

    def onclick_input0GetValue(self, emitter):
        self.container0.children['input0label'].set_text('Hello Input1!')

    def onclick_input1GetValue(self, emitter):
        self.container0.children['input1label'].set_text('Hello Input1!')



#Configuration
configuration = {'config_start_browser': True, 'config_port': 8081, 'config_address': '0.0.0.0', 'config_project_name': 'untitled', 'config_multiple_instance': True, 'config_enable_file_cache': True, 'config_resourcepath': './res/'}

if __name__ == "__main__":
    # start(MyApp,address='127.0.0.1', port=8081, multiple_instance=False,enable_file_cache=True, update_interval=0.1, start_browser=True)
    start(untitled, address=configuration['config_address'], port=configuration['config_port'],
                        multiple_instance=configuration['config_multiple_instance'],
                        enable_file_cache=configuration['config_enable_file_cache'],
                        start_browser=configuration['config_start_browser'])

**Comment by dddomodossola** [comment]
Don't be worried to ask, it is a pleasure to be helpful.
There is an error in your code. You written:
`self.container0.children['input0label'].set_text('Hello Input1!')`
But it should be:
`self.container0.children['input0Label'].set_text('Hello Input1!')`

in this text 'input0Label' you written lower case **L** instead of upper case

**Comment by pawelevans** [comment]
Once again, that's a great help, also with the additional note, thank you very much!!!  I am enjoying use this gui tool and learning remi & python.
I don't seem to be able to stay on the button context in the gui to change something, as the context keeps switching away.  Perhaps I should open a new thread for each issue now I have got going. :-)

**Comment by dddomodossola** [comment]
What you mean with "I don't seem to be able to stay on the button context in the gui to change something, as the context keeps switching away." ?

**Comment by dddomodossola** [comment]
**IMPORTANT NOTE** I suggest you to first design and draw the entire GUI, and than change the code manually to develop the app logic. 
This is because, when you open again a modified code with the editor, you can lost changes made manually. The editor is an automatic system and isn't able to maintain all your changes.

**Comment by pawelevans** [comment]
I see, I will do it this way, thanks again :)

**Comment by dddomodossola** [comment]
I understand, maybe it's a bug of the new version. You can select the button also from the list in the upper right panel, it should work

**Comment by dddomodossola** [comment]
Bug fixed, thank you so much for reporting. If you download the most updated editor the button selection should now work.

**Comment by pawelevans** [comment]
Could you tell me which is the best way to display a digital input or output status.  I basically want an LED or a small box to turn green or red to reflect the state.  Should I use some widget or an image?

**Comment by dddomodossola** [comment]
Of course there are different possible solution, you can use a label or a button giving them a rounded corner.
My preferred solution is to use Svg. Put an Svg widget and an SvgCircle inside it. The svg circle can be filled with different color in case of active or unactive status.

**Comment by pawelevans** [comment]
Thank you this is really nice, I will try the Svg widget.  Is there any documentation on how to use this, or should I go through all the examples to see if there is one being used?

**Comment by dddomodossola** [comment]
Give it a try with the Editor, put an Svg widget and than, inside it, an SvgCircle. Unfortunately there is no documentation. If you find it difficult I can prepare an example.

**Comment by pawelevans** [comment]
I have done that, but I get the following error:
  File "myFirstApp.py", line 210, in onclick_input0GetValue
    svgcircle0.set_fill('green')
NameError: name 'svgcircle0' is not defined

This is the code, generated by gui with a few amendments when clicking buttons (I am new to python :-) )
        svgcircle0.variable_name = "svgcircle0"
        svgInput0.append(svgcircle0,'svgcircle0')
        container0.append(svgInput0,'svgInput0')
        container0.children['input0Create'].onclick.do(self.onclick_input0Create)
        container0.children['input0GetValue'].onclick.do(self.onclick_input0GetValue)
        container0.children['moduleGetTime'].onclick.do(self.onclick_moduleGetTime)
        container0.children['input1Create'].onclick.do(self.onclick_input1Create)
        container0.children['input1GetValue'].onclick.do(self.onclick_input1GetValue)


        self.container0 = container0
        return self.container0

    def onclick_input0Create(self, emitter):
        pass
    def onclick_input0GetValue(self, emitter):
        self.container0.children['input0Label'].set_text('Hello Input0')
        svgcircle0.set_fill('green')
    def onclick_moduleGetTime(self, emitter):
        client = HelperClient(server=("192.168.0.120", 5683))
        response = client.get("/time")
        if response is not None:
            self.container0.children['moduleLabel'].set_text(response.payload)
        client.stop()
    def onclick_input1Create(self, emitter):
        pass
    def onclick_input1GetValue(self, emitter):
        self.container0.children['input1Label'].set_text('Hello Input1')

**Comment by dddomodossola** [comment]
svgcircle0 has limited scope in the **main**. You should assign svgcircle0 as class member in the main function:

`self.svgcircle0 = svgcircle0`

later you can do:
```
def onclick_input0GetValue(self, emitter):
    self.container0.children['input0Label'].set_text('Hello Input0')
    self.svgcircle0.set_fill('green')
```

look that I used **self.svgcircle0** instead of **svgcircle0**

**Comment by pawelevans** [comment]
perfect!!!!!! 
thank you

**Comment by dddomodossola** [comment]
;-)

**Comment by pawelevans** [comment]
making nice progress!!! :-) I am assigning a text field for the user to enter (hopefully) a valid IP address, which I then want to use to send COAP messages out to this device.  So far I have:

   def onchange_ipaddress(self, emitter, new_value):
        pass

    def onclick_input1GetValue(self, emitter):
        self.container0.children['input1Label'].set_text('Hello Input1')
        self.svgled1.set_fill('green')

    def onclick_input0Create(self, emitter):
        self.svgled0.set_fill('red')

    def onclick_moduleGetTime(self, emitter):
        client = HelperClient(server=("192.168.0.120", 5683))
        response = client.get("/time")
        if response is not None:
            self.container0.children['moduleLabel'].set_text(response.payload)
        client.stop()    

Should I save the new_value in the method onchange_ipaddress to a global variable to use later in the call to HelperClient instead of the hard coded IP address?

**Comment by dddomodossola** [comment]
Not necessarly. The event can be used for different purposes. In your case the event is not required, 
you can do `ipaddress.get_value()` where you need to get the ipaddress value.

**Comment by pawelevans** [comment]
thanks for that, I'm not quite getting it though.  Are you saying I don't need the onchange_ipaddress event?  I want to allow the user to enter any IP into a text widget.  So am I correct in saying, just do for example something like:
client = HelperClient(server=(ipaddress.get_value(targetip), 5683)) - targetip being the text widget

**Comment by pawelevans** [comment]
Thank you once again :-)

**Comment by pawelevans** [comment]
another question if you don't mind ;-)
I am getting this error on trying parse a json response and display it on the screen:

remi.server      INFO     Started httpserver http://0.0.0.0:8081/
remi.request     INFO     built UI (path=/)
127.0.0.1 - - [06/Feb/2020 16:19:11] "GET / HTTP/1.1" 200 -
remi.server.ws   INFO     connection established: ('127.0.0.1', 59462)
remi.server.ws   INFO     handshake complete
remi.server.ws   ERROR    error parsing websocket
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/remi-2020.2.5-py3.5.egg/remi/server.py", line 261, in on_message
    callback(**param_dict)
  File "/usr/local/lib/python3.5/dist-packages/remi-2020.2.5-py3.5.egg/remi/gui.py", line 169, in __call__
    return self.callback(self.event_source_instance, *callback_params, **self.kwuserdata)
  File "myFirstApp.py", line 285, in onclick_input0GetValue
    self.container0.children['input0Label'].set_text(state)
  File "/usr/local/lib/python3.5/dist-packages/remi-2020.2.5-py3.5.egg/remi/gui.py", line 2097, in set_text
    self.add_child('text', escape(text, quote=False))
  File "/usr/lib/python3.5/html/__init__.py", line 19, in escape
    s = s.replace("&", "&amp;") # Must be done first!
AttributeError: 'bool' object has no attribute 'replace'

This is the relevant code:
   def onclick_input0GetValue(self, emitter):
        client = HelperClient(server=(self.ipaddress.get_value(), 5683))
        response = client.get("/inputs/0/status")
        if response is not None:
            json_str = json.dumps(response.payload)
            resp = json.loads(response.payload)
            state = resp['state']
            self.container0.children['input0Label'].set_text(state)
            if state == "true" :
                self.svgled0.set_fill('green')
            else :
                self.svgled0.set_fill('red')
        client.stop()

**Comment by dddomodossola** [comment]
When you set the content of a label you have to set a **string**. You are instead setting a **bool**. You should do:

self.container0.children['input0Label'].set_text( **str(** state **)** )

**Comment by pawelevans** [comment]
You are a star, thank you!!!!!!!!

**Comment by pawelevans** [comment]
Hi, I want to use a button widget which has the label text 'SET' and when the button is pressed the button shows 'CLEAR'.  Is this possible as it will be better than having two separate buttons?
Thanks.

**Comment by dddomodossola** [comment]
Of course, in the event listener onclick of button you can do mybutton.set_text("CLEAR")

**Comment by pawelevans** [comment]
super! ...and then clicking whilst it is set to 'CLEAR' will go back to 'SET'?

**Comment by dddomodossola** [comment]
You have to store the information in a boolean flag, and decide if to show SET or CLEAR with an if statement

**Comment by pawelevans** [comment]
that's great, thanks once again!

**Comment by pawelevans** [comment]
is it possible to also change the background_color on click of button, I can see it's set with css_background_color on initialisation but not a method to set it after?

**Comment by dddomodossola** [comment]
you can do it in the onclick event handler  the same way as initialization:

    mybutton.css_background_color = "rgb(255,200,0)" #values are respectively Red,Green,Blue

**Comment by pawelevans** [comment]
thanks, I did it that way initially but it didn't work so thought there may be another means to do it, I will try again and see where my mistake is

**Comment by pawelevans** [comment]
strange that I change the position of it with self.myButton.set_css_top = "200" and the button moved on click, but not the color despite setting it to rgb(255.255.255)

**Comment by dddomodossola** [comment]
are you using dot "." or comma "," to separate values ? it must be "," comma

**Comment by pawelevans** [comment]
yes definitely comma, I literally copied it from the initialisation and just changed the RGB value

**Comment by dddomodossola** [comment]
try with this:

```
# -*- coding: utf-8 -*-

from remi.gui import *
from remi import start, App


class untitled(App):
    def __init__(self, *args, **kwargs):
        #DON'T MAKE CHANGES HERE, THIS METHOD GETS OVERWRITTEN WHEN SAVING IN THE EDITOR
        if not 'editing_mode' in kwargs.keys():
            super(untitled, self).__init__(*args, static_file_path={'my_res':'./res/'})

    def idle(self):
        #idle function called every update cycle
        pass
    
    def main(self):
        return untitled.construct_ui(self)
        
    @staticmethod
    def construct_ui(self):
        #DON'T MAKE CHANGES HERE, THIS METHOD GETS OVERWRITTEN WHEN SAVING IN THE EDITOR
        vbox0 = VBox()
        vbox0.attr_editor_newclass = False
        vbox0.css_align_items = "center"
        vbox0.css_display = "flex"
        vbox0.css_flex_direction = "column"
        vbox0.css_height = "250px"
        vbox0.css_justify_content = "space-around"
        vbox0.css_left = "20px"
        vbox0.css_margin = "0px"
        vbox0.css_position = "absolute"
        vbox0.css_top = "20px"
        vbox0.css_width = "250px"
        vbox0.variable_name = "vbox0"
        button0 = Button()
        button0.attr_editor_newclass = False
        button0.css_height = "30px"
        button0.css_margin = "0px"
        button0.css_order = "140121714029184"
        button0.css_position = "static"
        button0.css_top = "20px"
        button0.css_width = "100px"
        button0.text = "PRESS ME"
        button0.variable_name = "button0"
        vbox0.append(button0,'button0')
        vbox0.children['button0'].onclick.do(self.onclick_button0)
        
        self.button0 = button0
        self.vbox0 = vbox0
        return self.vbox0
    
    def onclick_button0(self, emitter):
        self.button0.css_background_color = "rgb(255,200,0)"
        self.button0.set_text("PRESSED")



#Configuration
configuration = {'config_project_name': 'untitled', 'config_address': '0.0.0.0', 'config_port': 8081, 'config_multiple_instance': True, 'config_enable_file_cache': True, 'config_start_browser': True, 'config_resourcepath': './res/'}

if __name__ == "__main__":
    # start(MyApp,address='127.0.0.1', port=8081, multiple_instance=False,enable_file_cache=True, update_interval=0.1, start_browser=True)
    start(untitled, address=configuration['config_address'], port=configuration['config_port'], 
                        multiple_instance=configuration['config_multiple_instance'], 
                        enable_file_cache=configuration['config_enable_file_cache'],
                        start_browser=configuration['config_start_browser'])
```

**Comment by pawelevans** [comment]
Thank you for that, yes it worked of course. I will compare what I have and hopefully it will become obvious :)

**Comment by pawelevans** [comment]
Your button also worked in my container, it was a typo, I had changed css bit to set when checking if there was a set function for color......and forgot to change it back, thanks for your help and sorry to waste your time

**Comment by dddomodossola** [comment]
you are welcome ;-)

**Comment by pawelevans** [comment]
hello again, I am sending a chunk of text which has linefeeds - to label using the set_text method
however, the newlines are not in the output
is there a way to achieve?
thanks!

**Comment by dddomodossola** [comment]
Hello @pawelevans . You have to use:

    mylabel.css_white_space = "pre"

and it will work.

**Comment by pawelevans** [comment]
thanks so much! :+1:
