### ISSUE TITLE
GUI Editor can't keep focus on instances list items and button

### ISSUE THREAD

**Issue by DaddyOh** [dddomodossola/remi#360]
2020.2.5 version of editor and remi

I'm new at this so forgive me if I'm doing something wrong. I'm trying to extend the example in the editor README file. the following behavior is observed when I have added a text box to the container.

When I click on the button in the gui it does not keep focus so I can't move it or resize it.

The same is true for items in the Instances List.

Running on Chrome on a Mac v 10.13.6.

![image](https://user-images.githubusercontent.com/1836509/74175260-72a12e00-4c03-11ea-9bb1-800eaaf04df7.png)

Thanks for any hints on how to make this work.

**Comment by dddomodossola** [comment]
Hello @DaddyOh , thank you for reporting.
This appears to be a bug recently reported and fixed. I suggest you to download and try the most updated editor version on master branch. Please let me know if this solve the problem.

**Comment by DaddyOh** [comment]
Thanks.  That worked.
