### ISSUE TITLE
App.onpagehide not being called under certain conditions

### ISSUE THREAD

**Issue by bielaszewski** [dddomodossola/remi#365]
An app overrides App.onpagehide() ...

1) When the browser is on the same host as the remi,  the onpagehide is called as expected when the browser tab is closed.  ( FireFox on Linux )

2) When the browser is run on a separate host from remi, the onpagehide method is NOT being called when the browser tab is closed. ( Silk browser on a Kindle tablet).

Browser issue or remi?  I dont know.
 Update: I tried condition#2 with a laptop and onpagehide IS called when the remi tab is closed

The attached "issue reproducer" is based on examples/helloworld_app.py.   It overrides App.onpagehide with a method that prints a message and flushes stdout when called.
The socket package is used to find the host ip address before calling start()

.py file attached with .txt extension.  git hub weirdness
[onhide_bug.py.txt](https://github.com/dddomodossola/remi/files/4252547/onhide_bug.py.txt)

regards,
bielaszewski  (aka mtcabeza on reddit)

**Comment by bielaszewski** [comment]
Update: I tried condition#2 with a laptop and onpagehide IS called when the remi tab is closed.
That exhausts my supply of alternate hardware to try this on.
I AM ASSUMING IT IS SOME WEIRDNESS WITH THE SILK BROWSER ON KINDLE and will close the issue.

**Comment by dddomodossola** [comment]
@bielaszewski thank you for the further testing. Yes it have to be a problem with the kindle browser. Unfortunately I have not a kindle and so I can't throubleshoot. What you were trying to achieve with onpagehide?

**Comment by bielaszewski** [comment]
DR, sorry for the slow response, my github account needs an email address
update.   A lot of code has flowed under the bridge since this issue
cropped up.   I think i was going to use the pagehide event to inform other
views to update themselves.  My solution was to have all views share the
same data, which is cleaner.

FYI, I am using remi/ kindle browser as a touchscreen remote for
controlling a synthesizer stack running on a desktop.  This avoids 1)
having a keyboard and monitor on top of the midi keyboard and 2) avoids
swivling between computer keyboard and musical keyboard. Its coming along :)

I really enjoy working with Remi.  Reading your code is educational.!
Thanks for all your effort.  Longterm, i think REMI will be an important
python package.  For purely desktop apps i had been using PySimpleGui but
it does not seem ready for web browser use.

regards,
john bielaszewski (aka mtcabeza)
jjbielas@protonmail.com
Sedona, AZ

**Comment by dddomodossola** [comment]
Thank you a lot @bielaszewski ! I'm happy you are appreciating remi. About PySimpleGUI, it is improved day by day, is a really good alternative ;-)

When you get your project done, please share some screenshot. Have a good work !
