### ISSUE TITLE
Unicode Characters not working anymore

### ISSUE THREAD

**Issue by Counterdoc** [dddomodossola/remi#366]
Hi @dddomodossola ,

I just tested an old application (2 years) that I wrote using REMI. I am using a fresh installation with REMI now, but I recognized that unicode characters are not being displayed correct anymore. 

For example for temperatures when using `&deg; C`

It was working fine in the past. I just tested it with a simple html page and it works. So no browser issue. 

Thanks
Marius

**Comment by dddomodossola** [comment]
Hello @Counterdoc ,
You should use the special character ° instead.
Regards

**Comment by Counterdoc** [comment]
That was easy... it works! Thank you for the quick help.
