### ISSUE TITLE
TabBox  Formatting 

### ISSUE THREAD

**Issue by mtcabeza** [dddomodossola/remi#368]
When adding to a TabBox,   certain tab counts will cause a second row of tabs to be created.
For example tab boxes containing 6 and 7 tabs exhibit this issue. 
It appears to be due to float calculations f in TabBox.resize_tab_titles() causing the total width of all tabs to get slightly > 100%

The attached program demonstates the issue.  It takes an int on the command line which tells it how many tabs to create.  (.txt extension is for github weirdness).

[tabbox_v2.py.txt](https://github.com/dddomodossola/remi/files/4314351/tabbox_v2.py.txt)

**Comment by mtcabeza** [comment]
Here is a screenshot of the layout defect.  Tab#6 is in a second row of tabs.
![tab_layout_defect_screenshot](https://user-images.githubusercontent.com/3891556/76533431-47de0b80-6435-11ea-8c29-69ffaa4af92e.png)

Here is the mythical one line change that i applied to my local copy of gui.py
to fix it.   

[tab_layout_defect_screenshot-hack.txt](https://github.com/dddomodossola/remi/files/4324785/tab_layout_defect_screenshot-hack.txt)

**Comment by dddomodossola** [comment]
@mtcabeza thank you! I will look into this soon. Excuse for the late reply, it's a busy period

**Comment by mtcabeza** [comment]
No rush.  I have patched my local copy of gui.py.  I was just adding info that should have been provided with the original issue. Regards!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
