### ISSUE TITLE
Problems with asciiart of sub-widget

### ISSUE THREAD

**Issue by Eothred** [dddomodossola/remi#369]
I am not sure if this is correct use of the API or not, but at least my code seem to not correctly make use of set_from_asciiart(). I have made a somewhat minimal example below:

```python
import remi.gui as gui
from remi import start, App

class MyApp(App):

    def main(self):
        self.config = gui.GridBox(width='100%', height='100%', style={'margin': '0px auto'})
        self.main_widget = gui.TabBox(width='100%', height='100%')
        # A grid for the configuration tab
        self.config.set_from_asciiart("""
                        |label1  |           |
                        |        |           |
                        |label2  | label3    |
                        """, 1, 1)

        mydict = {}
        for i in range(5):
            mydict[f'label{i}'] = gui.Label(f'label{i}')

        self.config.append(mydict)
        self.main_widget.add_tab(self.config, 'Config', None)


        return self.main_widget

if __name__ == "__main__":
    start(MyApp, title="My App", debug=True)

```

Now I am expecting to see the three labels according to the layout defined in the asciiart, but instead I just get a vertical list of the 5 labels in the dictionary. Am I misunderstanding something?

My colleague Emanuele found a work-around by putting the config widget inside another widget.

**Comment by dddomodossola** [comment]
Hello @Eothred, thank you a lot for reporting. The TabBox widget forces the css 'display' attribute of the appended widgets. This causes that GribBox (that must have 'display':'grid') gets the attribute set to 'block'. This causes wrong layouting. 
The solution is to append the gridbox to a container, and then, the container to the tabbox.
The widgets tree would be:
    
    TabBox
        Container
            GridBox

Regards
