### ISSUE TITLE
[Question] how to make a disabled object and enable later

### ISSUE THREAD

**Issue by m-kareem** [dddomodossola/remi#373]
Hi Davide, all,

Thanks once again for your kind support. I will ask my questions here in git repo from now on as you have advices, rather than reddit.

I am trying to build a web-based GUI with Remi, similar to this dummy one that I have built with “QT for WebAssembly": http://petra.phys.yorku.ca:5000

1) I need some objects to be initially grayed out, and upon the user's action, get enabled. I tried attributes['disabled'] = 'True' for the object I want to disable but it did not work. Perhaps I am doing something incorrectly.
A simple example of a disabled button which gets enabled / disabled with a checkbox object would be very much helpful.

2) As you can see, there are two tabs at the top in my dummy QT example. What is the easiest way to make something similar with remi?

Thanks,

**Comment by dddomodossola** [comment]
Hello @m-kareem , here is an example for you

```python
# -*- coding: utf-8 -*-

from remi.gui import *
from remi import start, App


class untitled(App):
    def __init__(self, *args, **kwargs):
        #DON'T MAKE CHANGES HERE, THIS METHOD GETS OVERWRITTEN WHEN SAVING IN THE EDITOR
        if not 'editing_mode' in kwargs.keys():
            super(untitled, self).__init__(*args, static_file_path={'my_res':'./res/'})

    def idle(self):
        #idle function called every update cycle
        pass
    
    def main(self):
        return untitled.construct_ui(self)
        
    @staticmethod
    def construct_ui(self):
        #DON'T MAKE CHANGES HERE, THIS METHOD GETS OVERWRITTEN WHEN SAVING IN THE EDITOR
        container0 = Container()
        container0.attr_editor_newclass = False
        container0.css_height = "90.0px"
        container0.css_left = "20px"
        container0.css_position = "absolute"
        container0.css_top = "20px"
        container0.css_width = "300.0px"
        container0.variable_name = "container0"
        checkbox0 = CheckBox()
        checkbox0.attr_editor_newclass = False
        checkbox0.css_height = "30px"
        checkbox0.css_left = "30.0px"
        checkbox0.css_position = "absolute"
        checkbox0.css_top = "30.0px"
        checkbox0.css_width = "30px"
        checkbox0.variable_name = "checkbox0"
        container0.append(checkbox0,'checkbox0')
        self.button0 = Button()
        self.button0.attr_editor_newclass = False
        self.button0.css_height = "30px"
        self.button0.css_left = "120.0px"
        self.button0.css_position = "absolute"
        self.button0.css_top = "30.0px"
        self.button0.css_width = "100px"
        self.button0.text = "button"
        self.button0.variable_name = "button0"
        container0.append(self.button0,'button0')
        container0.children['checkbox0'].onchange.do(self.onchange_checkbox0)
        

        self.container0 = container0
        return self.container0
    
    def onchange_checkbox0(self, emitter, value):
        self.button0.set_enabled(value)



#Configuration
configuration = {'config_project_name': 'untitled', 'config_address': '0.0.0.0', 'config_port': 8081, 'config_multiple_instance': True, 'config_enable_file_cache': True, 'config_start_browser': True, 'config_resourcepath': './res/'}

if __name__ == "__main__":
    # start(MyApp,address='127.0.0.1', port=8081, multiple_instance=False,enable_file_cache=True, update_interval=0.1, start_browser=True)
    start(untitled, address=configuration['config_address'], port=configuration['config_port'], 
                        multiple_instance=configuration['config_multiple_instance'], 
                        enable_file_cache=configuration['config_enable_file_cache'],
                        start_browser=configuration['config_start_browser'])
```

For the tabs, use the TabBox widget.

Regards ;-)

**Comment by m-kareem** [comment]
Thanks a lot Davide for your prompt response.
When I disable a dropdown object, it is not getting grayed out, but it is correctly bing disabled. Is it a known issue?

One more quick question. How do I make a solid line border around a container. I guess it should be via style when defining the container like:
gui.Container(width=400, layout_orientation=gui.Container.LAYOUT_HORIZONTAL, style={'display': 'block', 'overflow': 'auto', 'text-align': 'left'})

But I don't know the keyword. Is it documented somewhere?

Thanks

**Comment by m-kareem** [comment]
Hi @dddomodossola ,

I also found out that the **checkbox** object is not getting disabled. Is there any other method for disabling it, or it is not supported yet in remi?

Thanks,

**Comment by dddomodossola** [comment]
In order to disable a Checkbox:
mycheckbox.set_enabled(False)

In order to disable a CheckboxLabel:
mycheckboxlabel._checkbox.set_enabled(False)

In order to disable a container:
mycontainer.style['pointer-events'] = 'none'
mycontainer.style['opacity'] = '0.4' #this is to give a disabled apparence

Regards ;-)

**Comment by m-kareem** [comment]
Thanks @dddomodossola  for your kind support.

In order to re-enable the container, shall I do:
**del subContainerMiddle_2.style['pointer-events']**

or there is a more proper way to do this.

And by the way, where all these things are documented? I could not find it in the "Remi Documentation Release 1.0.0". Is there any more up-to-date one?

Best,

**Comment by dddomodossola** [comment]
Hello @m-kareem that's the right way. However unfortunately there is no documentation about this. There is only the readme file and the example. And of course you can ask me for help. ;-)
