### ISSUE TITLE
[Question] how to draw a border around a container

### ISSUE THREAD

**Issue by m-kareem** [dddomodossola/remi#375]
Hi @dddomodossola , all,

I am wondering if there is any way to make a border around containers?
I tried to use style={'border': '2px'} in the object definition, but it is just being ignored. Perhaps I am missing something

Thanks,

**Comment by dddomodossola** [comment]
Hello @m-kareem ,
The border definition have to be like this:
style={'border':'2px solid black'}
and it will work ;-)
