### ISSUE TITLE
[Question] set_text method for gui.Table

### ISSUE THREAD

**Issue by m-kareem** [dddomodossola/remi#376]
Hi @dddomodossola,

thanks again for your kind support. Indeed I am making great progress in my project with your help and support.

I have the following question:
I have a realtime data coming from an SQL database in every update cycle. I would like to have a dynamic table (each cell value gets updated in every update cycle).
I can do this via labels, defining the label in the **main(self)** e.g.:
**self.Sens_T_1 = gui.Label('',width=200, height=30, margin='10px')**

 and setting new text in idle() function, e.g.:
**self.Sens_T_1.set_text('Temperatue[C]: ' + str(get_Temperatur()))**

Is there any way to do same thing with a table's cell?

Regards,

**Comment by m-kareem** [comment]
Sorry for the spam, I guess I found a useful example here:
https://github.com/dddomodossola/remi/issues/321#issuecomment-504353981

**Comment by dddomodossola** [comment]
No problem ;-)
