### ISSUE TITLE
TabBox in OSX

### ISSUE THREAD

**Issue by Eothred** [dddomodossola/remi#384]
I wrote the following test app (a minimal version of my full app that still shows our issue):

```python
import remi.gui as gui
from remi import start, App
class MyApp(App):
    def main(self):
        self.main_widget = gui.TabBox(width="100%", height="100%")
        self.tab_scan = gui.VBox(width="100%", height="100%", style={"margin": "0px auto"})
        self.tab_scan.append(gui.Button("Run scan", width=200, height=30, margin="10px"))
        self.tab_scan.append(gui.Button("Load scan", width=200, height=30, margin="10px"))
        self.main_widget.add_tab(gui.Container(children=[self.tab_scan]), "Run scan", None)
        return self.main_widget
if __name__ == "__main__":
    start(MyApp)
```
Now this seems to work just fine on my computer (4 browsers tested), but on my colleagues OSX box, the buttons are overflowing the tabs if she use Firefox or Chrome. Safari shows the layout as expected. Screenshot below shows left to right, Firefox, Safari, and Chrome:
![Test_differentBrowsers](https://user-images.githubusercontent.com/187567/81038226-93e18580-8ea5-11ea-9259-3ba68a944b21.png)

I found issue #368 somewhat related but I think this is different so I opened a separate report.

**Comment by Eothred** [comment]
No need to write an example apparently. My colleague also tested the `examples/tabbox.py` from the remi repository. It has the same problem.

**Comment by dddomodossola** [comment]
Hello @Eothred, 
Unfortunately I have no OSX devices to test this. However looking at the images (thank you for providing) I can see that the tab title expands to the bottom. It seems strange. 
Can you please inspect the webpage and look for css margins? Maybe the remi css is not so strictly defined, permitting some browsers to freely define some parameters.

**Comment by natalia-milas** [comment]
Hi, so we managed to narrow down the issue a bit. Sorry because I won't be able to explain it super professionally but it is connect to javascript missing (or "forgetting") some layout settings when creating the page.  We could get everything working when openning the html file and fixing by hand (basically settign the element height to "auto" instead of 100%) but the problem would show up again once we re-run the script. One way to solve the tab size issue was to remove the Container from the Tabbox (originally it had TabBox->Container-> GridBox). Although it fixes the tab the final result was that now the widgets inside the TabBox get messed up instead and all flushed left (I think this is covered in #369). I am still tryng to fix it in some other way and I get back if I find anything useful.

**Comment by dddomodossola** [comment]
Hello @natalia-milas thank you a lot for helping fix this issue. 
So, you modified html changing element height from '100%' to 'auto'. Wonderful. But of course reloading the page it refreshes and the error appears again.

Basically we need to change the remi css. By default a script loads the standard remi css, but there is a way to define a different css file allowing to customize the application (and in this case fix css issues).

I can prepare a corrected css for you. Can you give me a printscreen of the corrected html? Because otherwise I can't understand the specific element involved in the problem.

**Comment by natalia-milas** [comment]
So here is everything I coudl collect (tell me if you need more, I can run it no problems!)

Images here are the same scrip before and after I changed the height parameters (which I am not 100% sure to which elements it belowngs, but I highlighted it with the red box).
![Before](https://user-images.githubusercontent.com/29061953/82057667-fc114200-96c3-11ea-894d-c758703b067a.png)
![After](https://user-images.githubusercontent.com/29061953/82057675-fe739c00-96c3-11ea-81eb-9a366a9632b9.png)

**Comment by natalia-milas** [comment]
I am also uploading the code that does work without changes (modification of the test script @Eothred  poster when he opened the issue) but showing the flushed left buttons.
`import remi.gui as gui
from remi import start, App
class MyApp(App):
    def main(self):
        self.main_widget = gui.TabBox(width="100%", height="auto")

        button_run = gui.Button("Run scan", width=200, height=30, margin="10px")
        button_scan = gui.Button("Load scan", width=200, height=30, margin="10px")
        vbox_buttons = gui.VBox(width="100%", height="auto", style={"margin": "0px auto"})
        vbox_buttons.append(button_run)
        vbox_buttons.append(button_scan)

        self.main_widget.add_tab(vbox_buttons, "Run scan", None)
        return self.main_widget
if __name__ == "__main__":
    start(MyApp)
`



![Screen Shot 2020-05-15 at 15 45 52](https://user-images.githubusercontent.com/29061953/82057823-34188500-96c4-11ea-8a3b-12091c628bb6.png)

**Comment by dddomodossola** [comment]
Perfect information reporting. I found that the 'height:100%' is hardcoded in remi. Can you please try the following code?

```python
import remi.gui as gui
from remi import start, App

class CustomTabBox(gui.TabBox):
    def resize_tab_titles(self):
        tab_w = 100.0 / len(self.container_tab_titles.children.values())
        for l in self.container_tab_titles.children.values():
            l.css_width = "%.1f%%" % tab_w
            l.css_height = "auto"

class MyApp(App):
    def main(self):
        self.main_widget = CustomTabBox(width="100%", height="100%", _class="TabBox")
        self.tab_scan = gui.VBox(width="100%", height="100%", style={"margin": "0px auto"})
        self.tab_scan.append(gui.Button("Run scan", width=200, height=30, margin="10px"))
        self.tab_scan.append(gui.Button("Load scan", width=200, height=30, margin="10px"))
        self.main_widget.add_tab(gui.Container(children=[self.tab_scan]), "Run scan", None)
        return self.main_widget

    
if __name__ == "__main__":
    start(MyApp)
``` 

If confirmed I will update remi to fix the issue. 

Thank you in advance.

**Comment by natalia-milas** [comment]
Hi Davide,

So the ne you sent did not work. However I played around a bit and with a small modification (below) I managed to get it going:

import remi.gui as gui
from remi import start, App

class CustomTabBox(gui.TabBox):
    def resize_tab_titles(self):
        tab_w = 100.0 / len(self.container_tab_titles.children.values())
        for l in self.container_tab_titles.children.values():
            l.set_size("%.1f%%" % tab_w, "auto")


class MyApp(App):
    def main(self):
        self.main_widget = CustomTabBox(width="100%", height="100%", _class="CustomTabBox")
        self.tab_scan = gui.VBox(width="100%", height="100%", style={"margin": "0px auto"})
        self.tab_scan.append(gui.Button("Run scan", width=200, height=30, margin="10px"))
        self.tab_scan.append(gui.Button("Load scan", width=200, height=30, margin="10px"))
        self.main_widget.add_tab(gui.Container(children=[self.tab_scan]), "Run scan", None)
        self.main_widget.resize_tab_titles()
        return self.main_widget

if __name__ == "__main__":
    start(MyApp)

And here is how it looks like (the layout of the whole things changes a bit and I am not sure why)

![Screen Shot 2020-05-18 at 08 58 02](https://user-images.githubusercontent.com/29061953/82183367-1f1b3c00-98e6-11ea-85ca-afb778689704.png)

**Comment by natalia-milas** [comment]
I also went and looking into the TabBox implementation itself and I think if you change on line 1675 on the code itself:
from: l.set_size("%.1f%%" % tab_w, "100%") 
to : l.set_size("%.1f%%" % tab_w, "auto")

shoudl fix the problem and not change the whole layout. Here is the result!

![Screen Shot 2020-05-18 at 09 02 17](https://user-images.githubusercontent.com/29061953/82183569-86d18700-98e6-11ea-9358-056585d52a36.png)

**Comment by dddomodossola** [comment]
Modified remi according to the proposed solution. Thank you a lot @natalia-milas and @Eothred ;-)

**Comment by Eothred** [comment]
Thanks both for following up on this! I close as I understood from Natalia that it works now. I also checked that this did not cause any issues on my existing environment.
