### ISSUE TITLE
Editor not working?A ttributeError: module 'remi.gui' has no attribute 'Container'

### ISSUE THREAD

**Issue by giacomomarchioro** [dddomodossola/remi#385]
Thanks for the amazing tool.
I am trying to use the editor using this command in OSX 10.11.3 Python 3.6.8, but I got the following error:

```
In [8]: %run editor/editor.py                                                   
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/Desktop/remi/editor/editor.py in <module>
     21 try:
     22     import prototypes
---> 23     import editor_widgets
     24 except ImportError:
     25     from . import prototypes

~/Desktop/remi/editor/editor_widgets.py in <module>
     88 
     89 
---> 90 class ToolBar(gui.Container):
     91     def __init__(self, **kwargs):
     92         super(ToolBar, self).__init__(**kwargs)

AttributeError: module 'remi.gui' has no attribute 'Container'
```

Thanks for your help!

**Comment by dddomodossola** [comment]
Hello @giacomomarchioro ,
Maybe you have installed an older remi version. Try to update it and run the editor again.
Verify that you are installing remi on the same python version that you are using to run the editor.
Please let me know if this works for you ;-)

**Comment by giacomomarchioro** [comment]
Hi, thanks for the quick reply. I can't find the remi.__version__ attribute but I've re-installed and also try to clone and make it run from the folder or some conflict with other version of remi gui installed previously. I'll let you know if I manage to solve the issues thanks again.

**Comment by dddomodossola** [comment]
You are welcome ✌️

**Comment by dddomodossola** [comment]
@giacomomarchioro Have you fixed the problem? How is it going?

**Comment by giacomomarchioro** [comment]
I removed everything, I tested again today and used the project download folder. Now it works. Thanks again for the tool. Best regards!
