### ISSUE TITLE
[Question / Enhancement] Have each web browser tab from one user create a separate instance

### ISSUE THREAD

**Issue by jimbob88** [dddomodossola/remi#386]
# The concept
For example, let's take the [session_app.py](https://github.com/dddomodossola/remi/blob/master/examples/session_app.py) example.

When first opening it, it looks like so:
![image](https://user-images.githubusercontent.com/9913366/81430962-46d90a00-9158-11ea-936c-b920c62232e7.png)

And in the log we see:

```
127.0.0.1 - - [08/May/2020 18:17:50] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [08/May/2020 18:17:50] "GET /res:style.css HTTP/1.1" 200 -
remi.server.ws   INFO     connection established: ('127.0.0.1', 52596)
remi.server.ws   INFO     handshake complete
```

And after login it looks like so:
![image](https://user-images.githubusercontent.com/9913366/81431005-548e8f80-9158-11ea-8de6-7b1cdf9fdd88.png)

Now that is all really good; however, if we open a new tab connecting to the same server (http://127.0.0.1:52591/), we get a new connection established in the log:

```
127.0.0.1 - - [08/May/2020 18:17:51] "GET /res:font.woff2 HTTP/1.1" 200 -
127.0.0.1 - - [08/May/2020 18:19:07] "GET / HTTP/1.1" 200 -
remi.server.ws   INFO     connection established: ('127.0.0.1', 52653)
remi.server.ws   INFO     handshake complete
```

Now the good thing about this connection is the fact it remembers the fact we are logged in:
![image](https://user-images.githubusercontent.com/9913366/81431210-b3540900-9158-11ea-8abf-8f1b66a0bf22.png)

My issue is the fact, if we press the "RENEW BEFORE EXPIRATION" button, the second tab changes its label -> "RENEW", which is expected; however, the first tab also changes to "RENEW".

I personally believe there should be an option available where these two tabs are differentiated by their data values but the login is carried between them.

# Another example

Let's take my `wheelers-wort-works-online` program as an example!

If we open 2 tabs of [it](https://wheelers-wort-works-online--jimbob88.repl.co/), and in the first one change the `recipe name` value, the recipe name input box changes in both tabs.

It would be nice to be able to change values in one tab, and then see that change only in that one tab.

Thanks very much,

James

**Comment by dddomodossola** [comment]
Hello @jimbob88 , this parameter already exists. It is the *multiple_instance*. Do:

    start( MyApp, multiple_instance=True )

Regards.

**Comment by jimbob88** [comment]
Hi, thanks for your reply!

This didn't seem to work for me...

If you take the widgets_overview_app example, that has `multiple_instance=True`; however, if we open 2 instances of it.

If we look at the first tab:

![image](https://user-images.githubusercontent.com/9913366/81443450-57e04600-916d-11ea-887b-0502ae770504.png)


And the second tab:

![image](https://user-images.githubusercontent.com/9913366/81443468-63337180-916d-11ea-95a0-9cf11b5b7fe3.png)

If you press the "Press me!" button, both tabs change the button's text to `Hi!`

Thanks in advance,

James

**Comment by dddomodossola** [comment]
You have to open 2 different browsers, like chrome and firefox, instead than 2 tabs.

**Comment by jimbob88** [comment]
Thanks @dddomodossola that does work; however, for my application isn't perfect. I was wondering if that feature could work for just FireFox. Let's having 10 tabs for the same application opened.

I did try with a User-Agent Switch, but that didn't work... Any ideas to get multiple instances to work for 10 tabs of the same application?

Thanks in advance,

James

**Comment by dddomodossola** [comment]
Unfortunately there is no solution for this. However I don't understand the motivation. Why you need to open 10 instances of the same application? Maybe you just need the TabBox widget?

**Comment by jimbob88** [comment]
@dddomodossola  Yeah i know it's a bit weird, but the reason is that my program allows you to have a lot of recipes and one often needs to reference another.. At the moment the program runs in tk windows and I personally think it would be cleaner if the user were to be able to access the site with multiple recipes open on each tab of the web browser...

I guess I could implement this with tabbox as you say, but i feel i would rather implement it with multiple browser tabs...

Thanks very much for your help...

**Comment by dddomodossola** [comment]
I understand, however I really don't have a solution for this. The TabBox or something similar is the only way.

**Comment by jimbob88** [comment]
I was looking through the code to see if i could come up with an idea, and i noticed that on line 276 `parse_parametrs`was spelt wrong, just a heads up...

Anyway thanks very much for your help! Love your project, keep at it!

**Comment by dddomodossola** [comment]
Thank you a lot 😉
