### ISSUE TITLE
are there any examples on mouse event on gui.Image

### ISSUE THREAD

**Issue by longswordinhand** [dddomodossola/remi#396]
I am wondering how to handle the mouse event on gui.Image? Are there any examples?
Thanks.

**Comment by dddomodossola** [comment]
Hello @longswordinhand. The mouse events for the Image are the same available for the generic Widget class.
You can also use the Editor to link events to images.
What you need to do exactly?

**Comment by longswordinhand** [comment]
Thanks a lot for your kind answers. I would like to create an application to have some mouse interaction on an image, such as draw a circle on an image using a mouse.
If there are examples, it will be very helpful.
Thanks again.

> Hello @longswordinhand. The mouse events for the Image are the same available for the generic Widget class.
> You can also use the Editor to link events to images.
> What you need to do exactly?
