### ISSUE TITLE
Problem to use the gui.image for image animation 

### ISSUE THREAD

**Issue by longswordinhand** [dddomodossola/remi#397]
I am using the gui.Image to load a sequence of images as an animation.  
However, the widget does not refresh and only display the last image. I am wondering how to update the image widget manually. Please help.
Thanks a lot.

**Comment by dddomodossola** [comment]
Hello @longswordinhand can you please share your code? I will review it to fix the animation ;-)

**Comment by longswordinhand** [comment]
Here is the code. Thanks a lot. The aim is to load a video and then play each frame in this video in a loop. In the function menu_play_video_clicked, the image is not updated correctly and no image is shown.
Thanks a lot.

###########################
from __future__ import print_function

import threading
import cv2

import time
import io

import PIL.Image
import PIL.ImageDraw

import remi.gui as gui
from remi import start, App
import base64, binascii

class SuperImage(gui.Image):
    def __init__(self, file_path_name=None, app_instance=None, **kwargs):

        image = file_path_name
        super(SuperImage, self).__init__(image, **kwargs)

        self.app_instance = app_instance
        self.imagedata = None
        self.mimetype = None
        self.encoding = None
        if not image: return
        self.load(image)
        

    def load(self, file_path_name):
        if type(file_path_name) is bytes:
            try:
                #here a base64 image is received
                self.imagedata = base64.b64decode(file_path_name, validate=True)
                # self.imagedata = file_path_name
                self.attributes['src'] = "/%s/get_image_data?update_index=%s" % (id(self), str(time.time()))
            except binascii.Error:
                #here an image data is received (opencv image)
                self.imagedata = file_path_name
                # self.refresh()
            # self.refresh()
        else:
            #here a filename is received
            self.attributes['src'] = gui.load_resource(file_path_name)
            """print(f'***** Loading file = {file_path_name}')
            self.mimetype, self.encoding = mimetypes.guess_type(file_path_name)
            with open(file_path_name, 'rb') as f:
                self.imagedata = f.read()"""
        self.refresh()

    def refresh(self):
        i = int(time.time() * 1e6)
        if self.app_instance is not None:
            self.app_instance.execute_javascript("""
                var url = '/%(id)s/get_image_data?update_index=%(frame_index)s';
                var xhr = new XMLHttpRequest();
                xhr.open('GET', url, true);
                xhr.responseType = 'blob'
                xhr.onload = function(e){
                    var urlCreator = window.URL || window.webkitURL;
                    var imageUrl = urlCreator.createObjectURL(this.response);
                    document.getElementById('%(id)s').src = imageUrl;
                }
                xhr.send();
                """ % {'id': id(self), 'frame_index':i})

    def get_image_data(self, update_index):
        headers = {'Content-type': self.mimetype if self.mimetype else 'application/octet-stream'}
        return [self.imagedata, headers]

class MyApp(App):
    def __init__(self, *args):
        super(MyApp, self).__init__(*args)

    def main(self, name='world'):
        # the arguments are	width - height - layoutOrientationOrizontal
        self.widget_height = 512
        self.widget_width = 512
        self.mainContainer = gui.Container(width=2000, height=1000, margin='0px auto')
        self.mainContainer.style['text-align'] = 'center'
        self.image_widget = SuperImage(width=512, height=512, app_instance=self)
        self.image_widget.style['margin'] = '10px'
        self.video_path = None

        self.menu = gui.Menu(width=620, height=30)
        m1 = gui.MenuItem('File', width=100, height=30)
        m11 = gui.MenuItem('Open Video', width=100, height=30)
        m11.onclick.do(self.menu_open_video_clicked)

        m14 = gui.MenuItem('Video Play', width=100, height=30)
        m14.onclick.do(self.menu_play_video_clicked)

        self.menu.append(m1)
        m1.append(m11)
        m1.append(m14)

        self.mainContainer.append(self.menu)        
        self.mainContainer.append(self.image_widget)

        # returning the root widget
        return self.mainContainer

    def menu_open_video_clicked(self, widget):
        self.fileselectionDialog = gui.FileSelectionDialog('File Selection Dialog', 'Select a video file', False, '.')
        self.fileselectionDialog.confirm_value.do(
            self.on_video_file_selected)
        self.fileselectionDialog.cancel_dialog.do(
            self.on_dialog_cancel)
        # here is shown the dialog as root widget
        self.fileselectionDialog.show(self)

    def on_video_file_selected(self, widget, file_list):
        if len(file_list) < 1:
            return
        self.video_path = file_list[0]
        self.set_root_widget(self.mainContainer)
    
    def on_dialog_cancel(self, widget):
        self.set_root_widget(self.mainContainer)
    
    def open_fileselection_dialog(self, widget):
        self.fileselectionDialog = gui.FileSelectionDialog('File Selection Dialog', 'Select files and folders', False,
                                                           '.')
        self.fileselectionDialog.confirm_value.do(
            self.on_fileselection_dialog_confirm)

        # here is returned the Input Dialog widget, and it will be shown
        self.fileselectionDialog.show(self)


    def menu_play_video_clicked(self, widget):
        capture = cv2.VideoCapture(self.video_path)
        rect = True
        while rect:
            rect, frame = capture.read()
            if rect:
                pil_image = PIL.Image.fromarray(frame[...,::-1])
                self.image_widget.pil_image = pil_image
                buf = io.BytesIO()
                pil_image.save(buf, format='png')
                self.image_widget.load(buf.getvalue())
                self.image_widget.refresh()
                self.do_gui_update()

        capture.release()
        self.set_root_widget(self.mainContainer)

    def on_close(self):
        """ Overloading App.on_close event to stop the Timer.
        """
        self.stop_flag = True
        super(MyApp, self).on_close()


if __name__ == "__main__":
    start(MyApp,)

**Comment by dddomodossola** [comment]
@longswordinhand It seems to be good code! I will try to fix it this evening ;-)

**Comment by dddomodossola** [comment]
@longswordinhand here is a working version:

```python

import threading
import cv2

import time
import io
import traceback
import remi
import remi.gui as gui
from remi import start, App
import base64, binascii

class SuperImage(gui.Image):
    capture = None              #the cv2 VideoCapture
    thread_stop_flag = False    #a flag to stop the acquisition thread
    thread = None #             the update thread
    app_instance = None
    def __init__(self, filename, *args, **kwargs):
        self.framerate = 10
        self.capture = cv2.VideoCapture(filename)
        super(SuperImage, self).__init__("", *args, **kwargs)
        self.thread = threading.Thread(target=self.update)
        self.thread.daemon = True
        self.thread.start()

    def set_image_data(self, image_data_as_numpy_array):
        #oveloaded to avoid update
        self.img = image_data_as_numpy_array

    def search_app_instance(self, node):
        if issubclass(node.__class__, remi.server.App):
            return node
        if not hasattr(node, "get_parent"):
            return None
        return self.search_app_instance(node.get_parent()) 

    def __del__(self):
        self.thread_stop_flag = True
        self.capture.release()
        super(OpencvVideo, self).__del__()

    def update(self, *args):
        while not self.thread_stop_flag:
            time.sleep(1.0/self.framerate)
            if self.app_instance==None:
                self.app_instance = self.search_app_instance(self)
                if self.app_instance==None:
                    continue

            with self.app_instance.update_lock:
                self.app_instance.execute_javascript("""
                    var url = '/%(id)s/get_image_data?index=%(frame_index)s';
                    var xhr = new XMLHttpRequest();
                    xhr.open('GET', url, true);
                    xhr.responseType = 'blob'
                    xhr.onload = function(e){
                        var urlCreator = window.URL || window.webkitURL;
                        urlCreator.revokeObjectURL(document.getElementById('%(id)s').src);
                        var imageUrl = urlCreator.createObjectURL(this.response);
                        document.getElementById('%(id)s').src = imageUrl;
                    }
                    xhr.send();
                    """ % {'id': self.identifier, 'frame_index':str(time.time())})
                

    def get_image_data(self, index=0):
        gui.Image.set_image(self, '/%(id)s/get_image_data?index=%(frame_index)s'% {'id': self.identifier, 'frame_index':str(time.time())})
        self._set_updated()
        try:
            ret, frame = self.capture.read()
            if ret:
                self.set_image_data(frame)
                ret, png = cv2.imencode('.png', frame)
                if ret:
                    headers = {'Content-type': 'image/png', 'Cache-Control':'no-cache'}
                    # tostring is an alias to tobytes, which wasn't added till numpy 1.9
                    return [png.tostring(), headers]
        except Exception:
            print(traceback.format_exc())
        return None, None


class MyApp(App):
    def init(self, *args):
        super(MyApp, self).init(*args)

    def main(self, name='world'):
        # the arguments are	width - height - layoutOrientationOrizontal
        self.widget_height = 512
        self.widget_width = 512
        self.mainContainer = gui.Container(width=2000, height=1000, margin='0px auto')
        self.mainContainer.style['text-align'] = 'center'
        self.image_widget = SuperImage('', width=512, height=512)
        self.image_widget.style['margin'] = '10px'
        self.video_path = None

        self.menu = gui.Menu(width=620, height=30)
        m1 = gui.MenuItem('File', width=100, height=30)
        m11 = gui.MenuItem('Open Video', width=100, height=30)
        m11.onclick.do(self.menu_open_video_clicked)

        m14 = gui.MenuItem('Video Play', width=100, height=30)
        m14.onclick.do(self.menu_play_video_clicked)

        self.menu.append(m1)
        m1.append(m11)
        m1.append(m14)

        self.mainContainer.append(self.menu)        
        self.mainContainer.append(self.image_widget, 'image_widget')

        # returning the root widget
        return self.mainContainer

    def menu_open_video_clicked(self, widget):
        self.fileselectionDialog = gui.FileSelectionDialog('File Selection Dialog', 'Select a video file', False, '.')
        self.fileselectionDialog.confirm_value.do(
            self.on_video_file_selected)
        self.fileselectionDialog.cancel_dialog.do(
            self.on_dialog_cancel)
        # here is shown the dialog as root widget
        self.fileselectionDialog.show(self)

    def on_video_file_selected(self, widget, file_list):
        if len(file_list) < 1:
            return
        self.video_path = file_list[0]
        self.image_widget = SuperImage(self.video_path, width=512, height=512)
        self.mainContainer.append(self.image_widget, 'image_widget')

    def on_dialog_cancel(self, widget):
        pass

    def open_fileselection_dialog(self, widget):
        self.fileselectionDialog = gui.FileSelectionDialog('File Selection Dialog', 'Select files and folders', False,
                                                        '.')
        self.fileselectionDialog.confirm_value.do(
            self.on_fileselection_dialog_confirm)

        # here is returned the Input Dialog widget, and it will be shown
        self.fileselectionDialog.show(self)

    def menu_play_video_clicked(self, widget):
        pass

    def on_close(self):
        """ Overloading App.on_close event to stop the Timer.
        """
        self.stop_flag = True
        super(MyApp, self).on_close()

if __name__ == "__main__":
    start(MyApp,)
```

**Comment by longswordinhand** [comment]
It is awesome. Thanks a lot for your work.
In the function  __del__, a class OpencvVideo is used. Where can I have it?
Thanks.

**Comment by dddomodossola** [comment]
It's an error, replace OpencvVideo with SuperImage

**Comment by longswordinhand** [comment]
That is wonderful. I appreciate your code.

**Comment by dddomodossola** [comment]
;-)
