### ISSUE TITLE
padding in default widgets

### ISSUE THREAD

**Issue by nzjrs** [dddomodossola/remi#4]
The menu and listbox widgets could use some padding (particularly on the left)

**Comment by dddomodossola** [comment]
Have you seen a functionality problem or you are referring to style improvements?

**Comment by nzjrs** [comment]
I guess it is only a style improvement, although not being able to read the first character in a listbox also hurts functionality.

**Comment by dddomodossola** [comment]
Oh yes, in this case it is a functionality issue. Thank you.

**Comment by KenT2** [comment]
I lose the first character if the listitem is wider than the listview

**Comment by dddomodossola** [comment]
Hello Ken, you're right. Maybe nzjrs is using a different browser that is causing strange rendering. Nzjrs, can you show me an image of the problem? (and please provide further information, like browser and OS)

**Comment by nzjrs** [comment]
Firefox 40, Linux.

![gui](https://cloud.githubusercontent.com/assets/41891/10289464/ae364bca-6b9e-11e5-8148-c8f94c4984a4.png)

**Comment by dddomodossola** [comment]
It seems that all the characters are visible.. Am I missing something?

**Comment by cyberpro4** [comment]
I'll add some padding before  the menu item but the list box seems pretty fine..

**Comment by nzjrs** [comment]
yeah, with https://github.com/dddomodossola/gui/commit/d954149bfbca69f0331eb1c90dbf547e044bd8bc it now looks better for me. Don't know what KenT2 means

**Comment by dddomodossola** [comment]
KenT2 told that, if the ListItems contained in the ListView have width greater than the width of ListView, it is normal to have something hidden, because the container itself trims the content.

**Comment by cyberpro4** [comment]
Can we close this?

**Comment by nzjrs** [comment]
maybe a new bug report for some other default styles? for example, padding between the OK and Cancel buttons in the File Browser dialog

**Comment by cyberpro4** [comment]
I'll restyle the whole dialog.
