### ISSUE TITLE
Can't set display style on row zero of class remi.gui.TableWidget unless use_title=True

### ISSUE THREAD

**Issue by jwrothwell2** [dddomodossola/remi#405]
I set column zero of each row to display:none (hides a DB key for that row's data), and I don't need or want a title row, so I set TableWidget use_title=False, and then put my data in row 0, setting column 0 to not display:

`self.table.item_at(*coords).set_style("display:none")`

This line of code is in a while loop, iterating through the database file -- all rows are set properly (no display of column zero) except for row 0 which displays all columns.

My workaround is to set use_title=True -- it then allows me to set display:none (or hidden), and I start my data with row 1 (2nd row).  But a thin blue line is displayed where the title row would be.

Is this expected behavior?  If so, any way to get rid of the blue line?
![Row 0 column not hidden](https://user-images.githubusercontent.com/71052582/93010411-0a238200-f541-11ea-9be3-67279d217eac.png)
![Row 0 hidden but title color shows as line](https://user-images.githubusercontent.com/71052582/93010457-a6e61f80-f541-11ea-8da9-4c6b6dfa0904.png)

**Comment by dddomodossola** [comment]
Hello @jwrothwell2 , I created this example for you, please give it a look and let me know if it solve your problem:

```python
import remi.gui as gui
from remi import start, App
import os

import sqlite3 as lite

# code example from https://pythonspot.com/python-database-programming-sqlite-tutorial/
# creating a custom database
try:
    con = lite.connect('user.db')
    with con:
        cur = con.cursor()    
        cur.execute("CREATE TABLE Users(Id INT, Name TEXT)")
        cur.execute("INSERT INTO Users VALUES(1,'Michelle')")
        cur.execute("INSERT INTO Users VALUES(2,'Sonya')")
        cur.execute("INSERT INTO Users VALUES(3,'Greg')")
except lite.OperationalError:
    print("database table seems to already exist")


class MyApp(App):
    def main(self):
        main_container = gui.VBox(style={'margin': '0px auto'})

        self.table = gui.Table()


        #Loading database into table
        con = lite.connect('user.db')
        with con:    
            cur = con.cursor()    
            cur.execute("SELECT * FROM Users")
            rows = cur.fetchall()
            for row in rows:
                #print row
                table_item_id = gui.TableItem( str(row[0]) )
                table_item_id.style['display'] = 'none'
                table_item_username = gui.TableItem(row[1])
                table_row = gui.TableRow()
                table_row.append([table_item_id, table_item_username])
                self.table.append(table_row)

        main_container.append(self.table)
        return main_container


if __name__ == "__main__":
    # starts the webserver
    start(MyApp, address='0.0.0.0', port=0, start_browser=True, username=None, password=None)

```

Kind Regards

**Comment by jwrothwell2** [comment]
This works, of course. ;-)  But even before trying it (since I assumed it would work fine), I started looking at what you did differently.  For one, you used the Table class, whereas I used the TableWidget.  But probably more important (I thought) was that you were populating the row/cell data and style before creating (appending) the table_row, whereas I was creating the row first with set_row_count, and then populating the row and changing its style. And I confirmed this -- I tried your code with both Table and then TableWidget, and got the same results. And I could set TableWidget's use_title to True or False and it didn't affect hiding the first column. So the difference that seems to matter is the sequence.

I'm curious...do you know why setting display:none prior to appending the row works and setting if afterward doesn't?  And why it only affects the first row?  Thanks.

**Comment by dddomodossola** [comment]
@jwrothwell2 The TableWidget is an automated (simplified) version of Table. It internally updates the first row in some cases. It is not supposed that the user modify directly cells style. 
As a side note, I suggest you to not store data in hidden cells. In my opinion, the right way to do so is to overload the TableRow class in order to add custom properties, and store custom info there. This way, when you get a row instance in case of onclick event, you gets custom properties with it.

```python
class MySuperTableRow(gui.TableRow):
    db_index = None
    def __init__(self, _db_index, *args, **kwargs):
        gui.TableRow.__init__(self, *args, **kwargs)
        self.db_index = _db_index
```

**Comment by jwrothwell2** [comment]
@dddomodossola I really appreciate this -- I had no idea you could do this in Python.  I've only been using Python for a few months, and I've never had much exposure to object-oriented languages and inheritance - and never really understood the concept of overloading.  I didn't realize that you could add properties like this that weren't originally defined.

So, I got this coded and working -- after several hours of trying to retrieve the value I'd stored, using row._db_index.  I almost gave up until I tried row.db_index for some reason and that worked. So I guess now I need to learn the significance of using the leading underscore when assigning the value and dropping it when retrieving the value...always something more to learn...

Thanks again so much -- this is so much easier than using hidden columns and having to search for them later using another column's coordinates. And of course, much cleaner code.  You're teaching me well!  ;-)

**Comment by dddomodossola** [comment]
@jwrothwell2 you are erally welcome.

The leading underscore has no special meaning in this case. I named the class attribute "db_index" (this is why you access the this attribute without undescrore, it is because it has no underscore) and the parameter of the __init__ function "_db_index". So I assigned the parameter class.db_index = _db_index.

**Comment by jwrothwell2** [comment]
Ah, ok. I'm still trying to wrap my head around extended classes and how they receive arguments or attributes but I think I see what you mean now that you pointed it out. Thanks.
