### ISSUE TITLE
https://remiguieditor.daviderosa.repl.co/ no module named remi

### ISSUE THREAD

**Issue by awesomebytes** [dddomodossola/remi#407]
Hello, just letting you know that https://remiguieditor.daviderosa.repl.co/ is not loading :)

**Comment by dddomodossola** [comment]
@awesomebytes thank you a lot for the info, I will now fix

**Comment by dddomodossola** [comment]
@awesomebytes  Fixed thank you ;-)

**Comment by dddomodossola** [comment]
It seems that because of recent repl.it updates it is not possible to run the editor in a stable way. I removed that link from the readme. In the future I will look for a different solution.
