### ISSUE TITLE
error parsing websocket

### ISSUE THREAD

**Issue by m-kareem** [dddomodossola/remi#409]
Dear @dddomodossola,

Thanks a lot for your continues help and support. I get a weird error message when I run my GUI: 
"**remi.server.ws   ERROR    error parsing websocket**"

however the GUI remains running and functioning as expected. Is this something I should worry about? And any idea how to fix it? Below is the beginning of the logs till the error occurrence.

Stay safe and all the best

--------------------------------- 

remi.server      INFO     Started httpserver http://127.0.0.1:5000/
127.0.0.1 - - [08/Oct/2020 00:50:16] "HEAD / HTTP/1.1" 200 -
remi.server.ws   INFO     connection established: ('127.0.0.1', 56126)
remi.server.ws   INFO     connection established: ('127.0.0.1', 56135)
remi.server.ws   INFO     connection established: ('127.0.0.1', 56136)
remi.server.ws   INFO     connection established: ('127.0.0.1', 56137)
remi.request     INFO     built UI (path=/)
remi.request     INFO     built UI (path=/res:style.css)
remi.request     INFO     built UI (path=/my_res:ITKlogo.png)
remi.server.ws   INFO     connection established: ('127.0.0.1', 56142)
remi.server.ws   INFO     handshake complete
127.0.0.1 - - [08/Oct/2020 00:50:17] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [08/Oct/2020 00:50:17] "GET /my_res:ITKlogo.png HTTP/1.1" 200 -
127.0.0.1 - - [08/Oct/2020 00:50:17] "GET /res:style.css HTTP/1.1" 200 -
127.0.0.1 - - [08/Oct/2020 00:50:18] "GET /res:font.woff2 HTTP/1.1" 200 -
remi.server.ws   ERROR    error parsing websocket
Traceback (most recent call last):
  File "//anaconda3/lib/python3.7/site-packages/remi/server.py", line 259, in on_message
    callback = get_method_by_name(runtimeInstances[widget_id], function_name)
  File "//anaconda3/lib/python3.7/weakref.py", line 137, in __getitem__
    o = self.data[key]()
KeyError: '4641814544'
127.0.0.1 - - [08/Oct/2020 00:50:18] "GET /res:style.css HTTP/1.1" 200 -
127.0.0.1 - - [08/Oct/2020 00:50:18] "GET /my_res:ITKlogo.png HTTP/1.1" 200 -
remi.server.ws   INFO     connection established: ('127.0.0.1', 56154)
remi.server.ws   INFO     handshake complete
127.0.0.1 - - [08/Oct/2020 00:50:19] "GET /res:font.woff2 HTTP/1.1" 200 -

**Comment by dddomodossola** [comment]
@m-kareem it is a normal message. It could be related to a case where you have an application running, you close and reopen the server, and the gui reloads. Can also occur in other situations. No problem

**Comment by m-kareem** [comment]
@dddomodossola ,

great, thanks a lot for your prompt response..
