### ISSUE TITLE
Old browsers support

### ISSUE THREAD

**Issue by dddomodossola** [dddomodossola/remi#41]
Should we support old browsers (for example IE9) that mainly does not have websockets? As a solution we can build a layer that implements the same protocol of the websocket class in the server, but communicates with POST requests. 
Is it a good idea?

**Comment by nzjrs** [comment]
No, that would complicate the code considerably for very very little benefit.

Remember that each feature has a maintenance cost that must be paid forever.

**Comment by dddomodossola** [comment]
Ok you are right! ;-)
