### ISSUE TITLE
clean Readme

### ISSUE THREAD

**Issue by Ksengine** [dddomodossola/remi#414]
move changelog and docs to another files.
dont include them in README

**Comment by dddomodossola** [comment]
@Ksengine Thank you for the suggestion. I will do it soon ;-)

**Comment by Ksengine** [comment]
can i help you.

**Comment by Ksengine** [comment]
we can close this issue now

**Comment by Ksengine** [comment]
i am the author of https://github.com/Ksengine/DicksonUI
you starred it once
but i had deleted and recreated it.

**Comment by Ksengine** [comment]
@dddomodossola 
not yet moved

**Comment by dddomodossola** [comment]
@Ksengine DicksonUI is cool! Why you deleted it? 
I will rework the readme after some important pending works.

**Comment by Ksengine** [comment]
> I will rework the readme after some important pending works.

ok

**Comment by Ksengine** [comment]
**my description :**
> A student in Sri Lanka. 16 years old.beginner for coding.

------------------
and beginner for github
i deleted it accidentally.
I had recreated DicksonUI.
If you can please contribute

**Comment by dddomodossola** [comment]
@Ksengine I really would be happy to contribute but I have no spare time. Work+family+some extra work= no spare time 😥

**Comment by Ksengine** [comment]
i made a pr #420
