### ISSUE TITLE
How to intentionally append different widgets in same row?

### ISSUE THREAD

**Issue by occoder** [dddomodossola/remi#421]
When I append two Button widgets into a container, as long as, their width sum does not exceed the container's width. These two Button widgets are arranged in the same row by default.
But if I append two different types of widget, say TextInput and Button, they are arranged to different rows by default whatsoever.
So my question is if Remi could explicitly define packing into same row once packing fails then falls back to different rows?
Thanks for any advice.

**Comment by dddomodossola** [comment]
The packing depends on the specific container used. If you want to arrange elements vertically use VBox container. If you want to arrange elements horizontally use an HBox. 
The basic Container class is better suited for absolute object positoning. The GridBox layout allows to arrange elements in structured flexible grids.
Kind Regards.

**Comment by occoder** [comment]
Thank you@dddomodossola for the enlightenment.
The answer brings me to [this layout example](https://github.com/dddomodossola/remi/blob/master/examples/layout_app.py).
