### ISSUE TITLE
Why is on_close not called when the browser tab is closed?

### ISSUE THREAD

**Issue by occoder** [dddomodossola/remi#422]
In the [widget_overview_app.py](https://github.com/dddomodossola/remi/blob/master/examples/widgets_overview_app.py), the on_close function is supposed to be called when the browser tab is closed.
But it turns out the on_close function is not called as the time counting continues no matter if the client browser is closed or not.
Do I misinterpret the intention behind on_close function?
Thanks

**Comment by occoder** [comment]
And I'd like to implement emitting certain button click event (or calling the click binding function directly) upon when the last browser tab is closed. Is this possible?

**Comment by dddomodossola** [comment]
Hello @occoder ,

App.on_close is called on app termination, it means the process termination. 
You maybe need this https://github.com/dddomodossola/remi/blob/master/examples/onclose_window_app.py .

Have a nice day
