### ISSUE TITLE
How to arbitrarily position item within HBox?

### ISSUE THREAD

**Issue by occoder** [dddomodossola/remi#427]
I'd like to arrange image and label items within HBox with arbitrary padding pixels among them.
But it seems HBox does not allow to do so.
If I set style with, like `style='position: relative; left: 100px; top: 100px'` to each item. The items still stack up by default.
I don't know what gets wrongly set.
By the way, does position: relative mean being relative to its parent container, i.e. Hbox in my case? It seems that it won't take effect no matter how I tweak up it parent property.

**Comment by dddomodossola** [comment]
Hello @occoder,

For absolute positioning you should use the Container class. The HBox arranges the children automatically. 
However you maybe want to not define absolute position for items, you don't need to set *left* and *top*. You simply need to set a margin to each item. To get this, set:

```python
    my_hbox.css_justify_content = 'flex-start'
    child1.css_margin = '10px' #the required spacing value
    child2.css_margin = '10px' #the required spacing value
```

Kind Regards

**Comment by occoder** [comment]
Hello @dddomodossola 
Thanks for your kind prompt.
I've tried your proposal. It turns out that css_margin makes the margin around the item's all sides which makes it difficult to just leave space at only one side of the item.

**Comment by dddomodossola** [comment]
Hello @occoder ,

Instead of child.css_margin, you can use child.style['margin-left']

;-)

**Comment by occoder** [comment]
Thank you @dddomodossola
