### ISSUE TITLE
[Doc] Error in building Sphinx docs

### ISSUE THREAD

**Issue by Robin-Castellani** [dddomodossola/remi#429]
Hi everybody! 👋

First of all thanks for your efforts! That's a great library.

I was looking for a documentation beyond the `README.md`, but I found nothing ready to be used. Therefore I tried to build the docs from the `doc` directory using the `Makefile` provided (Sphinx based). These errors occurred:

```
WARNING: autodoc: failed to import module 'gui' from module 'remi'; the following exception was raised:
No module named 'remi'
```

I solved by inserting at the beginning of  the `conf.py` Sphinx file this line
```
sys.path.insert(0, os.path.abspath('..'))
```
In this way I notify Sphinx that it should look for modules in its parent directory (that is the repo root directory), that is where `remi` is.

With this modification the HTML build went good; only rst syntax warning like this one were raised:
```
remi\gui.py:docstring of remi.gui.CheckBoxLabel.set_on_change_listener:1: WARNING: Inline emphasis start-string without end-string.
```
These warnings are not so bad, the docs may not be built as you meant to be.

Shall I pull-request this change? After a short search I've found no issue about doc.
Also, is there any doc available anywhere (readthedocs, GitHub Pages, elsewhere)? 

Thanks,
Robin

PS: this is my very first issue, I'm sorry whether I missed some information. Anyway, I found no contribution code of conduct...

**Comment by dddomodossola** [comment]
Hello @Robin-Castellani you are really welcome to create a pull request. There is no additional documentation unfortunately. However there are some example, and the graphical editor can be also really useful. Nonetheless  you can ask me for questions/suggestions.  😉👍

**Comment by Robin-Castellani** [comment]
Thank you Davide! 

I'll create it as soon as possible. 👍

**Comment by dddomodossola** [comment]
Thank you too @Robin-Castellani 😉
