### ISSUE TITLE
Editor - 'Editor' object has no attribute 'drag_helpers'

### ISSUE THREAD

**Issue by igor-dan** [dddomodossola/remi#436]
When trying to run editor, I receive following exception:

_Traceback (most recent call last):
  File "C:\WinPython\WPy64-3850min\python-3.8.5.amd64\lib\site-packages\remi\server.py", line 421, in _idle_loop
    self.idle()
  File "E:/dev2/Python/SandBox/remi/editor/editor.py", line 720, in idle
    for drag_helper in self.drag_helpers:
AttributeError: 'Editor' object has no attribute 'drag_helpers'_

**Comment by dddomodossola** [comment]
Hello @igor-dan , thank you for reporting this problem. Can you please tell me which version are you using? Please try to install both remi and editor from remi master branch

**Comment by igor-dan** [comment]
Hi. This is exactly what I did. I cloned remi master branch.

**Comment by dddomodossola** [comment]
@igor-dan What you updated? The editor or the remi installation? 
furthermore can you download again the latest editor version? I made a change right now and I would like to know that it works.

Thank you too ;-)

**Comment by p-bogi** [comment]
Hello, I just started to try Remi for the first time. The examples worked. So I tried to start the GUI Editor. I am on Win10 and Python 3.7.3. I tried more branches (master, develop ...) but cannot find one where the error would not appear. I also tried Firefox, Chrome, Edge.
remi.request     ERROR    exception in App.idle method
Traceback (most recent call last):
  File "D:\python\Python37\lib\site-packages\remi\server.py", line 421, in _idle_loop
    self.idle()
  File "D:\git-work\remi\editor\editor.py", line 721, in idle
    for drag_helper in self.drag_helpers:
AttributeError: 'Editor' object has no attribute 'drag_helpers'

**Comment by dddomodossola** [comment]
Hello @p-bogi please install remi from github master branch. The problem is that you installed remi from pypi and you are using a more updated editor version from github.

**Comment by p-bogi** [comment]
Thanks, that helped! :)

**Comment by dddomodossola** [comment]
😉👍
