### ISSUE TITLE
Could event handler be connected at initialization?

### ISSUE THREAD

**Issue by waingt** [dddomodossola/remi#437]
This GUI library is so cool.
But, when I create a button, I must assign a variable to it at first, then connect event and append it to container. (this takes 3 lines)
I suppose it is cooler if this could be done in one line

for example:

```python
class Button(gui.Widget, gui._MixinTextualWidget):
    def __init__(self, text="", onclick=None, *args, **kwargs):
        super(Button, self).__init__(*args, **kwargs)
        self.type = "button"
        self.set_text(text)
        if type(onclick) == list:
            if len(onclick) == 2:
                self.onclick.do(onclick[0], *onclick[1])
            elif len(onclick) == 3:
                self.onclick.do(onclick[0], *onclick[1], **onclick[2])
        elif onclick:
            self.onclick.do(onclick)
```
usage:
```python
container.append(Button("click", onclick=[self.btnclick, ["somedata"]]))
```

**Comment by dddomodossola** [comment]
@waingt  This is really cool, I will implement it in a near future! Thank you for the suggestion ;-)
However I will make a more generic implementation to avoid named parameters like "onclick". I suppose to accept a parameter like Button("my button", do={Button.onclick: my_onclick_handler, Button.onmouseover: my_onmouseover_handler}) .
