### ISSUE TITLE
Checkbox widget?

### ISSUE THREAD

**Issue by awesomebytes** [dddomodossola/remi#44]
Any plan to implement a checkbox widget?

I may hack one with two images of a checked and unchecked checkbox, but I believe you can do better by creating the html element for it.

**Comment by dddomodossola** [comment]
No problem, I will implement it soon maybe today ;-)

**Comment by dddomodossola** [comment]
Hi awesomebytes, I built a new CheckBox widget. You can see the usage in the widgets_overview_app.py.
This is a first base implementation, but a composite CheckBox with Label have to be build.

**Comment by awesomebytes** [comment]
Tested and I made you a PR https://github.com/dddomodossola/remi/pull/46 with a new screenshot to ease your life.

Thank you very much!
It's good to have the CheckBox separated, but I agree that a Composite one with label would be nice.
