### ISSUE TITLE
Hover text?

### ISSUE THREAD

**Issue by awesomebytes** [dddomodossola/remi#45]
Any plan on implementing hover text on the widgets?

I would like to be able to show some text over a widget to help understand what it does.

**Comment by dddomodossola** [comment]
You can already set an hover text by the standard html attribute 'title' in this way

widget_instance.attributes['title']='your hover text'

Let me know if you encounter problems ;-)

**Comment by nzjrs** [comment]
Maybe add this to the Readme?

**Comment by awesomebytes** [comment]
That's great to know!

Thank you. My experience so far with your library is wonderful.

**Comment by dddomodossola** [comment]
Yes this must be written in the README. I'm doing this now. Happy to see you like the library. ;-)

**Comment by dddomodossola** [comment]
Done
