### ISSUE TITLE
How to emit an event and trigger an action

### ISSUE THREAD

**Issue by m-kareem** [dddomodossola/remi#450]
Hello @dddomodossola ,

Thanks again for your kind and continues support. I would like to implement 'pubsub' feature in my GUI to receive alerts and warnings from other scripts that are running in the background. The best way to have less interaction between the GUI and the other scripts is to have those scripts to send messages via 'pubsub' and receive them in the GUI.

After a message is received by the GUI,  I would like to trigger an action (like showing a pup-up alert message). Could you please show me how to emit an event upon the receive of a message by 'pubsub' and trigger an action?

Best regards,

**Comment by dddomodossola** [comment]
Hello @m-kareem ,

Excuse me for the late reply. To trigger an event you simply need to call it like a function. Suppose the Button.onlick event, if you have a button named *mybutton* and you want to trigger the event by code, you can simply do mybutton.onclick(). This way the listener will receive the event. 

Furthermore, consider that in order to communicate with other processes, remi can receive GET requests. This allows you to avoid implementing particular protocols. Look at the example https://github.com/dddomodossola/remi/blob/master/examples/webAPI_app.py .

Kind Regards.

**Comment by m-kareem** [comment]
Hello @dddomodossola,

Thanks a lot for your kind response. The onclick() function is specific for the buttons and I am already using it in my GUI. My question is for when a generic event happens independent of the users actions. For example when a warning message is received by the GUI from other processes. How should the listener get it and how to call a specific function based on that?

Best regards,

**Comment by dddomodossola** [comment]
I'm not sure to understand. Let's discuss it. 
You have a remi application and an external application. 
The external app sends message to remi app using a particular protocol.
The remi app receives such messages in a thread or in the idle loop.
When the event occurs, for example the string "WARNING" is received by protocol, a particular function have to be called.
If this is the situation you simply need to call such function, for example:

    if message == "WARNING":
        self.my_warning_handler() #or maybe self.my_warning_dialog.show()

Events are not requirent up to this point. 
Maybe you want to create an app automation where, for particular messages, the app spawns events, and the listeners should handle such events. If so, please describe it in detail.

**Comment by m-kareem** [comment]
Thanks a lot @dddomodossola , what you described is exactly what I want to do. I just did not know where to place the function in the code. So it should be in a running thread in the main function of the GUI or in the idle loop so that remi can always listen when the "if" statement became true, it executes the message handler.

I will give it a try and will let you know if it did not work.

Best,

**Comment by dddomodossola** [comment]
This is a threaded application example https://github.com/dddomodossola/remi/blob/master/examples/threaded_app.py , give it particular attention tp the App.update_lock used to sync the remi thread with the external thread. ;-)
