### ISSUE TITLE
How to delete my selected item using listview

### ISSUE THREAD

**Issue by Ah-Q** [dddomodossola/remi#451]
I recently learned remi. When using listview, I want to delete the selected item, but after observing the source code, I found that the corresponding function was not found. How should I delete the selected item?

**Comment by dddomodossola** [comment]
Hello @Ah-Q , to remove a widget from a parent you can do parent.remove_child(child_instance). In your case you should do 

    listview.remove_child(listview.children[listview.get_key()])

Kind Regards

**Comment by Ah-Q** [comment]
> Hello @Ah-Q , to remove a widget from a parent you can do parent.remove_child(child_instance). In your case you should do
> 
> ```
> listview.remove_child(listview.children[listview.get_key()])
> ```
> 
> Kind Regards
This problem has puzzled me for a long time, and now it has been solved by you. Thank you very much
