### ISSUE TITLE
how to support js scripts in remi framework

### ISSUE THREAD

**Issue by yaochx** [dddomodossola/remi#463]
I haw few dev experience on web ui, here's a probing question.
Is it possible to insert the following code in remi gui, or how to support js scripts in remi framework?
```
    <div class="wrapper">
      <section class="main-controls">
        <canvas class="visualizer" height="60px"></canvas>
        <div id="buttons">
          <button class="record">Record</button>
          <button class="stop">Stop</button>
        </div>
      </section>

      <section class="sound-clips">
      </section>

    </div>

    <script src="scripts/app.js"></script>
```

[scripts/app.js](https://raw.githubusercontent.com/mdn/web-dictaphone/gh-pages/scripts/app.js)

I'm finding solutions to use js code to record audio in remi demo

Thanks in advanced

**Comment by dddomodossola** [comment]
Hello @yaochx ,

In the example script "template_advanced_app.py" https://github.com/dddomodossola/remi/blob/master/examples/template_advanced_app.py you can find a section to append custom css and js: 
```
    def main(self):
        #custom additional html head tags
        my_html_head = """
            """

        #custom css
        my_css_head = """
            <link rel="stylesheet" href="" type="text/css">
            """

        #custom js
        my_js_head = """
            <script></script>
            """
```

Here you can add custom js code or a link to js files. ;-) 

Kind Regards.

**Comment by yaochx** [comment]
Many thanks to @dddomodossola 
I will have a try
