### ISSUE TITLE
I want to embed VLC in the browser，I don't know, any examples？

### ISSUE THREAD

**Issue by Antonio0307** [dddomodossola/remi#466]
I want to embed VLC in the browser，I don't know, any examples？

**Comment by dddomodossola** [comment]
This is not a remi specific question. What is your project?

**Comment by Antonio0307** [comment]
Sorry, my English is not very good.I want to embed a VLC player in REmi,but, I don't know what to do.......I'd like to see some examples of this, if any.....
Thanks for your  reply ! : )

**Comment by themayankjha** [comment]
you cannot as per say embed vlc in a browser. also It's not possible any more. It used to be possible with FLASH, but flash is no longer supported. You must use a format that is supported like HLS or DASH.

source :- https://stackoverflow.com/questions/60124729/how-to-show-rtmp-live-stream-in-web-browser
