### ISSUE TITLE
Remi + Jupyter Lab

### ISSUE THREAD

**Issue by gbrault** [dddomodossola/remi#473]
@dddomodossola : Many thank for your work.

Some time in Jupyter, you need to develop user specific UI and you can use

-   Ipywidgets and Voila
-   Or Remi, using a Remi fork: https://github.com/gbrault/remi

It still is in development, but if you are interested, I can open a pull request, let me know.

**Comment by dddomodossola** [comment]
@gbrault Many thank you too for your wonderful work on the pull request 475 .
