### ISSUE TITLE
TextInput callback on Enter

### ISSUE THREAD

**Issue by awesomebytes** [dddomodossola/remi#48]
Maybe just with having the single_line attribute to True we could have a callback when hitting enter.

**Comment by dddomodossola** [comment]
Done. You can use *set_on_enter_listener* in order to register your callback. Please give us a feedback in order to close the issue.

**Comment by awesomebytes** [comment]
Dude, you rock! checking right now.

**Comment by awesomebytes** [comment]
Tested, it works flawlessly :)

**Comment by dddomodossola** [comment]
Fine! Thank you ;-)
