### ISSUE TITLE
add gui layout algorithm

### ISSUE THREAD

**Issue by nzjrs** [dddomodossola/remi#5]
Manually specifying widget coordinates is slow, error prone, and different to other gui frameworks.

Perhaps auto computation of widget location and size can be added. There are two pure python gui layout libraries available

http://cassowary.readthedocs.org/en/latest/
https://github.com/pybee/colosseum

**Comment by dddomodossola** [comment]
Hi nzjrs, you have not to define the coordinates of a widget. It is only required define the size of a widget in the constructor. however you're right, the auto-sizing could be a useful functionality. I'm trying to avoid external library dependencies, so I plan to do it simply coding it by myself.

**Comment by nzjrs** [comment]
Cool thanks.

> I'm trying to avoid external library dependencies, so I plan to do it simply coding it by myself.

I think some pure-python dependencies are fine. Coding it yourself can introduce unnecessary bugs.

**Comment by dddomodossola** [comment]
You're right again, but I'm worried about PIP... I heard about a lot of developers that everytime gets problems with pip, furthermore I imagine a world where people download something and this "something" works. :-D
I will evaluate your suggestion.

**Comment by nzjrs** [comment]
> You're right again, but I'm worried about PIP... I heard about a lot of developers that everytime gets 
> problems with pip

pip can have problems when it needs to compile native code. for pure python it is good enough.

if developers have trouble with it that is often the fault of the developers
