### ISSUE TITLE
Using examples without setup.py gives import error

### ISSUE THREAD

**Issue by KenT2** [dddomodossola/remi#52]
I tried using the examples without running setup.py. This gave an import error. I moved the examples up a directory level and they worked,

Is there a way change the examples such that they will do the imports across sub-directories.

**Comment by nzjrs** [comment]
This is normal python package layout and behaviour. You can install in a virtualenv with python setup.py develop, or you can set your pythonpath to be the current directory ```export PYTHONPATH=`pwd`:$PYTHONPATH``` etc
