### ISSUE TITLE
Dropdown set methods dont set the dropdown

### ISSUE THREAD

**Issue by awesomebytes** [dddomodossola/remi#54]
I've tried set_value and set_key and they are not changing the value.

**Comment by awesomebytes** [comment]
Actually, the select_by_key (sorry, called it set_key) works, but I cannot make work the set_value. I may be messing something with the string representation of the field :/.

**Comment by dddomodossola** [comment]
Can you provide an example of your usage? Furthermore, have you enabled debug in order to check errors?

**Comment by awesomebytes** [comment]
I had debug 2 enabled indeed, no errors, I'll try to find a reproducible
tiny example, but I'm almost sure I'm messing up something with strings and
maybe their representation.

With the set key works.

Btw I just kinda finished the app I was doing. I'll make it pretty and show
:) it's a very useful tool for robotics people using ROS.

**Comment by KenT2** [comment]
try the latest widgets_overview_app. It has a dialog from the menu in which you set a dropdown value which is transferred to the main page. Works here on Firefox on Windows with RPi  server.

**Comment by dddomodossola** [comment]
:-D  where you will post your app? I'm curious to see it! 

However, the usage of set_value is shown in the example provided by Ken, and it works.

**Comment by nzjrs** [comment]
@awesomebytes Ha, I am also using remi to drive ROS. Small world.

**Comment by awesomebytes** [comment]
Be my first beta tester of my web dynamic reconfigure then!
https://github.com/awesomebytes/web_dyn_reconf

The enums are wrong (I supposed they always start in 0, and that's totally wrong) but it works! (no one uses enums anyways, right? haha).

**Comment by nzjrs** [comment]
Awesome, although I wish dynamic reconfigure wasn't such a poorly
implemented POS to begin with.....

;-)

**Comment by nzjrs** [comment]
Also see that you are doing the setattr dance to generate dynamic methods. I really should add userdata support to callbacks.

**Comment by awesomebytes** [comment]
True, but everyone uses it! The enums part is crazy... they store in a string a python dictionary, I mean, it's string representation of a python dictionary. So you must kinda eval it to transform it in a python dictionary. From C++ that sounds like a nightmare haha

And yeah, I found out that setattr trick. But that's ugly as hell. I hope I never need to debug that.

Please, if you have the time, implement the userdata in callbacks :)

**Comment by awesomebytes** [comment]
I'm going to close this issue as I'm sure I was doing something wrong with the text inside of the dropdowns.

**Comment by dddomodossola** [comment]
Maybe you can show us the piece of code you consider faulty in order to detect the error?

**Comment by awesomebytes** [comment]
I ditched it away, sorry xD

**Comment by dddomodossola** [comment]
No problem ;-)
