### ISSUE TITLE
read_next_message string index out of range

### ISSUE THREAD

**Issue by awesomebytes** [dddomodossola/remi#56]
I've seen this error happen from time to time, I cannot reproduce it:

```
Exception in server.py-read_next_message.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/remi/server.py", line 177, in read_next_message
    length = self.bytetonum(length[1]) & 127
IndexError: string index out of range
```

**Comment by dddomodossola** [comment]
Hi awesomebytes, this exception happens when the browser disconnects or is closed. This is managed. ;-)

**Comment by awesomebytes** [comment]
Ok, great to know, next one who googles this will be fine haha

Thank you :)

**Comment by buxtonpaul** [comment]
Hi
How do you mean managed? I have this issue on version 1.0 installed from pip.
After disconnecting the browser and receiving the message I am then unable to launch again as the socket is already bound.

Excellent project by the way, looking forward to slapping it onto some raspberry pi's!

**Comment by dddomodossola** [comment]
Hello @buxtonpaul  . 
This exception is not an issue. Is a known 'normal' behaviour caused by browser (websocket) disconnection. This isn't the cause of your problem. Can you provide more info about the problem? Such as host system, web browser and so on...

**Comment by buxtonpaul** [comment]
Actually I feel a little silly.  This issue made it look like the server had shutdown, however it is still running, which is why when I attempt to run it again it fails. Doh!

**Comment by dddomodossola** [comment]
@buxtonpaul no problem, you are welcome ;-)
