### ISSUE TITLE
Add userdata to callbacks

### ISSUE THREAD

**Issue by frsh2fourty** [dddomodossola/remi#58]
Is there a way to pass multiple variables from multiple text inputs to a single listener function?

My thought was to set up an on_change listener for each text input but use the same listener function name for each one, then when writing the actual listener function pass all the variables you want that function to use, for example:
self.input1 = gui.TextInput(200, 20)
self.input1.set_on_change_listener(self, 'listener_function')
self.input2 = gui.TextInput(200, 50)
self.input2.set_on_change_listener(self, 'listener_function')
def listener_function(self, var1, var2)
    self.lbl.set_text(str(var1) + ' & ' + str(var2)

However, doing this breaks the function so it won't populate the 'lbl' or do anything else defined in that function but doesn't return any errors.

**Comment by nzjrs** [comment]
No, adding userdata to callbacks is on my TODO list. You can kind of fake it with lambdas scoped lambda variables

```python

def main():
    # fixme: because the framework doesn't allow userdata, we have to create one function per callback

            slider = gui.Slider(400, 30, sval, 0, smaxval)
            f = lambda _v, _sname=sname: self.on_slider_change(_v, _sname)
            fname = 'on_slider_change_%d' % i
            setattr(self, fname, f)
            slider.set_on_change_listener(self, fname)
            self.sliders[sname] = slider

    def on_slider_change(self, value, trackbar_name):
        self.spins[trackbar_name].set_value(value)
        self.callbacks[trackbar_name](int(value))
```

**Comment by dddomodossola** [comment]
Maybe, the correct way to do this should be:
```python
    self.input1 = gui.TextInput(200, 20)
    self.input1.set_on_change_listener(self, 'listener_function')
    self.input2 = gui.TextInput(200, 50)
    self.input2.set_on_change_listener(self, 'listener_function')

def listener_function(self, var1)
    self.lbl.set_text(self.input1.get_value() + self.input1.get_value())
```

Do not forget that in listener functions you have access to all your variables.
This is also the way to manage this in other gui framework like qt.

However what proposed by John (user data in callbacks) is sure a very usefull improvement.

**Comment by dddomodossola** [comment]
The solution for passing userdata in the callbacks could be simply implemented in EventManager. When calling the callback it could pass as first parameter the "source_widget". 
```python
    def propagate(self, eventname, params):
        # if for an event there is a listener, it calls the listener passing the parameters
        if eventname not in self.listeners:
            return
        listener = self.listeners[eventname]
        return getattr(listener['instance'], listener['funcname'])( source_widget, *params )
```
Througout the "source_widget" one listener function can manage events from different widgets. Is it satisfying or the only "source" does not allow to manage other situations?

**Comment by nzjrs** [comment]
Source widget is not quite the same as userdata.

**Comment by dddomodossola** [comment]
Sure :-) but solves the above mentioned use case (allowing to reuse a callback for multiple purposes). Maybe the same "source_widget" can be used to store custom information where needed.

**Comment by nzjrs** [comment]
Are you familiar with how userdata is used in other gui frameworks and what
problems it solves?

Both userdata and the event source are commonly passed on.

Don't be too much like a ball, bouncing around and solving every proposed
use case - you really only get one chance to design the perfect API, that
if done well, will address the use cases people haven't thought of yet.

**Comment by nzjrs** [comment]
I mean no offense of course,  just some advice from someone who has done
this a few times ;-)

**Comment by dddomodossola** [comment]
I trust your opinion John. ;-)  It's only to get a constructive discussion on how to model the best solution.

**Comment by sfabris** [comment]
I'm playing with remi right now... Really nice.
But not being able to pass data on callbacks is limiting for me.

I tried to hack the code but I've been unsuccessful right now following the example proposed in this issue.

Which is the suggested / corrected way to obtain this right now?

**Comment by dddomodossola** [comment]
@sfabris can you provide me an example of your specific need? I will be pleased to help you.

**Comment by nzjrs** [comment]
I use the lambdas hack in all my code, so that way works for me at least. I should get back to implementing this...

**Comment by nzjrs** [comment]
@dddomodossola if you are used to using a GUI framework which allows you to attach userdata to all callbacks, it feels very very limiting to have this missing in remi. It changes how one structures event driven code and is hard to explain how much it can make things easier if you are not familiar with the paradigm.

**Comment by dddomodossola** [comment]
@nzjrs I understand John. This should be simple to implement. But I would like to have a solution that does not affect the actual usage of the library, just to say, is it ok to have an extra **optional** parameter userdata to set_on_xx_listener? If so, I can implement this rapidly.

**Comment by nzjrs** [comment]
The convention is the last user data argument is *userdata, and is then
unpacked when calling the callback - so it is optional and supports
multiple arguments. If you are not sure what I mean, check out how other
libraries do it and make a pull request so we can discus the api.

**Comment by dddomodossola** [comment]
Now it's done.

**Comment by sfabris** [comment]
Thanks!
