### ISSUE TITLE
Upload remi package to PyPi

### ISSUE THREAD

**Issue by cryzed** [dddomodossola/remi#68]
This would allow more people to find the project and (more) easily install it with pip.

**Comment by nzjrs** [comment]
Personally I don't think it is ready and stable yet. I don't know what the others think

Don't forget you can ```pip install git+https://github.com/dddomodossola/remi.git```

**Comment by cryzed** [comment]
I don't think there's a reason to not upload experimental Python modules to PyPi, as far as I know it's neither encouraged nor discouraged. Maybe making it clear in the README.md would prevent misunderstandings.

I'm just hoping that this would potentially attract more contributors and people interested in the project, since I definitely am.

**Comment by nzjrs** [comment]
I would rather achieve some level of API stability before unleashing this onto the world - it can be a burden having too many users if the library is still changing.

Most people find their software through google, not necessarily through pip. I will make it clear that remi can be installed from git directly using pip, and that it is unstable.

**Comment by cryzed** [comment]
Alright, thank you -- I can see why that would make sense. Looking forward to see how remi grows and using it!

PS: Sorry for spamming the bug tracker somewhat, I just feel creating a separate issue for each concern makes more sense, and I had some ideas during the few days I've known remi.

**Comment by nzjrs** [comment]
Let's keep this open so we don't forget. Don't worry, your issues are certainly not spam!

**Comment by caedn** [comment]
Any chance to have it on PyPi now?

**Comment by dddomodossola** [comment]
It could be great. I think that the library is enough ready to do so. Have you a tutorial about uploading on PyPi?

**Comment by nzjrs** [comment]
I agree. I think it's stable enough now

**Comment by dddomodossola** [comment]
;-) I will try to do so this night (GMT +1)

**Comment by dddomodossola** [comment]
Done, but maybe something is missing. I can't see the readme file shown in pypi. I've to investigate over this.
