### ISSUE TITLE
How can I make remi run in my local network?

### ISSUE THREAD

**Issue by Paarthri** [dddomodossola/remi#71]
So other computers in the network can access the page. It may sound like a stupid question but i'm new to think kind of stuff.

**Comment by nzjrs** [comment]
bind to 0.0.0.0 or to your internal network IP address

**Comment by Paarthri** [comment]
How do I do that?

**Comment by nzjrs** [comment]
call ```start(address='0.0.0.0')``` see https://github.com/dddomodossola/remi/blob/master/examples/simple_app.py#L54

you should replace '0.0.0.0' with the ip address of your local network interface for better security

**Comment by Paarthri** [comment]
Thank you
