### ISSUE TITLE
Format of Listview and Checkbox in Generic Dialog

### ISSUE THREAD

**Issue by KenT2** [dddomodossola/remi#74]
In the Generic Dialog I cannot get the ListView to format the columns correctly and checkbox seems to add a lot of space. See widgets_overview_app.py

**Comment by dddomodossola** [comment]
Ok, the problem seems to be caused by scrollbars that changes the size of the listview. I will see what we can do. For what about the checkbox, it is located at the center of the box you specified, the space after the checkbox is the area that the ListView occupies if rightly located.

**Comment by dddomodossola** [comment]
I removed the border to the ListView, the problem you mentioned disappeared. It is needed a restyle for the widget.

**Comment by KenT2** [comment]
Fixed for IE on windows and Epiphany (RPi). If you could change the width of the dialog from 400 to 425 that will fix it for Firefox on Windows.

Forgot the label for the Listview is vertically in the centre, hence my wrong comment about the checkbox

**Comment by dddomodossola** [comment]
@KenT2 Hi Ken, I tried it with firefox( version 41.0.1 ) on windows and it seems to be ok. Maybe you have to reload the page because of the caching? Please confirm.

**Comment by KenT2** [comment]
Yes, that was it. That's the second time I have been caught by that one :-(

**Comment by dddomodossola** [comment]
No problem, it happens also to me ;-)
