### ISSUE TITLE
Resources fails to load outside "res" folder

### ISSUE THREAD

**Issue by dddomodossola** [dddomodossola/remi#77]
When an Image widget points to a local resource, it fails to load.

**Comment by dddomodossola** [comment]
@nzjrs This seems to be generated by the regular expressions. Maybe this is specifically wanted because of security reasons. But we have to consider that, if the /res folder is part of the library and we have different apps using the library, should all apps insert their resources in the library path? How we can manage this?

**Comment by nzjrs** [comment]
We could whitelist a local location in the Server constructor

```s = Server(local_base='/foo')``` and then only serve res files relative to that base?

**Comment by nzjrs** [comment]
This should be fixed with

https://github.com/dddomodossola/remi/commit/35ce4c07a28ab920267f49449853d7edc9fc7f1a
