### ISSUE TITLE
Download displays the file in browser rather than saving it. IE only.

### ISSUE THREAD

**Issue by KenT2** [dddomodossola/remi#8]
The download works fine in Firefox with the download dialog allowing it to be saved, but in IE the logo.png is displayed in the browser instead of causing the download dialog. I vaguely remember from the distant past that IE needs a header to be sent. Can advise you if necessary.

**Comment by dddomodossola** [comment]
Hi Ken, Done! :-D
Please feedback

**Comment by KenT2** [comment]
Yes, works fine thanks
