### ISSUE TITLE
More GUI like API

### ISSUE THREAD

**Issue by nzjrs** [dddomodossola/remi#81]
There are several things that could be improved to make remi feel more like a GUI toolkit. Things like `.append(random_string,widget)` feel very much like you are manually writing HTML and not building a GUI. Perhaps make a container base class / mixin that manages append for you (as the ID is almost unneeded in most cases)

**Comment by nzjrs** [comment]
Also, things like ```Table``` should have a more table like API ```add_row``` etc

**Comment by nzjrs** [comment]
```Tag.append -> Tag.set_child```

```python
class Container(Widget):
    def __init__(self, w, h, layout):
        pass

    def append(self, widget):
        child_ref = '%s' % self._child_idx
        self.set_child(child_ref, widget)
        return child_ref
```

**Comment by dddomodossola** [comment]
I like this change. I coded the actual append function allowing to access child widget by known keys. This caused unpleasant coding. 
Maybe we should inform users by the README file about this change.

**Comment by KenT2** [comment]
I wonder if its possible to include an App supplied key as an optional argument. If not supplied then revert to auto-key.
* There have been occasions in the past when I could  have used App supplied keys.
* The change will break simple_app_dynamic_layout.py. I have just used the same technique in an experimental tabbbed dialog to display the new tab when a button is clicked. It's rather nice.
* It will make migration of existing Apps easier.

**Comment by KenT2** [comment]
Another thing that might make the API more gui like is to replace the strings specifying the names of the listener functions with the name of the function.
Instead of this:
self.bt.set_on_click_listener(self, 'on_button_pressed')
this:
self.bt.set_on_click_listener(self, self.on_button_pressed)

**Comment by nzjrs** [comment]
@KenT2 The difference between a user supplied key, and an invisible one is, to my intuition and what other toolkits do, the same as appending a child and setting a child. And in my API model I would return the generated key so the widget could be replaced/updated later using the set API.

Regarding the callbacks, yes I want to remove the string identifiers, it is very odd compared to every other GUI framework.

**Comment by nzjrs** [comment]
Does anyone have any naming suggestions for append / set_child / get_child ?

**Comment by dddomodossola** [comment]
I felt comfortable with Qt toolkit. What about add_widget (and from this set_widget / get_widget)?

**Comment by nzjrs** [comment]
I liked the Qt3 API a little more than the current one (i.e. now every Qwidget has an orientation, which is the model Remi copied...), but fair enough - set_widget and add_widget are distinct.

I want the API for container classes to feel a little different than non containers (the Gtk model), which is why I like append_widget.

**Comment by dddomodossola** [comment]
So, only to be sure I understood, you would like to have Containers that are comparable to Layouts right? The specific widgets themselves can contain other widgets?

**Comment by nzjrs** [comment]
I propose that In remi, contains would differ from widgets in that only they would provide append() which would manage child identifiers, and only containers would have an orientation property.

Every widget could still contain other widgets (via set_widget), but the container API would be nicer

**Comment by dddomodossola** [comment]
Ok, now it is clear. Which kind of advantage this work provides? Are these changes also propaedeutic to other changes you planned, or it's "just" to get a more standard API interface?

**Comment by nzjrs** [comment]
The changes are just to give the framework a more standard (so it feels
like other GUI toolkits) API

**Comment by nzjrs** [comment]
good enough now
