### ISSUE TITLE
Feature Request: TabView

### ISSUE THREAD

**Issue by KenT2** [dddomodossola/remi#82]
The TabView would implement the Tabs described here

 http://www.getmdl.io/components/index.html#layout-section/tabs

The TabView can be placed in a main page or a dialog. The tab panels are implemented as a container which the App can fill with its own content.

I have written  an experimental TabView using as a ListView for the Tab Bar which can be downloaded from  here

http://www.museumoftechnology.org.uk/ken/tabbed.zip

The methods in this prototype are those I used in another Tkinter application and are not sacrosanct

**Comment by dddomodossola** [comment]
Already done. An example in tabbox.py .
