### ISSUE TITLE
Make Message in Generic Dialog optional

### ISSUE THREAD

**Issue by KenT2** [dddomodossola/remi#83]
Sometimes the message is not required but if message='' then there is a lot of vertical whitespace

**Comment by Paarthri** [comment]
The white space is their not because of the absence of a message but because the default size of the GenericDialog is 500x160. No matter what is in it it will always be the predefined size.

**Comment by dddomodossola** [comment]
Fixed. ;-)
Furthermore, using GenericDialog I suggest to avoid to specify the "height" in the constructor. The GenericDialog itself should calculate it.
