### ISSUE TITLE
add_field in Dialogs and append in main pages

### ISSUE THREAD

**Issue by KenT2** [dddomodossola/remi#84]
I'm not an expert at this sort of thing but is seems odd to me that there is add_field for dialogs and append for  main pages. To me a dialog is the same as a main page except it has OK/Cancel buttons and pops up so the way of adding new fields should be the same for both.

P.S You can actually use append in dialogs providing you add_filed a container widget first.

**Comment by dddomodossola** [comment]
I think the best should be to rename 'add_field' in 'append' for dialogs in order to make it conformant to other containers. Is it ok as solution?

**Comment by KenT2** [comment]
I am OK with this

**Comment by dddomodossola** [comment]
Excuse me for the late reply, hope this satisfy your request. ;-)
