### ISSUE TITLE
Feature Request: append_with_label

### ISSUE THREAD

**Issue by KenT2** [dddomodossola/remi#85]
add_field_with_label is a useful function. It would be good to have append_with_label

**Comment by dddomodossola** [comment]
Hi Ken, can you explain this? In which kind of widget you would like to have this function?

**Comment by KenT2** [comment]
Yes, sorry, the request was a bit brief.

In dialog boxes you provide add_field and add_field_with_label. The equivalent of add_field for main pages is append and it would be useful to have append_with_label.

 add_field_with_label works with any type of widget and append_with label would do the same.

Have a look at #84 where I wonder if there is actually a need for add_field and append

**Comment by dddomodossola** [comment]
Hi Ken. Normally, in the examples script we written, Widgets are used as main pages. Widgets should not contain high level function like append_with_label. But, you can consider to use GenericDialog as main page.
