### ISSUE TITLE
asyncio [+ aiohttp] support

### ISSUE THREAD

**Issue by pohmelie** [dddomodossola/remi#90]
Since remi run in browser and there is client-server socket interatction, there is very good place for async io based mechanic. Also, I think there should be abstract layer between «transport» and server logic, so user can choose server and way to server on it's own and/or extend project. Even PyQt have awesome [quamash](https://github.com/harvimt/quamash). Or, if blocking logic is too hardcoded, then maybe create two way to run backend.

**Comment by pohmelie** [comment]
Any comments?

**Comment by nzjrs** [comment]
* one bug per suggestion
* asynio is an implementation detail not relevant unless you have actual performance problems
* I didn't understand at all what you meant by transport or why we would want that
* don't know why you think things are blocking or why it matters

**Comment by pohmelie** [comment]
I mean socket io is blocking, and thread based. This is not a performance issue, but what if I want use remi with my asyncio-based app?

**Comment by nzjrs** [comment]
there is nothing stopping you using remi with your asyncio based app

**Comment by pohmelie** [comment]
Nothing, except two incompatible loops.

**Comment by nzjrs** [comment]
I'm running remi in another application with 2 other incompatible loops. Works for me.

**Comment by pohmelie** [comment]
Of course this is possible , but why create new one, instead of using existing? And not all asyncio methods are thread safe.

**Comment by nzjrs** [comment]
Please file specific issues if you find concurrency bugs in remi or if you cannot integrate it with your code.

Remi is a gui framework, not a server one.

**Comment by pohmelie** [comment]
But it have server

**Comment by nzjrs** [comment]
The key word is framework.

Please file specific issues if you have them.
