### ISSUE TITLE
Logging stomps over any other logging

### ISSUE THREAD

**Issue by ttufts** [dddomodossola/remi#92]
I use a custom logger format and the basicConfig call loads a default formatter on the root logger. This causes duplicate log messages with the root format along with the log messages from my logger. 

I think I could avoid my log messages from propagating, but it seems like it would be better to avoid setting up the root logger and instead setting up a REMI logger.

**Comment by nzjrs** [comment]
Agreed. However you can always instantiate the Server yourself and therefor not get the logging basicConfig as applied in ```start()```
