### ISSUE TITLE
How can I run remi on a web host like pythonanywhere?

### ISSUE THREAD

**Issue by Paarthri** [dddomodossola/remi#95]
Title says it all.

**Comment by dddomodossola** [comment]
Hi Paarthri, I googled about this and it seems to be not possible. The problem is that pythonanywhere does not support sockets different from HTTP WSGI servers.
https://www.pythonanywhere.com/forums/topic/1034/
https://www.pythonanywhere.com/forums/topic/1652/

**Comment by Paarthri** [comment]
Thanks. Is there another free alternative to this?

**Comment by nzjrs** [comment]
https://c9.io/ or use and Amazon EC2 trial
