### ISSUE TITLE
How do I split a Remi App into Classes for modularity

### ISSUE THREAD

**Issue by KenT2** [dddomodossola/remi#97]
Hi
I am trying to make my  Remi application modular by defining a Dialog as a class but not having any success.

Attached is a simple App which demonstrates what I am trying to do and the problem. I'm sure the solution is very simple if only I knew what I was doing  :-(

[mc.zip](https://github.com/dddomodossola/remi/files/53210/mc.zip)

**Comment by nzjrs** [comment]
Can't you just derive from ```GenericDialog``` and do all your own customization in your ```__init__```?

Also, a zip file containing code is not so easy to review... can you attach it here or make a gist or put it on pastebin or something?

**Comment by KenT2** [comment]
Thanks John. I knew it would be simple.

You cannot attach a .py file to an Issue so here is a Gist of the solution, another good tip.

https://gist.github.com/KenT2/9f9cc514b8630ba735a2
